### ISSUE TITLE
angeltypes: Hidden flag

### ISSUE THREAD

**Issue by mortzu** [engelsystem/engelsystem#100]
**Reported by phaeusler on 1 Sep 42994305 17:20 UTC**
man muss engeltypen verstecken knnen

beispiel: vereinstisch engel

davon gibts 3 oder so...die machen das komplett selber

**Comment by gnomus** [comment]
Kann man über restricted Typen abdecken. und die, die sich nicht über das engelsystem organisieren setzt man auf force active
