### ISSUE TITLE
Replace `jquery` with plain javascript

### ISSUE THREAD

**Issue by ximex** [engelsystem/engelsystem#1001]
Replace `jquery` code with plain javascript for custom javascript code
`bootstrap` doesn't required jquery any more
`select2` still requires jquery. maybe we could also replace this to drop jquery completely

**Comment by MyIgel** [comment]
@weeman1337 wanted to have a look at this :+1:

**Comment by ximex** [comment]
Possible alternative: https://github.com/Choices-js/Choices
