### ISSUE TITLE
Rename `Räume` into `Örtlichkeiten`, `Lokalitäten` or `Standorte`

### ISSUE THREAD

**Issue by ximex** [engelsystem/engelsystem#1005]
this would be more general for example something outside

**Comment by MyIgel** [comment]
We could add that to the list of "improvements to be done after the db migration is done" :D

**Comment by cyroxx** [comment]
I find these suggestions a bit too formal or misleading.
How about something simple like `Ort` (`location`)?

**Comment by Corborax** [comment]
I am also in favor of the terms `Ort` / `Location`. 😄
