### ISSUE TITLE
Migrate from 2020 code to current

### ISSUE THREAD

**Issue by nilsnolde** [engelsystem/engelsystem#1099]
I was hacking in the email-on-notification thing from https://github.com/engelsystem/engelsystem/issues/296 (and would actually raise another issue asking if you'd be interested in it), but I did a grave mistake of accidentally basing my changes off a Dec 2020 codebase (v3.2.0). And that's not compatible with the Android app.

It's a running and currently pretty busy system (conference is in 3 weeks), and I'd need to migrate it to a newer version. I guess I'd have to go from 3.2.0 to at least 3.3.0 (according to the app developer). While I could just go ahead and try it sometime at night (after a backup;)), I wanted to ask if in your judgement the `migrate` script is safe to run? I'm not sure if or how I could judge if it really worked, as there might some corner/edge functionality that just works differently than it should..

**Comment by johnjohndoe** [comment]
Relates to https://github.com/engelsystem/engelsystem/issues/695#issuecomment-1440764517

**Comment by MyIgel** [comment]
@nilsnolde hi, the migrate script is safe to run ^^
If you want, I can also implement the send email on new message functionality (which means you have to either cherrypick the change or beta test the next release by using the current main branch ;))

**Comment by nilsnolde** [comment]
Wow, beautiful @MyIgel ! You guys are fast :smile: Thanks so much! Would've taken me at least a day or two to properly do it.

I set up the 3.3.0 on a clone of the running system, also no problems there. Very happy now:) Thanks again!

**Comment by MyIgel** [comment]
@nilsnolde  As that's just a change to the main branch some effort might be needed to apply the change to the 3.3.0 release. The easiest way would be to use the main branch which should be stable (hopefully, has some more changes) but if errors occur a note would be nice so that i can fix them ^^

**Comment by nilsnolde** [comment]
Ah yeah I know, but I already did hack it in 3.2.0. and ported it to 3.3.0, before you PRd it. But I’m sure others will very much enjoy it too, also we’ll be able to use it next year:)
