### ISSUE TITLE
Sorting is inconsistent between endpoints

### ISSUE THREAD

**Issue by MichiK** [engelsystem/engelsystem#1115]
In some endpoints, e.g. `/admin-arrive` and `/users`, the list of angels is properly sorted a-z, case-insensitive.

In `/angeltypes`, it is sorted case-sensitive, i.e. first A-Z, then a-z. This was very confusing to see.

**Comment by xuwhite** [comment]
for some reason we use sortBy and orderBy, that could be the reason why

angeltypes_controller.php: $members = $angeltype->userAngelTypes->sortBy('name');
admin_arrive.php:  $users = User::with('personalData')->orderBy('name')->get();
