### ISSUE TITLE
Disable time filter at shifts page

### ISSUE THREAD

**Issue by Whity07** [engelsystem/engelsystem#1132]
Hi!

Is there any option to disable the time filter to the shifts page?^(So anyone can see any shift at any time?)
Screenshot:
![image](https://user-images.githubusercontent.com/82459939/233775249-d321eaa0-dfbc-492e-9446-a4ce8bd919a5.png)

**Comment by MyIgel** [comment]
At the moment we don't have that option. What use case do you have for that?

**Comment by MyIgel** [comment]
That seems to be a good option on the first look but has some side effects.
Especially when having multiple rooms with many shifts having a whole day or even the whole event displayed at once requires more cpu resources (and adds additional load on the database).
