### ISSUE TITLE
Problems configuration to send Mails via SSL

### ISSUE THREAD

**Issue by Caeppi** [engelsystem/engelsystem#1134]
Hello again,
my Provide told me several times, that they no longer support sending Mails without encryption.

By checking my systems i found out, that my engelsystem is sending without, so i have to change it.

I tryed several option, but I do not know what parameter I have to use.

In the config I can find: (In deletes the correct mail)
        'host'       => env('MAIL_HOST', 'smtp.ionos.de'),
        'port'       => env('MAIL_PORT', 465),
        // Transport encryption like tls (for starttls) or ssl
        'encryption' => env('MAIL_ENCRYPTION', null),
        'username'   => env('MAIL_USERNAME', 'abs@abs.de'),
        'password'   => env('MAIL_PASSWORD', 'ficcow-tumVum-3fufqu'),
        'sendmail'   => env('MAIL_SENDMAIL', '/usr/sbin/sendmail -bs'),

I think, the correct way to change is MAIL_ENCRYPTION, but what do I have to take? I tryes SSL, TSL, STARTTSL; but every i get an error (monkeys are comming to fix the problem).

Accourding to my provider Port 465 should be correct.

Can everybody help?

Preetings
Patrick

**Comment by Caeppi** [comment]
I think, I found the Problem.

'encryption' => env('MAIL_ENCRYPTION', 'SSL'),

works fine :-)

Patrick

**Comment by MyIgel** [comment]
Happy to see that it worked! (And i hope that the password above is not the real one, if it is you should definitely change it).
As its solved i'll close this issue :)
