### ISSUE TITLE
Client-side confirmation of actions (e.g. deletion of a shift)

### ISSUE THREAD

**Issue by weeman1337** [engelsystem/engelsystem#1136]
**Problem description:**

Sometimes people have thick fingers and accidentally submit a change or delete something.

**Proposed solution:**

There should be a general client-side function that can be added to forms to ask for confirmation. This issue proposes a JavaScript function that hooks into form submissions if the attribute `data-confirm="text"` is present on a form element.

A confirmation modal should be displayed with the text of the attribute on form submission. [It should use the default Bootstrap modal.](https://getbootstrap.com/docs/5.3/components/modal/) The buttons should be in this order from left to right „No“ (default button) and „Yes“ (primary button). If `data-confirm` is preceded by another word, such as `data-confirm-danger`, this is used as the „Yes“ button type.

**Known problems / scope:**

The solution only works if the user has JavaScript enabled. Target are users with shift coordinator (or greater) power levels. These must have JavaScript enabled to work with the angel system anyway. A server-side solution is out of scope of this issue.

**Comment by MyIgel** [comment]
That sounds great!

**Comment by MyIgel** [comment]
(which would be even more complicated to do here)
