### ISSUE TITLE
Information in a personal message

### ISSUE THREAD

**Issue by Caeppi** [engelsystem/engelsystem#1139]
Hello,
the system sends an email to all users when you post a news item.
Is this also possible with a personal message?
So I write a personal message to a user in the system and the system notifies him that there is a message?
Couldn't find this.
I think it's a great function.

Thanks and best regards

**Comment by MyIgel** [comment]
Hi @Caeppi, when the user has enabled `Notify me on new private messages.` you could just send them a private message (letter icon in the menu), would that be sufficient enough?

**Comment by Caeppi** [comment]
I have 3 Buttons in my private menü:
1. Das xxx darf mir E-Mails senden (z.B. wenn sich meine Schichten ändern)
2. Notify me of new news
3. Allow heaven angels to contact you by e-mail.

I enabled all of them, but I am not getting any Mail-notification.

**Comment by MyIgel** [comment]
Ah, so you are using a release version :)

The "Send me messages on new PMs" was introduced in late February in fb8c05ed. If you need that feature you can use the main branch instead of the release version.
