### ISSUE TITLE
Make shifts only visible with needed angel type

### ISSUE THREAD

**Issue by sidri-zip** [engelsystem/engelsystem#1149]
During GPN we found that for some shifts it would be helpful to have the option that only people that are a member of the angel type can see the shifts that exclusively need this angel type.  
This would be nice for internal orga shifts we used the engelsystem for, but participants of the event do not need to see them on the dashboard.

**Comment by MyIgel** [comment]
That might make the shifts selection more complicated so i don't know if it would be a good idea but on the other hand seems to be somehow useful.. hmmm
and also this makes things more "hidden" which could be again the effort to make things transparent and open

**Comment by xuwhite** [comment]
There is an option to hide shifts of an angeltype from the dashboard. A participant set the filter to own angeltypes and only sees their available shifts in the shifts view
