### ISSUE TITLE
Hide t-shirt sizes (and other array configs) by setting their values to null

### ISSUE THREAD

**Issue by neumantm** [engelsystem/engelsystem#1154]
It seems, it is currently no longer possible to hide some t-shirt sizes by setting their value in the config to `null`.
Instead, for t-shirt sizes where the value is `null`, the key is displayed in the UI.

I'm using https://github.com/engelsystem/engelsystem/commit/fc8d335ea29f11fd8984df9cd67cde304fb5739a

**Comment by neumantm** [comment]
This seems to be a problem with twig.
When dumping the config from php, the `null`s are still there.
When dumping the config from within a twig template, the `null`s are replaced with empty strings.

**Comment by MyIgel** [comment]
Doing so (if it was possible at some point) was more a bug than a feature. The "[supported way](https://github.com/engelsystem/engelsystem#configuration-and-setup)" is (sadly still) to either modify the config.default.php or rename it to config.php and change it there.
Eventually changing this to a "supported way to do things" / "feature" might be possible

**Comment by neumantm** [comment]
I see. 
Then I'd suggest removing the second half of the following line until that possible change:
https://github.com/engelsystem/engelsystem/blob/9feed46d4e9149909c513acb57858e1a2acd317a/config/config.default.php#L330

**Comment by neumantm** [comment]
If you'd like I could look into implementing a solution for this.
I'd suggest implementing some logic in the following method which just removes the entry if the value is null in the end.
That way the change should be pretty small and automatically work for every such config option. 

https://github.com/engelsystem/engelsystem/blob/9feed46d4e9149909c513acb57858e1a2acd317a/src/Config/ConfigServiceProvider.php#L22-L45

Please tell me if I should go ahead with that idea.

**Comment by MyIgel** [comment]
That would be the same place i see that so i agree on this. But i would rather like to have a list of array keys that are then removed when their keys value is null -> `['themes', 'tshirt_sizes', 'headers', 'header_items', 'footer_items'']` and then check inside them if nulled value keys are dropped or not instead of on every config option
