### ISSUE TITLE
Set Secure Flag on Cookies

### ISSUE THREAD

**Issue by mweinelt** [engelsystem/engelsystem#1157]
When Cookies are set, the secure flag should be set, so they are only sent over HTTPS, which should be the default in 2023.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies?#restrict_access_to_cookies

**Comment by msquare** [comment]
Yep.

**Comment by MyIgel** [comment]
@msquare that change breaks in newest safaris: #1276
