### ISSUE TITLE
Character is not correctly displayed 

### ISSUE THREAD

**Issue by Corborax** [engelsystem/engelsystem#1162]
If I create a room that has an ' in the title / name it gets replaced after saving with

I. in /admin/rooms -> `&amp;#039;`
II. in /rooms?action=view&room_id=%number -> `&#039;`
III. in /admin/rooms/edit/%number -> name field: `&amp;amp;#039;` (double this time! and with _amp_)

**Example**
```
Fruit's house

I. Fruit&amp;#039;; house
II. Fruit&#039; house
III. Fruit&amp;amp;#039; house
```

**Comment by xuwhite** [comment]
I can only reproduce the problem in /admin/rooms/edit/%number there it looks like Fruit&#039;s house

**Comment by MyIgel** [comment]
This is also a problem with `&`

**Comment by msquare** [comment]
@Corborax thanks for reporting, should be fixed now in main. (#1173)
