### ISSUE TITLE
Abfrage zur IfsG Belehrung

### ISSUE THREAD

**Issue by MyIgel** [engelsystem/engelsystem#1167]
Es soll möglich sein, dass Engel das Vorhandensein der Belehrung nach § 43 Abs. 1 Infektionsschutzgesetz (aka Frikadellendiplom, sowohl "klein" als auch "groß"), analog zu Führerscheinen, eintragen können.
Auch diese Funktionalität soll als Soft-Requirement mit entsprechenden Hinweismeldungen zu Führerscheinen und Liste in der Tabelle des Engeltypen ausgegeben werden.
Potentielle Überprüfungen / Enforcen des status sind an dieser Stelle out of scope.

**Comment by MyIgel** [comment]
@xuwhite wollte sich das an schauen

**Comment by xuwhite** [comment]
Fast fertig

**Comment by MyIgel** [comment]
Ich freu mich drauf ^^
(for some definition von fast :P)
