### ISSUE TITLE
Die Schichten Generierung generiert bei potentiell kaputten eingaben sehr kaputte schichten

### ISSUE THREAD

**Issue by MyIgel** [engelsystem/engelsystem#1169]
![image](https://github.com/engelsystem/engelsystem/assets/1448057/10664c46-2631-4b90-af3f-24853aa2d4b9)

To be investigated / debugged, wahrscheinlich die `24:00`

**Comment by msquare** [comment]
Die 24 wird nun in eine 00 verwandelt, doppelte Schichtwechsel-Stunden entfernt und bei ungültigen Stundenangaben eine entsprechende Fehlermeldung erzeugt.
