### ISSUE TITLE
Feature improvement: Always include actual target date in mail subject

### ISSUE THREAD

**Issue by CodingSpiderFox** [engelsystem/engelsystem#1194]
During the last event I opted in to receiving notification mails from the engelsystem.

I successfully received emails with subject lines like these:

"[Engelsystem] Neue News: Angelshirts Day 4"
However I always find it not so easy to recognize "what day count are we at right now" (especially with the days -n to 0 because it is not so easy for everyone to know what day 0 refers to - is it the first actual event day or the last day before the official event starts?)

So I would like to have the subject like this instead 

"[Engelsystem] Neue News: Angelshirts Day 4 (xx.08.2023)" - always including the actual date that the news is relevant for.

**Comment by MyIgel** [comment]
Having that on every news is then more a convention than something we should add directly to every mail.
Eventually adding the event data to the footer of the email as it is done with the site itself might be a feasible option? (Including the "currently it's day x part)
