### ISSUE TITLE
Provide colloquial identifiers on date selection fields

### ISSUE THREAD

**Issue by extmind** [engelsystem/engelsystem#1203]
For date selection fields, where date pickers are not available, also provide the day of the week and possibly numbered day of the event. These are the identifiers that people usually use in communication rather than calendar dates. Thus, the correct selection is more obvious.

**Comment by MyIgel** [comment]
Which fields would that be? At the moment all date (and date+time) fields should use the browsers selects and thus should be available everywhere?

**Comment by extmind** [comment]
For example, on the details page for rooms and angeltypes, you have an overview of the corresponding shifts per day. The day is selected using a simple select field of various YYYY-MM-DD entries. Last time I used that, there was no date picker in sight.

**Comment by MyIgel** [comment]
The problem here is that shifts can be pretty irregular, depending on the use case of the engelsystem so a date picker would not fit in. Adding event days here might be useful indeed, but must be tested to know how it fits in.
