### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by psmoros** [engelsystem/engelsystem#1208]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@sev-hack) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by msquare** [comment]
Hi @psmoros 
Thank you for your investigations. Please send an e-mail with your findings to contact@engelsystem.de

I added a very basic SECURITY.md to the project.
