### ISSUE TITLE
Resend notification emails on news edit

### ISSUE THREAD

**Issue by MichiK** [engelsystem/engelsystem#1283]
Edits to news can change their content significantly. In this case it would be nice if we could resend notifications instead of having to delete and recreate the news (losing discussions in the process) to notify people.

This would need to be an optional checkbox (default off) so we don't trigger this all the time if someone fixed a typo.

**Comment by n-st** [comment]
Possibly this feature could also be used to allow for the opposite use case: creating a news entry without sending a notification.

**Comment by xuwhite** [comment]
This was already fixed in https://github.com/engelsystem/engelsystem/pull/1287
