### ISSUE TITLE
Catch duplicate news entries during submission

### ISSUE THREAD

**Issue by n-st** [engelsystem/engelsystem#1284]
In some circumstances (e.g. slow/unreliable internet connection, possibly also others), heaven users may (accidentally) submit the same news entry twice.
Currently, this immediately triggers mail notifications for both entries. The duplicate entry will usually be caught quickly and deleted, leaving the link in the notification mail dangling/404.

It would be useful if the Engelsystem would detect identical (or even "mostly identical") news posts and warn the user before actually posting them.

**Comment by MichiK** [comment]
When creating news lately I noticed that after submitting the form hangs for quite some time before it redirects. Looking in another tab shows that the news is created immediately but the loading of the next page takes long for some reason.

Msybe this is related.

**Comment by xuwhite** [comment]
fixed with https://github.com/engelsystem/engelsystem/pull/1287

**Comment by MyIgel** [comment]
That should not be the case anymore because submitting the same content twice is blocked by an error message
