### ISSUE TITLE
v3.5.0: /user-shifts "Alle/Keine" not doing anything

### ISSUE THREAD

**Issue by nilsnolde** [engelsystem/engelsystem#1338]
We deployed v3.5.0 for this year's FOSSGIS conference and it seems that the "Alle/Keine" filter options don't work, they're not doing anything:
![image](https://github.com/engelsystem/engelsystem/assets/25637358/46869665-9e88-4e26-9f7f-f955798ce524)

They're set e.g. here
https://github.com/engelsystem/engelsystem/blob/00f039dbaad8445d0f538e580448cfcbcdbad867/includes/pages/user_shifts.php#L303-L308

But my PHP is not up to scratch for much more debugging.. The server is running debian:bookworm with php v8.2.7, if that helps. I didn't try `master`, at a quick glance it seems there's no relevant code changes in master.

Anyone observing the same thing?

**Comment by MyIgel** [comment]
Looks like you have pretty outdated assets (js/css/images) at helfen.fossgis.de & the deployed version is `00f039d` which is the commit id of the release so you have deployed it via git?
In that case you have to build the assets using yarn, see [docs](https://github.com/engelsystem/engelsystem/blob/00f039dbaad8445d0f538e580448cfcbcdbad867/DEVELOPMENT.md#local-build-without-docker) for the needed steps.

**Comment by nilsnolde** [comment]
should've included the URL, kudos for finding it :) 

hmpf, that's very possible. I'll do that in a bit and (likely) close here. thanks!

**Comment by nilsnolde** [comment]
jep, all good:) thanks @MyIgel

**Comment by MyIgel** [comment]
Happy to help :)
