### ISSUE TITLE
Returning to unexpected page after deleting shifts

### ISSUE THREAD

**Issue by Lotterleben** [engelsystem/engelsystem#1342]
We're using the `📍location` overview to create our entire event shift plan.

When shifting things around, we noticed that after deleting a shift, we're redirected to the `user-shifts` page instead of the overview that we had previously found the shoft on. This was confusing to us, and makes editing our shifts very cumbersome as we have to do a lot of extra navigating (or oepning delete dialogues in separate tabs). 

Is this behavior intentional?

**Comment by MyIgel** [comment]
It is intentional as we normally use the shifts overview page to find shifts. A possible solution here is to use the confirmation modal which allows us to redirect the user back I
