### ISSUE TITLE
Nextcloud - SSO: You are not allowed to access this page

### ISSUE THREAD

**Issue by pasomm** [engelsystem/engelsystem#1358]
Hello,
I try to use Engelsystem with Nextcloud as SSO provider, but I received after "successful" Login:
"You are not allowed to access this page - Please log in."

My SSO configuration is as follows:
```
    'oauth'                   => [
          # Config
        'nextcloud' => [
            'name' => 'Nextcloud',
            'client_id' => 'xxxxxxxxxxxxxxx',
            'client_secret' => 'xxxxxxxxxxxxxxx',
            'url_auth' => 'https://nextcloud.de/index.php/apps/oauth2/authorize',
            'url_token' => 'https://nextcloud.de/index.php/apps/oauth2/api/v1/token',
            'url_info' => 'https://nextcloud.de/index.php/ocs/v2.php/cloud/user?format=json',
            'nested_info' => false,
            'id' => 'ocs.data.id',
            'username' => 'ocs.data.id',
            'email' => 'ocs.data.email',
        ],
```
My configured forwarding URL in Nextcloud is: https://engel.de/news. I have disabled the registration in the Engelsystem configuration.
Anybody got a tip to fix this problem?`Is it necessary to map the Nextcloud Usergroups to the Engelsystem Usergroups?

Note: I have replaced the URL to example URL.

**Comment by pasomm** [comment]
Hi @MyIgel,
thank you for your explaination. Now, it's working. The hint with the right redirection URL was missing for me.

**Comment by MyIgel** [comment]
Happy to hear that :)
