### ISSUE TITLE
User impersonated when adding or deleting a worklog

### ISSUE THREAD

**Issue by weeman1337** [engelsystem/engelsystem#1368]
**Description**

When adding or removing a worklog for a user it looks like that I am logged in as that user.

**Steps to reproduce**

- Log in as „admin“
- Go to user „peter“ settings
- Go to „Add work log“

Expected:

Upper right should show „admin“

What happens:

Upper right shows „peter“

**Comment by MyIgel** [comment]
Imho thats just a bug in the frontend (and less "impersonation" as its only changing the displayed name)
