### ISSUE TITLE
Schei� Encoding in "News updated" mail

### ISSUE THREAD

**Issue by MichiK** [engelsystem/engelsystem#1375]
Exhibit 1:

![Screenshot_20240330-130927](https://github.com/engelsystem/engelsystem/assets/6341204/ef94acdb-50a1-4545-8b06-6d7a4165fd82)

**Comment by MyIgel** [comment]
Das problem ist hierbei, dass der "renderer" an der stelle immer noch html rendert (und damit escaped) obwohl eigentlich text generiert wird.
Zum fixen muss wahrscheinlich ein "clear text renderer" / "mail text renderer" oder ähnlich erstellt werden welcher standardmäßig kein html excaping umsetzt -> tbd
