### ISSUE TITLE
Feature-Request: Confirmation-Dialog for taking back "Arrived" state

### ISSUE THREAD

**Issue by Wiiilmaa** [engelsystem/engelsystem#1439]
This action is only sparsely used. Most of the time it will be used accidentally, especially when initiated by an icon in a long list. Maybe even disable "unsetting" the arrived state in lists.

**Comment by MyIgel** [comment]
We have a confirmation dialog for deletions so it should be easily doable to adapt it.

Eventually other buttons could need that too so having a look there would be great.
