### ISSUE TITLE
"What do you want to do" is not explained

### ISSUE THREAD

**Issue by Arthur-Milchior** [engelsystem/engelsystem#1463]
How to reproduce.
* want to be an engel for the first time
* Go to https://engel.events.ccc.de/register and try to fill the form. Ensure it's in English.
* Read the question "what do you want to do", and try to understand what is the Späti Angel that is preselecetd, or what is FOC salesperson that is not preselected
* Read the angel guide https://angelguide.c3heaven.de/

Expected result:
* finding the words Späti or FOC somewhere.(This is the only explanaiton page linked here. It's linked from "T-shirt size" only)

Actual result:
* Filling with random selection and hoping it'll be easier to understand what the choices meant.

I'd suggest adding a link to the description, or adding the description to the angel guide. Or, if the angel guide already contains the description, ensure that the same vocabulary is used in the form and in the document so that details can be found

**Comment by EdJoPaTo** [comment]
The angeltypes have a description (When clicking on them from [`/angeltypes`](https://engel.events.ccc.de/angeltypes)). So the information exists in the Engelsystem. `/register` is indeed not that helpful without said description being shown or linked there.
