### ISSUE TITLE
Add member to angeltype as supporter

### ISSUE THREAD

**Issue by EdJoPaTo** [engelsystem/engelsystem#1464]
Currently, it's possible to add a member to an angeltype with a checkbox (confirm user). Especially on setting up an event the most used task is to create an angeltype and add the supporters for it. This is a multistep process currently: add member and then add supporter rights. It would be neat to do this in a single step.

Idea: Instead of the current "confirm user" checkbox 3 radio boxes could be helpful: Supporter, Member, Unconfirmed. Keeping the default the same would be Member.

**Comment by MyIgel** [comment]
As the "§confirm" checkbox is only shown when the angel type is restricted, adding another checkbox is easier here
