### ISSUE TITLE
Create/Edit Angel type field order

### ISSUE THREAD

**Issue by EdJoPaTo** [engelsystem/engelsystem#1470]
When viewing an angel type the contact is first, then the description.

When editing it its the other way around, first description, then contact. Personally I would put the one line thingies (contact) up top and then the description there too.

**Comment by MyIgel** [comment]
I would suggest "name, description, all contacts, state", splitting the name from the description makes it even more unreadable :D

**Comment by EdJoPaTo** [comment]
Whatever the order is, it should be the same on view and edit/create and in the template in the CCCV wiki.

**Comment by MyIgel** [comment]
I would definitely differentiate the view from the input (and wiki is another topic that can be fixed after it) as that are different usecases (but yes, eventually the output of contact data can be improved).

**Comment by EdJoPaTo** [comment]
Personally I find it confusing when reading stuff, hitting the edit button and then needing to parse the changed order of things.
