### ISSUE TITLE
Create Angel Type default should require introduction

### ISSUE THREAD

**Issue by EdJoPaTo** [engelsystem/engelsystem#1471]
Angel types should be as few as possible. If there is no introduction required, there is probably no need for a dedicated angel type. Therefore the default is to require an introduction. Its also easier to open up an existing angel type rather than closing it again.

So I propose having it enabled by default.

**Comment by MyIgel** [comment]
Even as this has the possibility that users might create angel types that all need introduction and get confused by that it might be indeed a good idea
