### ISSUE TITLE
Mobile phone number does not show in angel detail page

### ISSUE THREAD

**Issue by lubiana** [engelsystem/engelsystem#1476]
As a Schiko, when i click on the userpage of an angel that has a mobile phone number set, it does not show.
When i click on the edit page of that angel i can see that it exists. i would expect to see the mobile phone number at the same location where the dect number is shown

**Comment by MyIgel** [comment]
The config `enable_mobile_show` which shows the number is disabled (will show it for all angels) -> if its is off (as it is) the number is only visible in the config option and thus only to those who can edit a user -> works as configured :D
