### ISSUE TITLE
Double Signup as Supporter

### ISSUE THREAD

**Issue by cyriax0** [engelsystem/engelsystem#1480]
A user in the supporter role can sign up the same angel to the same shift in the same role twice.
This also might happen for themself by accident.

To reproduce:
Be supporter of any angeltype. Sign up to shift. Sign up to shift again.

Expected Behaviour:
The same angel should not be added to the shift more than once.

**Comment by cyriax0** [comment]
Example:
https://engel.events.ccc.de/shifts?action=view&shift_id=2394

**Comment by MyIgel** [comment]
This Bug is a feature which is used to block shifts (for example schedule imported shifts which are not recorded).
