### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by morphium86** [engelsystem/engelsystem#162]
Hi,
I just installed the engelsystem on my own environment. I did as told in the README, but cannot login. I just get back to the login page with the right password. With the wrong password I get an error message. I also tried resetting my password (changing the email via DB), but that didn't help, aswell.
Any suggestions where I could start to look? I am willing to answer via jabber i.e. - contact me at morphium@jabber.ccc.de.

Thanks in advance!
morphium

**Comment by JulianJacobi** [comment]
Hi,
ich habe jetzt gerade das selbe Problem, nur das keiner der Workarounds irgendeine Auswirkung hat.

**Comment by msquare** [comment]
Hallo Julian,
das war ein Programmierfehler, der ist jetzt behoben.

**Comment by fiedlfa** [comment]
Moin,
i have the same issue with an up-to-date master.  If i connect only via http the login does not work. If you need more time to fix this, at least write a comment in the Readme. It's annoying to not know this bug and searching for the error in the setup ;).

**Comment by gnomus** [comment]
I can't reproduce this Login via http works fine for me

**Comment by fiedlfa** [comment]
Es sieht für mich so aus, als ob man nur das erste mal man sich mit  einem Browser nicht per http verbinden kann (vllt. nutzt er die weiteren Male die Cookies die er über https vorher gewonnen hat? ich weiß es nicht). Nutzt du Firefox? Wenn ja versuch mal im Privaten Modus dich einzuloggen. Per HTTPS funktioniert es da bei mir, bei http nicht.

**Comment by gnomus** [comment]
Kanns lokal nicht reproduzieren :(
habe mal ne frische instanz aufgesetzt, da tritts dann wieder auf...
http://engel.kiffel.net/
