### ISSUE TITLE
Umlaute in Jabber JID nicht möglich

### ISSUE THREAD

**Issue by sycoso** [engelsystem/engelsystem#177]
Umlaute in der Jabber JID werden mit einem "Please check your jabber account information." quitiert.

**Comment by gnomus** [comment]
ecf25f5d2a1793671474fb9dfe816001b98b4770

Das hilft leider auch nicht
Es gibt leider kein perfektes E-Mail regex um alles zu überprüfen.
Evtl. kann man die überprüfung auch einfach mal rausnehmen. mit UTF-8 gibts je heutzutage eh die abstrusesten domains und damit auch e-mail adressen.
was denkst du @msquare ?

**Comment by msquare** [comment]
Ich denke wir können u.a. das Jabber Feld komplett entfernen, da wir die Daten nur sammeln und nicht verwenden. Die meisten Konferenzen, die das Engelsystem verwenden, basieren auf Leuten, die rumlaufen - da wird eher über DECT/Telefon/Handy oder Funken kommuniziert.

**Comment by msquare** [comment]
Bis jetzt bitte die Domain in Punycode konvertieren. Wenn PHP irgendwann auch Domains mit utf8 validieren kann, dann wird das funktionieren.
