### ISSUE TITLE
DECT calls

### ISSUE THREAD

**Issue by cookieBerlin** [engelsystem/engelsystem#183]
I need a JSON API with the DECT Numbers of the angels, that begins an Shift in given time slot.

For example : ?p=shifts_DECT_json_export&key=UserKeyOrApiKey&start_day=2014-12-29&start_time=15%3A00&end_day=2014-12-39&end_time=15%3A15

It will be nice to include the "Room name" and the "Angel Type" for every number

**Comment by gnomus** [comment]
@msquare Can we close this?
