### ISSUE TITLE
double spending of time when assigned by haven

### ISSUE THREAD

**Issue by MeraX** [engelsystem/engelsystem#184]
I had an double spending of one time slot in my shift.
I selected a Buildup shift from 18:00 to 20:00 but there was nothing to do for me. Therefore I went to haven and an archangel (sorry that I don't remember your name) had a new job for me, created a new shift (also from 18:00 to 20:00) and assigned me to it after work was done. So he probably used some kind of root privileges to create a conflict within the shifts "done" by me. (the time from both shifts count in my sum of work)

**Comment by gnomus** [comment]
Sorry, we can't fix Layer 8 Problems :D
