### ISSUE TITLE
Drop-down menu on phone/small screens

### ISSUE THREAD

**Issue by 20-100** [engelsystem/engelsystem#187]
When the screen is small (eg on a phone (a decent one that fits in a pocket, I mean)), the sections are gathered in a button like this : ≡

Then, when you click on it, you have a drop-down menu with them.
Problems :
 * you can't scroll in it, if you try, the page scrolls, not the menu
 * if you click/tap on it, sous often click on a link that is /behind/, in the page (that's possibly when you click on the line but not on the text of that line (eg I clicked on the blank space at the right of "Meetings" and endup on some user page that was linked in the text hidden by the drop-down menu))

**Comment by msquare** [comment]
Hi, can you please tell us the screen resolution for testing?

**Comment by 20-100** [comment]
According to http://whatismyandroidversion.com/ I have a 480x320 resolution.

About the versions : Android 2.3.4
I'm using the default browser, version 2.3.4. Maybe he's the crappy one, but I can't test with an other one because of small resources.

**Comment by msquare** [comment]
Thank you for this hint. Do you have any idea how to solve big dropdown-menus for small screens with bootstrap?

**Comment by gnomus** [comment]
I think this problem is not solvable. The resolution is just to small :(
