### ISSUE TITLE
Dropdownmenus are not working

### ISSUE THREAD

**Issue by Boggythescout** [engelsystem/engelsystem#191]
I've installed it on a server with PHP 5.4.38 but the Dropdown menus are not working.

**Comment by msquare** [comment]
Do you mean the admin dropdown menu?
Can I view your instance anywhere?
Is JavaScript in enabled?

**Comment by Boggythescout** [comment]
www.roversystem.de
JavaScript is enabled.

**Comment by msquare** [comment]
Did you checkout the submodules? (With git submodule init and git submodule update)
It seems that bootstrap is missing. (e.g. vendor/bootstrap/js/bootstrap.min.js)
This leads also to the missing icons.

**Comment by Boggythescout** [comment]
I've uploaded bootstrap. 
But the file you are mentioning seems like it isn't even in the repository of bootstrap.

**Comment by msquare** [comment]
The bootstrap submodule is in vendor/bootstrap/
And then there is a symlink linking the public needed files from that folder:
public/vendor/bootstrap -> vendor/bootstrap/dist
Does this symlink work for your clone and your webserver?

**Comment by Boggythescout** [comment]
I've cloned the repository via github vor Windows and synced it with "git pull --recurse-submodules" and "git submodule update --recursive"
Then I have everything down on my PC which is in the bootstrap repository.
But this path vendor/bootstrap/js/bootstrap.min.js doesn't exist. Neither on my PC nor on the bootstrap repository

**Comment by msquare** [comment]
There should be this file: https://github.com/twbs/bootstrap/blob/9f5660c3e3b3d392529d07c4f2cfe0aba2abbe89/dist/js/bootstrap.min.js
The path should be vendor/bootstrap/dist/js/bootstrap.min.js and with the symlink public/vendor/bootstrap/js/bootstrap.min.js
I still couldn't figure out why this does not work for you, sorry!

**Comment by msquare** [comment]
A workaround should be to copy the dist-directory from bootstrap manually to public/vendor/bootstrap/

**Comment by gnomus** [comment]
@msquare Solved?

**Comment by timowulff** [comment]
This solved it for me:
> A workaround should be to copy the dist-directory from bootstrap manually to public/vendor/bootstrap/

and to:
vendor/bootstrap/dist/js/bootstrap.min.js
Thanks.
