### ISSUE TITLE
Driving License information

### ISSUE THREAD

**Issue by zeidlos** [engelsystem/engelsystem#198]
As a shiftcoordinator I want to see what type of driving license a user has. Also I want to know if he has his own car with him and is willing to drive any vehicle (including his own) to drive stuff around for the PL.

Options: 

[ ] I am willing to operate cars for the PL
[ ] I have my own car with me and am willing to use it for the PL.
(You'll get reimbursed for fuel)

I have the following driving permits:
1. Car
2. Transporter 3,5T
3. Truck 7,5T
4. Truck 12,5T
5. Forklift

**Comment by gnomus** [comment]
@zeidlos Is this really needed?
Datensparsamkeit is an Issue here
