### ISSUE TITLE
Date format for the shift view and the detail view differs

### ISSUE THREAD

**Issue by ambro42** [engelsystem/engelsystem#202]
In the overview where you pick the shifts (https://engelsystem.de/cccamp15/?p=user_shifts) it says for example 14.08. but if you click on a the shift (https://engelsystem.de/cccamp15/?p=shifts&action=view&shift_id=696) it says 15-08-14. This is rather confusing.

**Comment by 20-100** [comment]
Agreed. Especially with camp dates in the middle of the month (and not 26-30), we have trouble with 2015's "15".
You might subsribe a shift/check its date the wrong day, especially if you're tired or in a hurry.
https://xkcd.com/1179/
