### ISSUE TITLE
Messages dropdown/popover isn't displayed in safari 

### ISSUE THREAD

**Issue by saerdnaer** [engelsystem/engelsystem#203]
In Safari on OS X the messages dropdown popover is not shown. Also the tringle icon doesn't move.

**Comment by gnomus** [comment]
Can't reproduce Please provide more Information

**Comment by gnomus** [comment]
@msquare Can you reproduce this?

**Comment by saerdnaer** [comment]
Here a screenshot from Safari and Chrome. I couldn't find a way to open this popover in Safari.
![Screenshot](https://cloud.githubusercontent.com/assets/40266/9564212/037a8bcc-4e9f-11e5-85c0-1a36369c0ffb.png)

**Comment by saerdnaer** [comment]
Any updates on this issue?

**Comment by saerdnaer** [comment]
Confirmed. Thanks!
