### ISSUE TITLE
notify angels about multipliers (e.g. night shift)

### ISSUE THREAD

**Issue by katrinleinweber** [engelsystem/engelsystem#205]
Because there were different info vagabonding around CCCamp15 about night shifts between sometime and sometime counting more, it would be cool to have a definite place to announce such info to the angels, without taking time away from meeting.

IMHO the bottom of the `?p=users&action=view` page after `Sum: N h` would be best: `(night shifts from x a.m. to y a.m. count Z-fold)`. In that case, coordinators would only always have to refer people to that page & wouldn't need to discuss changes.

Unless you want to avoid advertising this too much, a little `Z-fold` icon in the shift blocks might also help avoid confusion here.

**Comment by msquare** [comment]
Fixed. There is a hint now on the user's own view.
