### ISSUE TITLE
Angelsystem does either not count nightshifts with the double of usual hours, or incorrectly presents the sum of hours including nightshifts

### ISSUE THREAD

**Issue by trailblazr** [engelsystem/engelsystem#208]
Angelsystem does either not count nightshifts with the double of usual hours, or incorrectly presents the sum of hours including nightshifts.

Users who did night shifts usually get their hours counted with the duplicate amount of the hours. This seems to not work at the moment.

**Comment by gnomus** [comment]
It works but it is only calculated correctly in the Admin View

@msquare Shall we change this or is it on purpose?

**Comment by ulope** [comment]
Not to put too fine a point in this but it's quite demoralizing to see the wrong number of hours in your profile view after pulling a 4h night shift :(

**Comment by msquare** [comment]
For now the user page is supposed to show the hours of work you have done, not the special calculated hours for t-shirt accounting. This may change in future.
