### ISSUE TITLE
MySQL-query error beim Erstellen von Shifts

### ISSUE THREAD

**Issue by nafur** [engelsystem/engelsystem#211]
Hi,

I tried to create a new shift in a demo setup. After the preview seemed perfectly fine, this resulted in the error "Unable to create shift" as well as the following log output:

mysql_provider error: MySQL-query error: INSERT INTO `Shifts` SET
   `shifttype_id`='5',
   `start`='1440489600',
   `end`='1440496800',
   `RID`='1',
   `title`='Videoaufzeichnung',
   `URL`=NULL,
   `PSID`=NULL,
   `created_by_user_id`='1',
   `created_at_timestamp`=1440508356 (1054) Unknown column 'created_by_user_id' in 'field list'
#0  sql_error(MySQL-query error: INSERT INTO `Shifts` SET
   `shifttype_id`='5',
   `start`='1440489600',
   `end`='1440496800',
   `RID`='1',
   `title`='Videoaufzeichnung',
   `URL`=NULL,
   `PSID`=NULL,
   `created_by_user_id`='1',
   `created_at_timestamp`=1440508356 (1054) Unknown column 'created_by_user_id' in 'field list') called at [/www/helfer/engelsystem/includes/mysqli_provider.php:149]
#1  sql_query(INSERT INTO `Shifts` SET
   `shifttype_id`='5',
   `start`='1440489600',
   `end`='1440496800',
   `RID`='1',
   `title`='Videoaufzeichnung',
   `URL`=NULL,
   `PSID`=NULL,
   `created_by_user_id`='1',
   `created_at_timestamp`=1440508356) called at [/www/helfer/engelsystem/includes/model/Shifts_model.php:150]
#2  Shift_create(Array ([start] => 1440489600,[end] => 1440496800,[RID] => 1,[title] => Videoaufzeichnung,[shifttype_id] => 5,[URL] => ,[PSID] => )) called at [/www/helfer/engelsystem/includes/pages/admin_shifts.php:268]
#3  admin_shifts() called at [/www/helfer/engelsystem/public/index.php:129]

**Comment by nafur** [comment]
Ich vermute, dass das ganze mit dem einspielen der update.sql gefixt wäre. Das allerdings klappt auch nicht (auf einer komplett leeren Datenbank):

$ mysql -u user -p -D helfer < db/install.sql 
$ mysql -u user -p -D helfer < db/update.sql
ERROR 1005 (HY000) at line 11: Can't create table 'helfer.#sql-b63_5e383' (errno: 150)

Ich verwende die aktuelle Version des Helfersystems (commit 7a5dc3483527d444ad7786ce8d0ddc00c8bb33dc) sowie mysql-server 5.5.41

**Comment by msquare** [comment]
Hi,

you were nearly right. I updated the install.sql file - it was outdated since the last quick changes on chaos communication camp.
Please do a git pull und recreate the database using the updated install.sql.

Thank you!

**Comment by nafur** [comment]
Ah, nice. Thanks.
