### ISSUE TITLE
Is it possible to send a direct message to another Angel?

### ISSUE THREAD

**Issue by stefek99** [engelsystem/engelsystem#214]
I had a really good time at #cccamp15 and there is one person I really want to stay in touch...

*(we exchanged addresses but for some reason it didn't work out)*

Do you support direct messages between Angels?

If that is not supported - can I bribe you to release email address of that particular person?

My engelsystem login: **stefek99**
Login of the person I want to stay in touch: **yogi**
My email address: mstefanow@gmail.com
If I could receive email address of that person that would be super-awesome.

But of course we are all *hackers* and we treat privacy / security very seriously so... Maybe if you could ask him *"stefek99 wants to be in touch, is it OK if we share your email"* - that would be rather OK...

(and my gratitude would be endless)

**Comment by gnomus** [comment]
Yes that is possible.
https://engelsystem.de/cccamp15/?p=user_messages

We won't disclose userdata

**Comment by stefek99** [comment]
That is perfect. Thank you.
