### ISSUE TITLE
oauth support 

### ISSUE THREAD

**Issue by baracoder** [engelsystem/engelsystem#215]
allow users to authenticate with oauth accounts

**Comment by andynd** [comment]
@MyIgel wie vorhin im Mumble besprochen:

Wir bauen da aktuell das https://git.cccv.de/infra/uffd/uffd für die CCCV auf was für Crews eine SSO und über oauth2 auch eine Auth Schnittstelle bereitstellt. Es wäre total cool das zum nächsten (präsenz) Congress benutzen zu können um den Crews nicht jedes Jahr aufs neue Accounts anlegen zu müssen. Total cooles Bonusfeature: Teamverantwortliche auf "Gruppe aus foobar im auth" setzen.
