### ISSUE TITLE
Subject and Message of 'News' should be escaped

### ISSUE THREAD

**Issue by cko** [engelsystem/engelsystem#219]
Neither the subject nor the message of a new 'News' entry is escaped. This makes the application vulnerable for XSS. 

Can be tested by adding a news entry with a subject and message of `<script language="JavaScript">alert ('Hallo Welt!');</script>`

**Comment by Don42** [comment]
Has this been fixed?
Are fields provided by users vulnerable?

**Comment by msquare** [comment]
See #230
