### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by TobiasRe** [engelsystem/engelsystem#222]
Right now there is an Android client app missing for the Engelsystem.
I would like to start with the implementation with it.  Is there already any work towards a mobile Client done, or will I start with a fresh sheet of paper.

**Comment by DaspawnW** [comment]
On which platform did you develop the app? On Platformspecific Java or independent Cordova?

**Comment by TobiasRe** [comment]
There's nothing done yet. But I would definitely go the native Java approach.

**Comment by DaspawnW** [comment]
I think the con is, that you have only an application for android and not for platformindenendence.
With http://ionicframework.com/ and https://github.com/phonegap/phonegap-plugin-push you have a platformindependent approach

**Comment by TobiasRe** [comment]
I know. But there already is a cross-platform client: The web application! 
The native app shall be tailored specifically for the platform. The best approach for that is to go native.

**Comment by jschpp** [comment]
Has there been any progress with this?

**Comment by dasJ** [comment]
What about integrating it into the fahrplan? So I can see if there are no relevant talks while searching for a shift.

**Comment by msquare** [comment]
This needs an api. There are issues for an api.

Android app is out of the projects scope and has to be made by other people.
