### ISSUE TITLE
HTML-Code in news is not escaped

### ISSUE THREAD

**Issue by kakohari** [engelsystem/engelsystem#230]
When saving stuff like "</klugscheißmodus>" in a comment the string is not escaped but probably simply discarded.
Don't know if this should be treated as a problem or as "lack of fancyness" :-)

Expectation: Everything entered in the comment field is stored and displayed after sending/saving
How is it? Not everything shows up.
Reproduce: Put stuff in < > oder </ > in the comment field
Why? Do do some really nerdish commenting without emojis.

**Comment by msquare** [comment]
This is by intent. We included a privilege/role to enable HTML, without this privilege HTML is escaped.
