### ISSUE TITLE
Issues with merged shifts

### ISSUE THREAD

**Issue by 20-100** [engelsystem/engelsystem#232]
I don't know if this is new on the engelsystem this year, but I have the feeling that some shifts have been merged. Meaning the system states several AngelTypes are needed for the same slot.

I think this was actually an excellent idea: in this way, all talk-related shifts appear in the same slot.
But this raises some problems I'm trying to list here:
- Maybe #229 (displaying slots in which you cannot help), but I couldn't reproduce
- Autogenerated e-mail tells you "Your shift has been deleted/assigned/changed" stating this is a "Talk" shift. But what was I supposed to do in this talk ?
- On the AngelHub (displayed in heaven), you can see quickly (for instance) that in Hall 2 we need 2 microphone angels, 1 camera angel, then 2 angels, then 1 angel. But what for? I think that this is also due to the fact that there is only one icon by AngelType and not one by Shift Type. Don't know if this should be fixed here or on the AngelHub, maybe a bit of both.

Also, why isn't the VOC Coordinator merged in the Talk shift? (I could ask the same for Translator Angels but their shifts do not exist at all in the system at the moment)
Maybe there should be a slot "Talk" and a slot "Talk Coordinators" for Heralds, Stage-Managers, VOC Coordinator, Subtitle Angel Coordinators who take several shifts in a row. I think this would solve many problems we have currently in 32c3.

**Comment by msquare** [comment]
Since this is more an organisational point for heaven and no specific problem or feature is described, I will close this now.
