### ISSUE TITLE
Schichtüberschneidungen werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by jack32c3** [engelsystem/engelsystem#233]
Ich habe den Skin 32c3 eingestellt.
also:
weiß: gebuchte Schicht
gelb: blockierte Schichten

wenn ich, über den Filter, den Raum ( in welchem ich schon eine Schicht gebuchthabe) ausblende,
dann werden in der Schicht-Übersicht die Überschneidenden Schichten nicht mehr gelb angezeigt sondern rot (wenn noch was frei ist).
Es ist sogar der Button "Eintragen" vorhanden. 
Wenn ich auf "Eintragen" Clicke wird mir, korrekter weise, die Eintragung der Schicht verboten.

Gruß
Jack

**Comment by msquare** [comment]
Sollte inzwischen funktionieren.
