### ISSUE TITLE
German language is not working

### ISSUE THREAD

**Issue by escii** [engelsystem/engelsystem#238]
I see the "de_DE.UTF-8" translation files, also there are german phrases inside but it does somehow not get loaded, even if you choose "Deutsch" from the upper right menue the labels will stay english.

any ideas?

**Comment by msquare** [comment]
Please ensure, that the locale "de_DE.UTF-8" is installed on your system.

**Comment by escii** [comment]
works! thanks :)

**Comment by Nos-** [comment]
`localectl set-locale "LANG=de_DE.UTF-8"` helped me.
