### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by thegempie** [engelsystem/engelsystem#244]
HI,
I tried to set up the Engelsystem for our local refugee help group. Honestly, I am pretty new to running a website, Apache, MySql and PHP, so I'm almost sure that I did something wrong.
To check if I  could set up the engelsystem I tried it first in my local network on my raspberry pi.
I have a Mediawiki and a Wordpress installation running  on the same raspberry apache server, too.
So I moved the content of engelsystem-master to a folder "engelsystem-master" in /var/www/html and changed the permissions of the folder import so that www-data has read and write permission. 
Afterwards I changed the line "DocumentRoot /var/www/html/" to "DocumentRoot /var/www/html/engelsystem-master/public" in  /etc/apache2/sites-available/000-default.conf.
I used an existing wordpress sql database and ran install.sql and update.sql on this one.
I changed the config.php in the config folder so that it got the credentials of my database.
I tried to go to the engelsystem in my browser (IP/engelsystem/public/index.php) and it threw me an error 500.
What did i do wrong? Any help is appreciated :)
Thanks in advance,
thegempie

**Comment by runjak** [comment]
Hi,
I assume that you've also inserted `db/install.sql` and `db/update.sql` into your database as described?
Is there anything useful in your log messages for the http `500` error?
I'll try to reproduce the setup steps on my side and see if I can run into a similar issue.

**Comment by thegempie** [comment]
Genau, die beiden SQL Scripte habe ich in die Datenbank importiert.

Das Log sieht folgendermaßen aus (aus /var/log/apache2/error.log.1):
`
[Mon Feb 22 05:25:56.853087 2016] [:error] [pid 1014] [client 192.168.2.112:49514] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 80, referer: http://192.168.2.35/engelsystem-master/
[Mon Feb 22 05:25:56.853375 2016] [:error] [pid 1014] [client 192.168.2.112:49514] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 80, referer: http://192.168.2.35/engelsystem-master/
[Mon Feb 22 05:47:59.397943 2016] [:error] [pid 1011] [client 192.168.2.112:49617] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 80
[Mon Feb 22 05:47:59.398240 2016] [:error] [pid 1011] [client 192.168.2.112:49617] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 80
[Mon Feb 22 05:59:02.492268 2016] [:error] [pid 1013] [client 192.168.2.112:49690] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53, referer: http://192.168.2.35/engelsystem-master/
[Mon Feb 22 05:59:02.492584 2016] [:error] [pid 1013] [client 192.168.2.112:49690] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53, referer: http://192.168.2.35/engelsystem-master/
[Mon Feb 22 05:59:03.821711 2016] [:error] [pid 1011] [client 192.168.2.112:49696] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 05:59:03.821984 2016] [:error] [pid 1011] [client 192.168.2.112:49696] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 05:59:27.185961 2016] [:error] [pid 2068] [client 192.168.2.112:49701] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 05:59:27.186271 2016] [:error] [pid 2068] [client 192.168.2.112:49701] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 06:04:15.887627 2016] [:error] [pid 1015] [client 192.168.2.112:49734] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 06:04:15.887883 2016] [:error] [pid 1015] [client 192.168.2.112:49734] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 06:04:17.508946 2016] [:error] [pid 2067] [client 192.168.2.112:49735] PHP Warning:  require_once(/var/www/html/engelsystem-master/public): failed to open stream: No such file or directory in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 06:04:17.523318 2016] [:error] [pid 2067] [client 192.168.2.112:49735] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/engelsystem-master/includes/engelsystem_provider.php on line 53
[Mon Feb 22 06:25:08.481177 2016] [mpm_prefork:notice] [pid 822] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/www/html/engelsystem-master/public] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
`

**Comment by runjak** [comment]
First off: Good to know you've put the `SQL` scripts in the database and thanks for posting the logs :smiley:.

The [public/index.php](https://github.com/engelsystem/engelsystem/blob/master/public/index.php#L2) file needs access to the `engelsystem_provider.php` mentioned in the logs.
This file showing up in the logs gives confidence that the `index.php` is accessible as expected.
It hints, however, that the required include directory may either not exist where it should or may not be accessible by the user that your apache instance uses.

If you have sudo installed you could test if a file is accessible via something like
```
sudo -u www-data file /var/www/html/engelsystem-master/includes/engelsystem_provider.php
```
where `www-data` would be the apache user.
Otherwise you could check by investigating file permissions or starting a shell as the apache user to test this.

I'll see if I can think of other reasons for this problem…

**Comment by thegempie** [comment]
Yeah, that helped, I thought I changed the permissions, but looks like i didn't. Thanks a lot :+1:

**Comment by runjak** [comment]
:cool::cool::cool:, nice to hear that you could solve it.
