### ISSUE TITLE
Necessity to set /public as document root?

### ISSUE THREAD

**Issue by thegempie** [engelsystem/engelsystem#248]
Hi,

I want to use the engelsystem as a shift planning tool for our local refugee support group. I have set it up on my local network to check if it works, and it does, but i ran into a problem when i tried to put it on my website: I use a webhoster and don't have access to the apache configuration files, so i'm not able to change the document root, which I think i must(?). Is it possible to circumvent changing the http-root directory?
Additionally, I'd like to have the engelsystem in use on a domain with several webpages, so it would be great if i could have the URLs like this: "example.de/wiki", "example.de/wordpress", "example.de/engelsystem".

Any help is appreciated :)

**Comment by msquare** [comment]
Most of the webhosters offer an "entry point" configuration option, where you specify the "document root", "/public" for the engelsystem. Maybe you can use some symlink magic somehow? Or you use /engelsystem/public as url but make shure that others can't access the config files.

**Comment by msquare** [comment]
For security reasons we will not change this in the near future.
