### ISSUE TITLE
Can't seem to log out on the mobile version of the site

### ISSUE THREAD

**Issue by icedwater** [engelsystem/engelsystem#249]
I don't find the option anywhere in the drop-down menu. I'll see if I can toss in a patch.

**Comment by msquare** [comment]
Klick on the little dropdown icon on the bottom of the menu. Then logout appears.
![bildschirmfoto 2016-03-22 um 14 56 27](https://cloud.githubusercontent.com/assets/575004/13953837/496cb07e-f03e-11e5-9a35-faf10091f125.png)

**Comment by icedwater** [comment]
Yep, it wasn't obvious because the initial view of the menu didn't have the dropdown icon. I'm on Android 5.0.2 using Chrome 47.0.2526.83, here's what I saw:
![scrolled_menu](https://cloud.githubusercontent.com/assets/144799/14044852/b44bef48-f2cf-11e5-8f5f-bfe23113f042.png)
I wouldn't have thought to scroll the menu down either. I'll see if I can find out what it is.

**Comment by msquare** [comment]
The height of the menu is fixed by bootstrap. Since the navbar has "position: fixed", the only fix to this would be to set the height of the menu by javascript, fitting to the device screen.

**Comment by digitaldonkey** [comment]
Please test https://github.com/engelsystem/engelsystem/pull/713
