### ISSUE TITLE
Unable to create angeltype

### ISSUE THREAD

**Issue by kamishettysreeja25** [engelsystem/engelsystem#251]
Admin is unable to create new angel type.

**Comment by msquare** [comment]
Creating new angeltypes works for me as admin on a fresh install of the engelsystem.
Can you please provide more information/steps/things you entered?

**Comment by kamishettysreeja25** [comment]
![screenshot from 2016-03-22 19 18 38](https://cloud.githubusercontent.com/assets/14835922/13953626/e817d70c-f062-11e5-8d65-b8b9e5aad07f.png)

when i logged in as admin  i was unable to create a engeltype on my local server .

**Comment by msquare** [comment]
There must be a stack trace in your webserver's error log. Can you paste it?
Did you pull the latest master from git? Did you execute install.sql and update.sql?

**Comment by kamishettysreeja25** [comment]
![screenshot from 2016-03-22 19 45 05](https://cloud.githubusercontent.com/assets/14835922/13954400/9ec1104c-f066-11e5-9bb3-a75094d49172.png)

this is the error log and i have executed install.sql and update.sql

**Comment by msquare** [comment]
Ok, so what does your `config.php` looks like? (Without passwords please)

**Comment by kamishettysreeja25** [comment]
i found out the bug when i was running update.php file in engelsystem/db 
![screenshot from 2016-03-22 21 18 49](https://cloud.githubusercontent.com/assets/14835922/13957772/b2fa7b68-f073-11e5-9b24-ce9cc413512a.png)

showing this error,
in /db/update.php  mysql_provider.php is called   but the file is named  /includes/mysqli_provider.php

**Comment by kamishettysreeja25** [comment]
@msquare 
I am want to  take up  engel system project for gsoc 2016 .
Could you please tell me what all new features ,improvisations and expectations are required for engelsystem project . 
I have written a proposal for gsoc having the basic wireframes could you please review it and give me suggestions/feedback  so that i could improve it and work on it .
Thank You :) 
https://docs.google.com/document/d/1ILaow_2wIS0JS_R0vwrSSZcwuUhDkFeXAZjKcbo0SPE/edit#
