### ISSUE TITLE
Disallow SelfSignup for Shifts

### ISSUE THREAD

**Issue by jwacalex** [engelsystem/engelsystem#253]
If you approve someone for a group, this person is allowed to sign up for restricted shifts on its own. 
In some cases you want to accept people as a certain type of angel (eg. heralds, subtitles or video\* angels) but want also do distribute those shifts at a certain meeting.
The current fix is "not to accept anyone for this group", but this leads to confusion for the angels (e.g "you said I'm confirmed but I'm still listed as unconfirmed).

**Comment by percidae** [comment]
+1 from the subtitles team!
A more "angel friendly & motivating" fix would be very much appreciated.

**Comment by jwacalex** [comment]
Short update on this issue. After clarifying the scope and "how to implement" with @msquare I've [forked](https://github.com/jwacalex/engelsystem/tree/gh_issue_253_disallow_selfsignup_for_shifts) the project and going to prepare a patch.

**Comment by msquare** [comment]
Feature is merged.
