### ISSUE TITLE
Welche Voraussetzungen?

### ISSUE THREAD

**Issue by hollosch** [engelsystem/engelsystem#255]
Hallo,
welche Voraussetzungen an Server-Infrastruktur wird denn für eine Installation benötigt, oder kann man das System auch auf einem "normalen" Webspace installieren ?

**Comment by gnomus** [comment]
Ausprobiert habe ich es noch nicht, aber php und mysql sollten ausreichen

**Comment by hollosch** [comment]
Irgendwie bekomme ich das System nicht zum Laufen. Gibt es irgendwo eine Insatllationsanleitung für "Dummies" ?

**Comment by mkuh** [comment]
wo hackt es den ? Wo habt ihr euren Webspace ?

**Comment by gnomus** [comment]
nein
