### ISSUE TITLE
Login not possible, "Unable to load user angeltypes."

### ISSUE THREAD

**Issue by jubafest** [engelsystem/engelsystem#256]
Hey,

after I enter the default admin username and password on my fresh installation of engelsystem, the system redirected me to http://domain.tld/?p=news.

But instead of the dashboard or something else I only get the message 
`"Unable to load user angeltypes."`
on a white screen.

After I changed the PHP-version to 5.5, the following error appeared: 

```
Warning: require_once(/.../engelsystem/public): failed to open stream: No such file or directory in /.../engelsystem/includes/engelsystem_provider.php on line 53

Fatal error: require_once(): Failed opening required '' (include_path='.:/.../php-5.5.34/lib/php') in /.../engelsystem/includes/engelsystem_provider.php on line 53
```

I uploaded the .sql-Files (install.sql and update.sql) into the database, I generated a config.php, exaktly like in the installation instruction. Do you have any idea what the problem could be?

Thanks a lot!

**Comment by kamishettysreeja25** [comment]
hi ,
This issue was asked here #251 .  Now I am able to load angeltype . Did you clone it using --recursive flag ?

**Comment by msquare** [comment]
Closed, since no more activity.
