### ISSUE TITLE
List of Languages required for localisation 

### ISSUE THREAD

**Issue by kamishettysreeja25** [engelsystem/engelsystem#257]
I would like to implement localisation in different languages as it will make this system reach many people across the world.
I would like to know what all languages are required to be implemented?
Currently I have implemented localisation in hindi 
https://github.com/engelsystem/engelsystem/pull/252/commits/c80ccd492c0f95d54cf9827a1778eb2df20ea4ab
Thank you.

**Comment by mariobehling** [comment]
@kamishettysreeja25 Hi, I do not understand the questions, cause the languages required apparently depend on the people and events using it. So, potentially we need all languages.

**Comment by kamishettysreeja25** [comment]
@mariobehling As we are widely using this system for volunteer coordination for fossasia.It is sufficient to implement Asian languages. We can implement local languages where we have summits and places where  more  people volunteer ,  as an initial step and can be extended to languages, which the users  want .So by creating an issue we can know what all languages the users want :) .
