### ISSUE TITLE
Creating Unit Tests 

### ISSUE THREAD

**Issue by kamishettysreeja25** [engelsystem/engelsystem#258]
Creating unit tests for model and controller.

**Comment by vuhung** [comment]
This is a good idea, but a big task though.

Why not divide this tasks into smaller, manage-able one, per-file, per-feature and finish one by one?

**Comment by kamishettysreeja25** [comment]
@vuhung ,Yeah very good idea we can do it like that :) .
We can divide the work based on files and we can work together.

**Comment by msquare** [comment]
As mentioned, the task should be splitted into smaller chunks.
