### ISSUE TITLE
Translate README.md

### ISSUE THREAD

**Issue by vuhung** [engelsystem/engelsystem#259]
Some of us doesn't read Germany.

So, I suggest that we translate, at least, readme file to English :) 

https://github.com/engelsystem/engelsystem/blob/master/README.md

Please don't point me to Google or Bing translation :)

**Comment by kamishettysreeja25** [comment]
@vuhung  there exists a readme in English also .
https://github.com/engelsystem/engelsystem/blob/master/README-ENG.md 
Which contains all the instructions in English :)

**Comment by vuhung** [comment]
@kamishettysreeja25 Thanks. I close this ticket now :)
