### ISSUE TITLE
Ausklappmenü geht nicht

### ISSUE THREAD

**Issue by hollosch** [engelsystem/engelsystem#261]
Hallo,
das Admin-Ausklappmenü funktioniert bei unserer Installation nicht.

Die Links sind im Code vorhanden, aber das Menü klappt nicht auf:

`<li class=""><a href="?p=admin_arrive">Angekommene Engel</a></li> <li class=""><a href="?p=admin_active">Aktive Engel</a></li> <li class=""><a href="?p=admin_user">Engelliste</a></li>
<li class=""><a href="?p=admin_free">Freie Engel</a></li> <li class=""><a href="?p=admin_questions">Fragen beantworten</a></li> <li class=""><a href="?p=shifttypes">Schichttypen</a></li>
<li class=""><a href="?p=admin_shifts">Schichten erstellen</a></li> <li class=""><a href="?p=admin_rooms">Räume</a></li>
<li class=""><a href="?p=admin_groups">Gruppenrechte</a></li>
<li class=""><a href="?p=admin_import">Frab Import</a></li> <li class=""><a href="?p=admin_log">Log</a></li>
`

**Comment by hollosch** [comment]
Kann mir da jemand helfen ?

**Comment by moerssl** [comment]
Ich hatte den gleichen Fehler. Bei mir lag es daran, dass die Bootstrap-Dateien gefeht haben. 

Um das zu beheben, musste ich den Inhalt aus `/vendor/bootstrap/dist` nach `/public/vendor/bootstrap/` kopieren.

Ein Symlink dafür ist in master bereits enthalten, der aber wahrscheinlich per FTP nicht übertragen wird.

**Comment by msquare** [comment]
Ist das Problem gelöst?

**Comment by hollosch** [comment]
Nein, leider nicht :-(

**Comment by msquare** [comment]
Welche Dateien liegen bei Dir unter `public/vendor/`?

**Comment by msquare** [comment]
Kann man Deine Installation öffentlich aufrufen?

**Comment by hollosch** [comment]
Hallo,
wir versuchen inzwischen eine neue Installation. Aber danke.
