### ISSUE TITLE
Blank page after install unless set to maintance mode.

### ISSUE THREAD

**Issue by mattronix** [engelsystem/engelsystem#263]
Hi Guys,

I am installing Engelsystem for use at a hacker event but after installing it i get a blank screen unless i set it to maintenance mode. 

OS: Debian Jessie 8 (LXC Container) 

Steps:
apt-get install git nginx php-fpm mysql-server  
cd /var/www/
git clone --recursive https://github.com/engelsystem/engelsystem.git
then set the root to "/var/www/engelsystem/public/" in nginx 
then enabled php-fpm  
reloaded nginx
mysql -u root -p 
create database engelsystem; 
GRANT ALL PRIVILEGES ON engelsystem.* TO 'username'@'localhost' IDENTIFIED BY 'NOTREALPASSWORD';
exit; 
chown www-data:www-data import -R 
cd engelsystem/config 
cp config.default.php  config.php
set the database credentials in config.php 

and now i get a blank screen :(, thanks for the help i thought id put my exact steps so we can check if i have missed anything.

**Comment by kamishettysreeja25** [comment]
Hi @mattronix 
You missed the step of migrating the` tables `to `engelsystem` database.
Please go through the link for more instructions.
Link: https://github.com/fossasia/engelsystem/blob/master/install_local.md 
Cheers!
Happy Coding :)

**Comment by mattronix** [comment]
Thank you i have ran all the database steps on the page again dropped the database and started again. 

now also did         source /var/www/engelsystem/db/update.sql;

but now the page shows 500 error :( 

something else I’ve missed?

**Comment by mattronix** [comment]
found php logs apparently mysql support was also not installed -_- 

Closing ticket
