### ISSUE TITLE
Installation engelsystem auf 1und1 

### ISSUE THREAD

**Issue by GI24** [engelsystem/engelsystem#265]
Hallo, ich hoffe, dass jemand hier deutsch spricht :-)
Ich brauche bitte Hilfe ...
Gibt es eine "Schritt-für-Schritt" Anleitung das Engelsystem auf meinem 1und1 Webserver zu installieren? Irgendwie mache ich ständig ein Fehler.

Der 1und1 Server hat folgende Merkmale:
Server-Typ: MySQL
Server Version: 5.5.49-0+deb7u1-log - (Debian)
Protokoll-Version: 10
Server Zeichensatz: UTF-8 Unicode (utf8)
Webserver: Apache/2.2.22
Datenbank-Client Version: libmysql - mysqlnd 5.0.10

Vielen Dank für eine schnelle Hilfe... oder....
gibt es ein besseres System? Meine Anforderung ist:
Ca. 250 (auf Teilzeit und selbstständige) "Mitarbeiter" für Veranstaltungen zu planen. 
Verfügbarkeiten der Mitarbeiter erfassen (oder selbst angeben lassen)
personalisierter Login
Veranstaltungen z.B. in einem Kalender anlegen (inkl. Beginn und Ende und Anzahl benötigter MA) und die MA können sich bewerben
.. usw...
... usw ... 
sowas, was eigentlich alle Agenturen benötigen :-)
Oder kann mir das jemand programmieren? Und evtl. mit mir gemeinsam eine Version davon vermarkten? Habe unendlich viele Kontakte, die sowas benötigen würden.

Nochmals... DANKE

**Comment by mariobehling** [comment]
Hallo @GI24,
wir arbeiten momentan an einer erweiterten Version des Engelsystems. Die Änderungen sind hier noch nicht aufgenommen. Unser Code-Repository is hier https://github.com/fossasia/engelsystem/tree/development
Würde mich freuen euch zu unterstützen. Wie kann ich dich erreichen?

**Comment by GI24** [comment]
Hallo mariobehling,
Danke für Deine Antwort. Wie kann ich Dir am besten meine Kontaktdaten senden, ohne dass die jeder hier sieht?
Gibt es eine "Schritt-für-Schritt" Anleitung das Engelsystem auf meinem 1und1 Webserver zu installieren? Irgendwie mache ich ständig ein Fehler.
Beste Grüße
Torsten

**Comment by GI24** [comment]
Hallo Mario,

 

ich bekomme die Installation nicht hin.

Musste einiges ändern (www.gastroinstitut.de) kann mich aber nicht einmal selber einloggen L

 

Gibt es vielleicht ein fertig aufgesetztes Engelsystem, welches ich kaufen kann und mir jemand auf meinem Server installiert?

Hab leider keine Zeit mich mit all dem auseinander zu setzen.

 

Danke für eine Antwort.

 

Beste Grüße

Torsten

 

 

GI_logo_2x2

GASTRONOMIE INSTITUT

 

unterschrift_mail

Torsten Anders

Waldschmidtstraße 47

D - 60316 Frankfurt

Mobil: +49.170.2124477

Mail:  <mailto:b.konietzny@gastronomie-institut.de> t.anders@gastronomie-institut.de

Web:  <http://www.gastronomie-institut.de/> www.gastronomie-institut.de

 

Sitz: Frankfurt, Amtsgericht Frankfurt, St.Nr. 12 802 11922, , USt-IdNr. DE 268336534, Erlaubnis zur Arbeitnehmerüberlassung nach den §§ 1 und 2 des Gesetzes zur Regelung der Arbeitnehmerüberlassung  (AÜG) vom 7. August 1972 - BGBI. 1  S. 1393, Geschäftsführer: Dipl. Päd. Barbara Anders 
VERTRAULICHKEIT: Die Informationen dieser E-Mail und eventueller Anhänge sind vertraulich und privilegiert. Sie sind ausschließlich für den genannten Empfänger bestimmt. Der Zugriff durch eine andere Person auf diese E-Mail ist nicht gestattet. Sollten Sie nicht der genannte Empfänger sein, benachrichtigen Sie den Absender bitte unverzüglich. Die Weitergabe des Inhalts an Dritte, die Nutzung für andere Zwecke oder das Speichern bzw. Kopieren der Informationen auf andere Speichermedien durch unbefugte Dritte ist verboten.

CONFIDENTIALITY: The information in this e-mail and in any attachments thereto is confidential and privileged. It is intended solely for the named recipient. Access by any other person on this e-mail is not authorised. If you are not the named recipient, please notify the sender immediately. Unauthorised persons are not allowed to disclose the contents to another person, use it for any purpose, or store or copy the information in any medium.

 

Von: Mario Behling [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Juli 2016 14:40
An: engelsystem/engelsystem
Cc: GI24; Mention
Betreff: Re: [engelsystem/engelsystem] Installation engelsystem auf 1und1 (#265)

 

Hallo @GI24 <https://github.com/GI24> ,
wir arbeiten momentan an einer erweiterten Version des Engelsystems. Die Änderungen sind hier noch nicht aufgenommen. Unser Code-Repository is hier https://github.com/fossasia/engelsystem/tree/development
Würde mich freuen euch zu unterstützen. Wie kann ich dich erreichen?

**Comment by mariobehling** [comment]
Wir erstellen gerade weitere Doku. Vielleicht hilft die Info hier bereits: https://github.com/fossasia/engelsystem/blob/development/docs/INSTALLATION_SERVER.md

Ein Blogpost zum Setup auf einem Local Server ist hier http://blog.fossasia.org/deploy-engelsystem-on-your-local-server/

Meine Kontaktdaten auf https://titanpad.com/eventsys16

**Comment by msquare** [comment]
Ist das Problem inzwischen behoben?

**Comment by msquare** [comment]
Keine Reaktion...falls doch, bitte wiedereröffnen.

**Comment by R4U5CH1337** [comment]
Hi
ich habe das gleiche Problem und scheitere immer.

Ich habe auch "nur" einen hosted webspace. Also mySQL DB, PHP und FTP.
Also leider kein Composter, SSH und andere Möglichkeiten etwas per Kommandozeile einzugeben.
Ist es damit überhaupt möglich das Engelsystem zum Laufen zu bekommen?
Würde mich sehr freuen!
Beste Grüße
