### ISSUE TITLE
Introduce database migration scripts

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#267]
For now there is an install.sql and an update.sql. If you want to update your existing engelsystem it could happen, that the update.sql is cleared and all the changes are included into the install.sql.
Then you don't have a chance to update the systems db without investigating the db changes by yourself.

We want migration system like this:
1. Each db change has to be written into a migration sql file. The migration filenames should include a version or date because they are applied sorted by filename.
2. A db table containing the already applied migration file names.
3. An install-script for checking if there are open migrations and to migrate these.

**Comment by MyIgel** [comment]
Points 1) & 2) were implemented in 235266ec53f620d94a080ed7ae8e77eaef6dbb3c

**Comment by MyIgel** [comment]
Point 3) has been implemented by 2bebbeb1919e1d370ac5c0668e0db5ea63e73292
