### ISSUE TITLE
Check which http://www.php-fig.org/ psrs to use

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#269]

**Comment by MyIgel** [comment]
What | PSR | Comment
------------ | ------------- | -------------
Autoloading | [PSR-4](http://www.php-fig.org/psr/psr-4/) (includes [PSR-0](http://www.php-fig.org/psr/psr-0/)) | Root -> /src/, namespace Engelsystem
Style | [PSR-2](http://www.php-fig.org/psr/psr-2/) (includes [PSR-1](http://www.php-fig.org/psr/psr-1/)) | 

[Composer](https://getcomposer.org) is the autoloader (and Dependency Manager) you want to use

**Comment by msquare** [comment]
We use PSR-2 and PSR-4 as written by @MyIgel.
