### ISSUE TITLE
HTTP ERROR 500 by click on Register

### ISSUE THREAD

**Issue by userdimi** [engelsystem/engelsystem#270]
Hey guys,

if I cklick on Register or if I want to create a new user or if I want to change rights to user, I allways get the Error: HTTP ERROR 500 on a blank page.

**Comment by msquare** [comment]
Please provide more information about your system environment, which steps you took to install the engelsystem and more details about the error (See webserver error log).

**Comment by userdimi** [comment]
Hey, I have installed the application on Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-96-generic x86_64), Apache2 Server version: Apache/2.4.7 (Ubuntu) and PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37). I used this tutorial to install the Application: https://github.com/fossasia/engelsystem/blob/development/docs/INSTALLATION_SERVER.md. 

The Serverlog log me this error: 

[Thu Oct 20 11:02:27.283055 2016] [:error] [pid 1202] [client 84.151.234.247:35953] PHP Fatal error:  Call to undefined function select_angeltype() in 
/data/www/vhosts/geislingen.info/engelsystem/includes/controller/guest_login_controller.php on line 47, referer: http://geislingen.info/?p=login

**Comment by msquare** [comment]
When did you clone the repository? Did you try to install the latest version?

**Comment by userdimi** [comment]
I clone it on 02.10.16. Is this the latest Version?

**Comment by msquare** [comment]
Since fossasia did a lot of rewrites and changes, I don't know what the problem is. If you clone the latest original version from this repo, it should be fine.
