### ISSUE TITLE
admin_active (Active Angles) -> Unable to load event config.

### ISSUE THREAD

**Issue by anykraus** [engelsystem/engelsystem#271]
The Active Angles page (admin_active.php) currently does not show any content. Only "Unable to load event config."
Apache's error.log is pretty full, main culprit seems to be:
`PHP Notice:  Undefined variable: shift_sum_formula in /srv/http/engelsystem/includes/pages/admin_active.php on line 108, referer: http://localhost/engelsystem/public/?p=admin_user&action=save_groups&id=3&set_locale=en_US.UTF-8`
Subsequently the SQL-Query fails as ${shift_sum_formula} is empty:

SELECT \`User\`.*, COUNT(\`ShiftEntry\`.\`id\`) as \`shift_count\`,  as \`shift_length\` \n      FROM \`User\` LEFT JOIN \`ShiftEntry\` ON \`User\`.\`UID\` = \`ShiftEntry\`.\`UID\` \n      LEFT JOIN \`Shifts\` ON \`ShiftEntry\`.\`SID\` = \`Shifts\`.\`SID\` \n      WHERE \`User\`.\`Gekommen\` = 1\n      AND (\`Shifts\`.\`end\` < 1478047417 OR \`Shifts\`.\`end\` IS NULL`

-> nothing before **as \`shift_length\`**

**Comment by msquare** [comment]
Works for me. Does the problem still exist?

**Comment by anykraus** [comment]
Tested with commit 1a3b4e2a334c57cc403be1d8e21fd8e162d9df5c
Works for me.
