### ISSUE TITLE
Arrival date in registration vs. arrival date in settings

### ISSUE THREAD

**Issue by der-michik** [engelsystem/engelsystem#286]
The registration allows the user to select any day starting from today as date of arrival. The settings only allow dates between start of buildup and end of teardown. That should be the same in the registration.

In addition, after selecting 2016-12-16 during the registration (which is before the buildup start currently configured), I cannot change any of my settings anymore since that is an invalid arrival date and the settings page marks the field with the "entry required" icon and even after selecting a valid arrival date, "Please enter your planned date of arrival. It should be after the buildup start date and before teardown end date." will appear.

**Comment by der-michik** [comment]
The datepicker in the settings allows the 17th as arrival date and the 17th is noted on the start page. However, the 17th is not valid. The 18th works. Maybe this is a ">" vs. ">=" issue.

In addition: It should be the 19th as on 17th and 18th we can't do much stuff anyway (ask dodger if in doubt).

**Comment by msquare** [comment]
Fixed.
