### ISSUE TITLE
cannot handle IDN email addresses

### ISSUE THREAD

**Issue by noelk** [engelsystem/engelsystem#287]
Hello,

I tried to use an email with an Internationalized domain name (IDN) but the engelsystem refused to accept this address. Maybe adding IDN would be accepted as a feature request.

https://en.wikipedia.org/wiki/Internationalized_domain_name
https://wiki.debian.org/IDN

Thank you.

**Comment by kakohari** [comment]
Is there any (non-web) mailclient which can handle those adresses? About one or two years ago I couldn't find one.

**Comment by noelk** [comment]
Hello Kai,

Am Sonntag, den 04.12.2016, 09:35 -0800 schrieb Kai König:
> Is there any (non-web) mailclient which can handle those adresses?
> About one or two years ago I couldn't find one.

Yes.We tested some:

https://wiki.debian.org/IDN

OSS:
evolution
thunderbird
kmail
mutt

other:
Apple iOS+Mac: Mail
Windows: Outlook 2010

The wiki page has two test email addresses which you can try with your
client.

thx.

Regards

	Noël

**Comment by msquare** [comment]
Relates to #177. Please take also a look to that ticket if you understand German.
