### ISSUE TITLE
Rename "restricted angeltype"

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#294]
The restriction basically means: You need an introduction to the job. After that, you are confirmed for the angeltype.

So we want to rename the feature to "requires introduction" and change the icon from lock to library or education.

**Comment by ravench** [comment]
Some Angeltypes also require special qualification.

**Comment by anykraus** [comment]
Don't over-engineer. Restricted angeltype covers both use cases. KISS
Maybe change the wording instead "requires introduction" to something which suites your specific event better: "May require a combination of proven skills, certificates, participation at introductory meeting. See details in the specific angeltype description."

Be aware that restricted angeltype plays well together with the new "disallow self sign-up" https://github.com/engelsystem/engelsystem/issues/253 which truly locks an angeltype in a shift from being joined by a random person.

**Comment by jwacalex** [comment]
I'm voting for "requires introduction" with an explanation like
> This angeltype requires the attendance at an introduction meeting where everything will be told. You might find additional information in the description
