### ISSUE TITLE
Integrating Single Sign-On (e.g. SAML or OpenID Connect)

### ISSUE THREAD

**Issue by dat-leth** [engelsystem/engelsystem#325]
We are considering using the 'Engelsystem' as an internal tool to coordinate shifts and helpers for our events. 

The biggest missing feature is, that we'd really like to have a single sign-on solution. However it might seem, that a bigger rewrite of the current login structure is required. I'd appreciate any thoughts/help.

**Comment by MyIgel** [comment]
At the moment i'm doing a bigger rewrite/refactoring in the feature-igel-rewrite branch, so it could be a good idea to use that code as a base for any changes ;)

**Comment by msquare** [comment]
Done in #772
