### ISSUE TITLE
Layout issue hiding "Sign up"-buttons and helper list

### ISSUE THREAD

**Issue by lukas2511** [engelsystem/engelsystem#345]
With shorter shifts there seems to be a layout issue which hides the sign up buttons and even the list of helpers.

Here a screenshot of the MRMCD17 and FrOSCon17 installations, both have the same issue, I manually expanded one of the boxes on the left to show what is hidden.

![layout](https://user-images.githubusercontent.com/85965/30032191-ae806fd4-9194-11e7-8c7d-2dd820f4c8fe.png)

Especially for shifts with multiple helper types this makes it hard to see where help is needed.

**Comment by msquare** [comment]
How would you solve this?
Expand the cards on mouseover?
Stretching the timescale to fit the contents?

**Comment by lukas2511** [comment]
Maybe add a tiny indicator in the corner of each card to show that $n angels are still needed, and extend the card on mouseover.

This way you can easily have an overview on where help is actually needed and still have long descriptions in the card without breaking the grid.

**Comment by MyIgel** [comment]
Partially related issue: #546 (Expand shift panel)
