### ISSUE TITLE
"Unable to load event config."

### ISSUE THREAD

**Issue by larsbru** [engelsystem/engelsystem#346]
Hello, 
i tried to install engelsystem on Ubunut 16 and on my webspace at "hosteurope". In both cases i get the message "Unable to load event config." when i enter http...engelsystem/public

What is wrong? Does someone know/already had the same problem?

Thx alot
Lars

**Comment by larsbru** [comment]
Ok, i tried out some things and finally found out that i didn't set the config.php. ... 
But now i get the next info "Unable to load user angeltypes."... Where does this come from?  

Thanks for help in advance!

**Comment by msquare** [comment]
Did you execute the update.sql script?

**Comment by 607nm** [comment]
I have the same Problem.
I executed the sql scripts.
When I try to log in with the default credentials i get "unable to load user angeltypes"
When i try to create a new user I get:

```
Warning: sql_id(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 173

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 184

Warning: mysqli::query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 158

Warning: sql_query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 163

Warning: sql_query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 163

Warning: mysqli::close(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 9

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 184

Warning: mysqli::query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 158

Warning: sql_query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 163

Warning: sql_query(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 163

Warning: mysqli::close(): Couldn't fetch mysqli in /var/www/engelsystem/includes/mysqli_provider.php on line 9
Unable to update password.

```

**Comment by MyIgel** [comment]
Some days ago the rewrite branch got merged -> if your angelsystem is atm. not running in "production" I would recommend you to use the newest version :)
It contains a rewrite of the sql query functionality which should fix some potential bugs.

**Comment by msquare** [comment]
This should work now using the stable build v2.0.0.
