### ISSUE TITLE
Drop down menus do not scroll

### ISSUE THREAD

**Issue by cyriax0** [engelsystem/engelsystem#360]
The drop down menus at the top of the page (e.g. News Meetings...) do not scroll.

This is an issue for small screens because the items at the bottom are unreachable. (e.g. firefox on my puny 1366x768px notebook screen)

This is not an issue on mobile devices, scrolling the menu works fine on firefox mobile 55 on android.

To reproduce try reaching room Wardrobe from a small sized browser window.

**Comment by Wene** [comment]
I've the same problem even with "full HD" resolution.

The only workaround I found is resizing the browser window to force mobile mode. Then it works even on a desktop browser.
