### ISSUE TITLE
No self signup option work as expected (no effect)

### ISSUE THREAD

**Issue by leaneb** [engelsystem/engelsystem#363]
Have created a new Angeltype, called Tschunktester, tick the Checkboxes no self sign up and restricted in the Angeltyp settings.
A Angel with the Normal Angel Usergroup can send a Join Request, is that the expected manner i don't remeber exactly from 33C3

**Comment by msquare** [comment]
no self signup means, that the user cannot join shifts by himself. he has to be put into shifts.
restricted means double-opt-in by user and angeltype supporter to join the angeltype.

please check if it works as described, thank you!

**Comment by leaneb** [comment]
works as you described
