### ISSUE TITLE
Feature: Time Interval Buttons (on Shifts page)

### ISSUE THREAD

**Issue by cyriax0** [engelsystem/engelsystem#366]
### What?
Some buttons to set a time interval (clientside).

### Where To Implement it?
On the Shifts page below the time interval selection.

### Specifics
Two Groups of buttons:
`[Yesterday]` `[Today]` `[Tomorrow]`
`[last 8h]` `[last 4h]` `[next 4h]` `[next 8h]`
The first group sets the time intervals spanning a full day from 00:00-24:00.
The second group sets the time inteval respective to NOW.

### Rationale
Right now when using Engelsystem one has to manually enter time intevals, doing mental arithmetics and switching from activating elements via pointing to keyboard input.
This is inconvenient, especially for shift coordination, who has to query the Shifts table quite often, for mouse users that have to switch input devices, and for mobile users where pressing buttons is easier than typing arbitrary numbers.
Past time intervals are useful for entering angels into shifts retrospecively and should mostly be used by shift coordination, while future time intervals are good for planning and useful for everyone.
[last 4h] can also be used to find most of the running shifts conveniently.

### Invocation
I invoke @MyIgel 
All mate during development of this feature is on me.

**Comment by MyIgel** [comment]
Mate consumed: 0
Water consumed: 2
