### ISSUE TITLE
duplicate apparent username

### ISSUE THREAD

**Issue by cyriax0** [engelsystem/engelsystem#369]
### What
In the 34c3 live system when looking at the angeltype "Angel" there are two users named "goto". The first one is sorted to the head of the list, the second user is sorted into the list as expected. This might cause confusion for Shift Coordination later.
### Specualtion
Maybe the first username starts with some nonprinting chars. This would explain it being sorted to the beginning of the list. If so we might want to force usernames to contain only a valid subset of characters on registration. Someone with access to the system should query the user database to check if it's really two users with the same printed usernames or some wierd dupication bug.

**Comment by msquare** [comment]
At least we should introduce a trim on the username. The first goto seems to have a space in front.
