### ISSUE TITLE
Removing supporter rights does not work

### ISSUE THREAD

**Issue by der-michik** [engelsystem/engelsystem#376]
When I want to remove supporter rights for an angel type from a user, this does not work. The page asking for confirmation is displayed but after clicking on "yes", I get the untrained monkeys error message.

The error seems to be independent of the specific user and angel type.

**Comment by der-michik** [comment]
BTW: I tried to debug this one with a bit more detail but it works fine in my local instance but fails on engelsystem.de/34c3...

**Comment by msquare** [comment]
This is due to the new mysql version which is a little bit stricter regarding default values.
