### ISSUE TITLE
Editing news with HTML gives additional breaks

### ISSUE THREAD

**Issue by NilsKet** [engelsystem/engelsystem#385]
When editing news with HTML content additional `<BR>` Tags are inserted. Attached is a File with content for a HTML Table that renders with lots of blank space before the table when posted as news in the Engelsystem. [table.txt](https://github.com/engelsystem/engelsystem/files/1576715/table.txt)

I guess the problem is, that the full news entry from the DB is transformed by `nl2br` in display_news function in engelsystem/includes/pages/user_news.php 

For content that already is HTML this results in additional tags, in this case a `<br>` after each `</tr>` (cause that happens to be the end of the line in the source).

**Comment by msquare** [comment]
Solved in a0f70d9819532bca9def088e1089940b2696abf3 by introducing a <br> only if two \n occur.
