### ISSUE TITLE
"Event ends" time should be to the end of the day, not the start

### ISSUE THREAD

**Issue by luxferresum** [engelsystem/engelsystem#408]
Basically the system says the Event ends on 00:00 on the last day. That seems wrong.

**Comment by msquare** [comment]
The date from the event config entity does not contain time. This is filled into the config by config service provider and called from the twig view.

First idea: Let the login controller calculate the timestamps for the countdowns.
Second idea: Add helper functions to the event config model which return the needed timestamps.

**Comment by MyIgel** [comment]
This got implemented in 30e1d41c0a9194973faa243bc66411705744ceb5 as the start/end times can now be configured containing hours and minutes.
