### ISSUE TITLE
Gitlab CI @chaos.expert

### ISSUE THREAD

**Issue by wonko21** [engelsystem/engelsystem#409]
Moin ich hab mal ein Repo auf chaos.expert angelegt: https://chaos.expert/engelsystem 
Das "mirror" repo dort synct github alle 15min. Die CI läuft dann auch. Let the Unit tests come ;-)
Wenn Ihr nen webhook einrichten wollt könnte ich mir sparen alle 15min zu pollen.

**Comment by msquare** [comment]
Hi, cool. Kann man irgendwo Testergebnisse oder Coverage oder sowas sehen? Braucht man dafür einen Account?

Lass mir die Daten für den Webhook gerne zukommen.

**Comment by wonko21** [comment]
sorry hatte vergessen das repo public zu drehen m(

https://chaos.expert/engelsystem/engelsystem/pipelines

Account kannst du dir gerne klicken. musst du aber nicht. der igel hat auch master-rechte auf der gruppe/repo.

**Comment by wonko21** [comment]
da der webhook jedesmal die pipeline laufen lässt würde ich ungerne hier den url + sectrect posten. irc?

**Comment by wonko21** [comment]
ping @msquare

**Comment by msquare** [comment]
Hab mir jetzt mal einen Account geklickt. Schickst du mir den Webhook an github@notrademark.de?

**Comment by msquare** [comment]
@wonko21 der webhook bekommt ein 404 vom gitlab. Ideen?

**Comment by wonko21** [comment]
Hi der Hook gibt 404 im browser (HTTP GET) als POST geht dieser wunderbar ;-)

curl -X POST https://chaos.expert/api/v4/projects/384/ref/master/trigger/pipeline?token=TOKENHIER

**Comment by msquare** [comment]
Tut es aber leider nicht.

Request laut Github:
```
Request URL: https://chaos.expert/api/v4/projects/384/ref/master/trigger/pipeline?token=[...]
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/4f5b68a
X-GitHub-Delivery: e3818c4e-988d-11e8-994d-5330b3ebf6e5
X-GitHub-Event: push
```
Response:
Headers
```
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 27
Content-Type: application/json
Date: Mon, 06 Aug 2018 09:56:25 GMT
Server: nginx
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 7623fc22-5abc-4f40-bacd-ea5675f17bae
X-Runtime: 0.036586
```

Body
`{"message":"404 Not Found"}`

**Comment by msquare** [comment]
Mit einem eigenen Token gehts. Thx.
