### ISSUE TITLE
After the installation: PHP-Error Handler.php on line 76

### ISSUE THREAD

**Issue by Peeri90** [engelsystem/engelsystem#411]
Hello,
i use the instructions from https://github.com/engelsystem/engelsystem/blob/master/README.md The installation finished without errors.

i created the Databases with the .sql files and die config.php is modified.

But when i go to /engelsystem/public :

`Parse error: syntax error, unexpected 'die' (T_EXIT), expecting identifier (T_STRING) in /var/www/web1270/html/engelsystem/src/Exceptions/Handler.php on line 76`

I have no idea where is the problem. 

Thanks for your time!

Peeri

**Comment by msquare** [comment]
Wich PHP Version are you running?

**Comment by Peeri90** [comment]
Hello,
thank you for your answer.
The error come with PHP-Version 5.6.32.

Today i switch to PHP-Version 7.0.26 with a entry in the .htaccess :  AddHandler x-httpd-php70 .php
The new error Message: An unexpected error occurred, a team of untrained monkeys has been dispatched to deal with it.

ok, thats funny. but not helpfuly xD

**Comment by jens1o** [comment]
Perhaps `die` is a reserved keyword nowadays, so it can't be used as a function name anymore?

**Comment by msquare** [comment]
You should have an server error log if this message displays. Could you please check and paste here?

**Comment by Peeri90** [comment]
Hello :)
i found this in the logs.
with PHP 5.6:
`[Tue Jan 02 13:11:52.265430 2018] [fcgid:warn] [pid 982416:tid 140267591890688] [client 178.24.247.121:23110] mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected 'die' (T_EXIT), expecting identifier (T_STRING) in /var/www/web1270/html/engelsystem/src/Exceptions/Handler.php on line 76
`

With PHP 7.0 ore 7.1:
`[Tue Jan 02 13:18:10.177058 2018] [fcgid:warn] [pid 994580:tid 140267784922880] [client 178.24.247.121:23092] mod_fcgid: stderr: Exception: Code: 0, Message: Failed to start the session because headers have already been sent by "/var/www/web1270/html/engelsystem/config/config.default.php" at line 1., File: vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:141, Trace: [{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/vendor\\/symfony\\/http-foundation\\/Session\\/Session.php","line":56,"function":"start","class":"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Storage\\\\NativeSessionStorage","type":"->","args":[]},{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/src\\/Http\\/SessionServiceProvider.php","line":26,"function":"start","class":"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Session","type":"->","args":[]},{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/src\\/Application.php","line":62,"function":"register","class":"Engelsystem\\\\Http\\\\SessionServiceProvider","type":"->","args":[]},{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/src\\/Application.php","line":84,"function":"register","class":"Engelsystem\\\\Application","type":"->","args":[{}]},{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/includes\\/engelsystem.php","line":26,"function":"bootstrap","class":"Engelsystem\\\\Application","type":"->","args":[{}]},{"file":"\\/var\\/www\\/web1270\\/html\\/engelsystem\\/public\\/index.php","line":5,"args":["\\/var\\/www\\/web1270\\/html\\/engelsystem\\/includes\\/engelsystem.php"],"function":"require_once"}]
`

**Comment by Peeri90** [comment]
okay, i found the problem with php 7.0/7.1
i edited the config.php with the windows Editor. When i edit the File with notepad++ its works.

THank you for your time!
