### ISSUE TITLE
Room filter should have all rooms selected by default

### ISSUE THREAD

**Issue by oliver** [engelsystem/engelsystem#414]
On the Shifts page, the Rooms filter has by default only the first room selected. This is not useful for most users (at 34c3 this was the "ACR" room). Although the filter was preserved for the rest of the session, it was reset to the first room after being logged out. Since I was frequently logged out (maybe due to unstable Wifi?), often when I visited the Shifts page I first had to select All Rooms and click Filter, which was annoying.

**I suggest to select all rooms by default.** This would be an improvement to many and should not have any disadvantage over the current system (I guess virtually nobody wants to have exactly and only the ACR room selected).

Alternatively, a fancier solution would be to store the room filter in user profile so that it is preserved over logout.

**Comment by msquare** [comment]
Is done.
