### ISSUE TITLE
[FR] /metrics endpoint

### ISSUE THREAD

**Issue by RichiH** [engelsystem/engelsystem#418]
I am part of c3noc and have introduced Prometheus for 33c3; it's what has powered the dashboard for 33c3 & 34c3.

For engelsystem, I see two potential uses for /metrics:

* Useful metrics like internal system state, if databases can be reached, etc
* Fun metrics, especially the amount of person-hours which were worked by the various angels in all the different roles

The latter, I see as something that should go onto the dashboard for 35c3 to raise awareness of just how much time is spent on making congress happen.

For any questions, I am RichiH on all the usual IRC networks.

**Comment by msquare** [comment]
The engelsystem is very small and not monitored. You can check for engelsystem.de or engelsystem.de/35c3 via HTTP. If the status is 500, there is a problem. ;-)
I have to think about this, what would be your favourite solution?

Some "fun" metrics are already available under https://engelsystem.de/34c3/stats?api_key=<key>
For testing you can use:
https://staging.engelsystem.de/test/stats?api_key=ufqPVQXTBUyyes8z
A splitting of the work hours by shifttype and/or angeltype is a good idea.

Please ask before 35c3 for a new URL+API key.

**Comment by MyIgel** [comment]
What he means is a [Prometheus Exporter](https://prometheus.io/docs/instrumenting/writing_exporters/)

**Comment by msquare** [comment]
Oh.

**Comment by RichiH** [comment]
Yah, sorry, I should have worded that better. Ideally, there would be a `engelsystem.de/metrics` with, in your example:

````
user_count 2081
arrived_user_count 1795
done_work_hours 13263
users_in_action 0
````

or , in something that uses labels like Prometheus does:

````
angels{state="incoming"} 286 (as we would calculate the total users from the different states ourselves)
angels{state="arrived",working="no"} 1795
angels{state="arrived",working="yes"} 0
work_seconds{state="done"} 47746800 (which is 13263 * 3600. Again, I would calculate totals across work_hours myself)
work_seconds{state="planned"} 0
````

Doing it in `_seconds` makes it easier for you to expose quarter hours, etc; and easier for me to show personseconds worked per second as a changing graph.

**Comment by msquare** [comment]
@RichiH How can I send you the api key for the 35c3 engelsystem to access the metrics?

**Comment by RichiH** [comment]
CC @fjaeckel

Great, thanks!

Can you send a sample of your metrics so we can look at them re best
practices in naming and such?

ACLs to limit to certain source IPs would be easiest for us.

When will you start emitting data? I will be traveling until Saturday
afternoon, but I suspect Frederic will have time before that. Dashboards
can be done later.

Sent by mobile; please excuse my brevity.

**Comment by fjaeckel** [comment]
@msquare I suppose IRC is best? Not sure of a more “secure” way - but then we’re talking about metrics that we’re trying to expose to everyone anyway. :) i’m `jchome` on hackint/freenode/ircnet

**Comment by RichiH** [comment]
I am richih on all the things, but will be able to jump on IRC tomorrow at
the earliest. Feel free to do things without me and thanks all around.

Sent by mobile; please excuse my brevity.

**Comment by RichiH** [comment]
Thanks.

If you are using a library, activating stats like http return codes,
request latencies, etc is always good.


engelsystem_questions{answered="1"} 5

engelsystem_questions{answered="0"} 0

This should be state="answered" etc.


Else, it looks usable and useful.



Sent by mobile; please excuse my brevity.

**Comment by msquare** [comment]
The opposite of freeloaded may be working or present.

**Comment by fjaeckel** [comment]
@msquare can you please remove `# 35c3-Engelsystem stats` from the output? It breaks the format.

**Comment by MyIgel** [comment]
According to the [docs](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information):

> Lines with a # as the first non-whitespace character are comments. They are ignored unless the first token after # is either HELP or TYPE.

So it shouldn't break anything?!?

**Comment by fjaeckel** [comment]
Yea, but the error I get `"INVALID" is not a valid start token` points to that issue - but I have not found other things in the JSON that should cause an error like that.

**Comment by MyIgel** [comment]
That seams to be a problem with your config?

For me it works without any problems with
```yaml
  - job_name: 'engelsystem-35c3'
    scheme: https
    metrics_path: /35c3/metrics
    static_configs:
      - targets: ['engelsystem.de:443']
```
(at least after msquare removed the password protection because why should we protect interesting stats?)

**Comment by fjaeckel** [comment]
Works now, thanks! I forgot the https.
