### ISSUE TITLE
Administrator hinzufügen

### ISSUE THREAD

**Issue by Peeri90** [engelsystem/engelsystem#419]
Moin,
ich habe leider kein Menü gefunden, in dem ich einem registrierten User zum Administrator machen kann.
Wo kann ich dies machen?

Vielen Dank und viele Grüße
Peer

**Comment by msquare** [comment]
In der Userliste auf den Stift (rechts, bearbeiten) klicken und dort unten kannst du dann "Gruppen" (Rollen) vergeben. Diese kann man nur bei anderen Usersn, nicht sich selbst vergeben. Bei einem Admin einfach alle Gruppen anhaken.

**Comment by Peeri90** [comment]
Vielen Dank :)
