### ISSUE TITLE
404 on every site

### ISSUE THREAD

**Issue by freifunk-bamberg** [engelsystem/engelsystem#425]
Hallo, ich habe das system nach der anleitung in Github installiert, aber ich bekomme ständig den error 404...

hat sich das was entscheidendes geändert?

Danke für eure hilfe..
Rene

**Comment by MyIgel** [comment]
Interpretiert dein Server die .htaccess Datei Bzhw. ist er so konfiguriert dass er die index.php benutzt wenn die aufgerufene Datei nicht existiert?
Der Docroot zeigt auf public/?

**Comment by freifunk-bamberg** [comment]
nach der installation wurde mir die anledeseite angezeigt.
dirt konnte ich mich auch als admin anmelden, jetzt sehe ich die NEWS seite, sobald ich aber irgend einen link aus dem menü öfnen will kommt der fehler 404

**Comment by MyIgel** [comment]
Hast du mal einen Link zur Seite? Gerne auch per mail/dm/whatever

**Comment by freifunk-bamberg** [comment]
http://helfen.kontakt-daskulturfestival.de/

habe es gerade noch einmal installiert, jetzt funktionieren die Seiten aber irgendwie ist da kein syle mehr drinn

**Comment by MyIgel** [comment]
Bei mir werden die Styles geladen ;)

Das Problem ist dass deine .htaccess nicht geparsed wird -> dadurch funktionieren die Links nicht.

Hast du zugriff auf die server config? Dort sollte [`AllowOverride All`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) (oder zumindestens FileInfo) für den Webroot gesetzt sein.

Außerdem muss `mod_rewrite` aktiviert worden sein (`a2enmod rewrite`)

**Comment by MyIgel** [comment]
Ein workaround (wenn du nicht sofort die config anpassen kannst) wäre eine Anpassung im code sodass du die alten URLs verwendest.

Dafür muss nur die `Routing/UrlGenerator.php` angepasst werden:
```php
public function to($path, $parameters = [])
{
    $path = '/' . ltrim($path, '/');
    $request = app('request');
    $uri = $request->getUriForPath($path);

    $page = trim($uri, '/');
    $page = str_replace('-', '_', $page);
    $parameters['p'] = $page;
    $uri = '/index.php';

    if (!empty($parameters) && is_array($parameters)) {
        $parameters = http_build_query($parameters);
        $uri .= '?' . $parameters;
    }

    return $uri;
}
```

Dieser Quickfix ist eher ein hack -> sollte also nicht dauerhaft verwendet werden ;)

**Comment by msquare** [comment]
@MyIgel das sollten wir ins Readme aufnehmen: htaccess und mod_rewrite müssen aktiviert sein.

**Comment by MyIgel** [comment]
Jup, und eventuell auch einen LegacyUrlGenerator implementieren der auch ohne rewrite auskommt (konfigurierbar)

**Comment by freifunk-bamberg** [comment]
Super danke jetzt läuft alles!

**Comment by freifunk-bamberg** [comment]
Weil wir es gerade auch von css hatten, gibt es eine möglichkeit das Logo auszutauschen?

**Comment by MyIgel** [comment]
Das 'Logo' ist ein Icon einer Iconfont, du könntest es in "templates/layout.html:26" entfernen.
Das selbe gilt für den Titel, der ist auch überall fest eingebaut.

**Comment by freifunk-bamberg** [comment]
ok danke,
schade das könnte man noch mal ändern, so das man das logo von der jeweiligen veranstaltung rein packen kann....

**Comment by MyIgel** [comment]
Ich habe dafür gerade mal ein Issue aufgemacht (#426: Feature: Logo and text should be configurable)
