### ISSUE TITLE
Bug: nick is changed unexpectedly

### ISSUE THREAD

**Issue by phtan** [engelsystem/engelsystem#429]
I signed up with the nick 'Tony was seen at Hackerspace'.
I expected to be able to log in with that nick, but was not able to.
I found out that my nick was recorded as 'Tony was seen at Hacker'.
I could then log in with that (shorter) nick.

**Comment by MyIgel** [comment]
Jup, that's a bug ;)

The Nickname is stored in the Database with a length of 23 characters (according to db/install.sql#L377), that should be validated

**Comment by phtan** [comment]
I wonder if there is removal of certain characters from the nick, too. For example, if I register with the nick 'Tony (Chen)', will I be registered as 'Tony Chen' without me being notified about the change?

**Comment by MyIgel** [comment]
Jup, there is (includes/model/User_model.php#L309)
-> all non alphanum and "-_. " characters will be removed

Maybe we should show the username in the "you have registered" message ;)

**Comment by phtan** [comment]
Glad to see this issue has an associated PR now
