### ISSUE TITLE
Passwort wiederherstellen funktioniert nicht

### ISSUE THREAD

**Issue by psteinmu** [engelsystem/engelsystem#433]
Bei einem Antrag auf ein neues Passwort für das Engelsystem erhält man eine E-Mail, welche als Link /user-password-recovery?token=ein_token hat.

**Comment by MyIgel** [comment]
Welche Version des Engelsystems hattest du zu dem Zeitpunkt verwendet?
In der aktuellen Version funktioniert das Passwort zurücksetzen (soweit ich das testen konnte).

**Comment by msquare** [comment]
Das funktioniert im master/unstable gerade und in der stable v2.0.0 auch.
