### ISSUE TITLE
Use of a Framework?

### ISSUE THREAD

**Issue by fionera** [engelsystem/engelsystem#437]
I thought why not use a Framework for the Engelsystem. When you are rewriting it for MVC support etc. you could also use a Framework like Symfony.

**Comment by MyIgel** [comment]
Thats a point that I thought about and had some bigger conversations about it with @msquare. The TLDR is that the engelsystem should not depend on a framework (as in "We use Symfony/Laravel/whatever).
After that I started some refactoring (thats not finished yet) that uses some symfony/laravel framework parts.

Personally I prefer the laravel structure, way of implementation and design patterns ;)

**Comment by fionera** [comment]
Nice. I started reimplementing the Engelsystem in Symfony and will try to be feature complete until "Hacken Open Air" https://github.com/fionera/engelsystem/tree/symfony

**Comment by jens1o** [comment]
What will be the new PHP requirement after the Rewrite?

**Comment by MyIgel** [comment]
Hm, I don't think that this would be a good idea to reimplement it totally -> its a bunch of work (i know what i'm talking about), just replacing parts of it would be a better (and more effective idea -> thats what I'm working on sometimes (and will continue in a month or so).

One important thing is to keep the external dependnecies as small as possible so throwing in a bunch of external recources that require more dependencies is not the way we (@msquare and I) wanted to implement it. Also this would allow us to decide more granually what external recources (and versions) we want to use.

**Comment by MyIgel** [comment]
The PHP Version should be >= 7.0 or so ;)

**Comment by fionera** [comment]
I currently write for PHP 7.1.

@MyIgel Thinks that are already implemented:
- News
- Meetings
- AngelTypes
- Rooms
- Users
- Groups
- Permissions

I currently work on Shifts :D The Dependencys are currently only Symfony Packets from Composer and Parsedown as Markdown Parser
