### ISSUE TITLE
Loading failed for the <script> with source “http://*/vendor/bootstrap/js/bootstrap.min.js”.

### ISSUE THREAD

**Issue by jens1o** [engelsystem/engelsystem#440]
The file is not delivered within the git repository, yet.

**Comment by MyIgel** [comment]
Did you run `composer install`? If so your server have to follow symlinks (the `public/vendor/bootstrap` directory is a symlink to `vendor/twbs/bootstrap/dist`

**Comment by jens1o** [comment]
There are no symlinks on windows ;)

**Comment by MyIgel** [comment]
There [are](https://docs.microsoft.com/de-de/windows/desktop/FileIO/creating-symbolic-links) -> you can use the `mklink` command to create them

& you are really using windoofus for dev? 0o

**Comment by jens1o** [comment]
> you can use the mklink command to create them

I know, but they are not created automatically as I expected to be.

> you are really using windoofus for dev? 0o

Till I get my new laptop, yes :D

**Comment by MyIgel** [comment]
This issue is outdated after the merge of #427 (Use npm to handle frontend dependencies)
