### ISSUE TITLE
Change of the Language is not working

### ISSUE THREAD

**Issue by TDansa** [engelsystem/engelsystem#449]
Hi,

when I select the german language by my self in the system, there is no effect.
Also when I change the language in the config file...

The po and mo files are in the "locale" directory - is there something what I must do with them?
\engelsystem\locale\de_DE.UTF-8\LC_MESSAGES

thanks :)

**Comment by Nos-** [comment]
Changing the language (in my case from english to german) doesn't work too.

**Comment by MyIgel** [comment]
Is `php-gettext` installed? (#479: Installation instruction missing i18n instructions)

**Comment by Nos-** [comment]
Now it works. (See my comment in #479 ).
