### ISSUE TITLE
tshirt_sizes seem mixed with the default config

### ISSUE THREAD

**Issue by thegcat** [engelsystem/engelsystem#465]
It seems the `tshirt_sizes` we define in our `config.php` get merged with the values from the `config.default.php`, for example we don't have girlie options, those appear in the list in the Web interface though. Conversely, things exclusive to our list (XXL and XS for example) do appear in the list too. It seems both lists get merged.

Is this expected behaviour or a bug?

**Comment by msquare** [comment]
Thanks for reporting, this is a bug. Please remove the shirt sizes from `config.default.php` to make this work for you.

**Comment by thegcat** [comment]
Thanks for the hotfix proposal, that indeed fixes the issue for the moment.
