### ISSUE TITLE
Index 'from_frab'  (rooms) und Tabelle UserWorkLog nach Installation nicht vorhanden

### ISSUE THREAD

**Issue by merci-bcp** [engelsystem/engelsystem#471]
Hallo, ich habe das Engelsystem nach der Anleitung hier installiert, aber habe bisher 3 Fehlermeldungen bekommen:

Eine war sehr schnell behoben: 
- In der Tabelle AngelTypes fehlte die Spalte "show_on_dashboard".

Bleiben noch die anderen 2:
- Der Index 'from_frab' existiert nicht:
Beim Klicken auf "Verwalte Räume" als admin wird der Index 'from_frab' nicht erkannt. 
Ich bin nicht sicher, wozu dieser Index überhaupt gebraucht wird, habe ihn in admin_rooms.php jetzt auskommentiert, wodurch ich erst mal die Seite angezeigt bekomme. Allerdings fehlt nun (erwartbarerweise) ein Parameter für die Funktion Room_create(). 
Könnt ihr mir vielleicht sagen, wo/wie ich stattdessen den Index sinnvoll einfügen kann?

- Die komplette Tabelle UserWorkLog existiert nicht:
`Illuminate\Database\QueryException: (42S02)
array(3) {
  ["string"]=>
  string(349) "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.UserWorkLog' doesn't exist (SQL: 
        SELECT SUM(`work_hours`) AS `tshirt_score`
        FROM `User` 
        LEFT JOIN `UserWorkLog` ON `User`.`UID` = `UserWorkLog`.`user_id`
        WHERE `User`.`UID` = 4
        AND `UserWorkLog`.`work_timestamp` < 1537469298
    )"`...
Da habe ich natürlich gar keine Ahnung, was darin noch zu stehen hat. Wäre euch sehr dankbar, wenn ihr mir da helfen könntet.

Danke für das Bereitstellen des Systems - und eure Ideen. Sagt Bescheid, wenn ich den Bugreport in 3 teilen sollte.

**Comment by MyIgel** [comment]
Moin, hast du die Datenbank über das `bin/migrate` Script importiert?
Es hört sich so an als hättest du nur die `db/install.sql` importiert, hier fehlt noch die `db/update.sql` und weitere Migrationen die nur über das `bin/migrate` Script importiert werden

**Comment by merci-bcp** [comment]
eigentlich hatte ich das schon, ja

**Comment by msquare** [comment]
Schau sonst mal unter Releases und nimm da die stabile Version vom Congress.

**Comment by merci-bcp** [comment]
Danke für eure Rückmeldungen. Wir haben beim Durchschauen allerdings inzwischen festgestellt, dass das System an sich nicht ganz so gut für unsere Anwendung passt, bzw. wir noch zu viel anpassen müssten, um es sinnvoll für unsere Anwendung nutzen zu können. 
Insbesondere ist die Schichtenplanung bei uns insgesamt etwas weniger wichtig, die Kommunikation in Teams bestimmter Engeltypen (nicht nur mit einzelnen Eneln) aber umso mehr. Deswegen werden wir nun doch wieder auf das gute, alte Forum zurückgreifen. Das aber nur am Rande als Feature-Idee, weil ich mir vorstellen kann, dass das auch für andere Initiativen hilfreich sein könnte.
