### ISSUE TITLE
Installation instruction missing i18n instructions

### ISSUE THREAD

**Issue by thegcat** [engelsystem/engelsystem#479]
To get another language than English to work, it was necessary to install additional packages (on Ubuntu one of `gettext` or `php-php-gettext` should do the trick) and to make sure that the locales that should be available in the engelsystem are also installed on the system (check `locale -a`, missing ones can mostly be added with `locale-gen`).

**Comment by Nos-** [comment]
Many thanks for that!

Additionally this can be helpful too:

> Please ensure, that the locale "de_DE.UTF-8" is installed on your system.

(see Issue #238 German language is not working)

and here the command for that: `localectl set-locale "LANG=de_DE.UTF-8"`
