### ISSUE TITLE
Tutorial 1und1 (oder andere) Webserver

### ISSUE THREAD

**Issue by TDansa** [engelsystem/engelsystem#492]
Hi,

ich würde das System gerne auf einem 1und1 Webserver zum laufen bringen.
Wie mach ich das am besten? Gibt es dafür bereits schon Ansätze/Anleitungen? Ich hab leider bei meiner Recherche nichts gefunden (auch nicht auf englisch)

Composer Installation, oder auch Docker Installation funktioniert ja dort nicht, ich habe einfach mal probiert das ganze lokal auf meinem Apache Webserver zu installieren (was natürlich geht) und dann das Verzeichnis einfach zu kopieren + Datenbank natürlich... da bekomme ich aber nur den Fehler: 
HTTP 500: Interner Serverfehler oder auch "An unexpected error occurred, a team of untrained monkeys has been dispatched to deal with it."

Kann mir hier jemand einen Tipp geben? 

Ich wäre euch sehr sehr sehr dankbar :)

**Comment by MyIgel** [comment]
1&1 ist nicht gerade der beste Platz für ne Seite aber ok, jedem seine eigenen Probleme denn das Engelsystem braucht eigentlich ssh access auf den Webspace den 1&1 wahrscheinlich nicht hat.
Für dich ist es wahrscheinlich am schnellsten wenn du das [2.0.0](https://github.com/engelsystem/engelsystem/releases) release verwendest (den Inhalt des .zip archives hochladen und die `db/install.sql` und `db/update.sql` in die Datenbank importieren).

**Comment by TDansa** [comment]
Ja ich weiss, 1 und 1 ist leider sehr bescheiden, aber die Mühe zu wechseln wollen wir uns gerade nicht machen :)
SSH Zugang gibt es zwar, kostet aber unmengen an Geld und ist mit unserem alten Paket tatsächlich nicht möglich - D.h. wir würden gezwungen sein unsere Domäne zu ändern da 1und1 keine .org mehr anbietet ... nervig ...

Wenn ich genau das tu, was du sagst - dann bekomme ich diesen oben genannten Fehler, natürlich hab ich vorher die config datei bearbeitet und mit dem entsprechenden DB Zugang gefüllt, ich hab es aber auch ohne probiert, funktioniert auch nicht :(

Danke für die Hilfe! :)

**Comment by MyIgel** [comment]
Ich habe es gerade noch mal getestet, bei mir funktioniert das `2.0.0` Release problemlos.
Hast du beide SQL Dateien importiert? Schau auch mal in deinem `error.log` nach, da sollte der Fehler drinne stehen ;)

**Comment by TDansa** [comment]
Jap, hab das Paket entpackt und als erstes die SQL Datenbank angelegt, diese hab ich dann mit dem install.sql und update.sql Paket befüllt - danach hab ich den gesamten entpackten Ordner auf meinen Webspace geschoben. 
Dann hab ich die config.php bearbeitet und die Datenbankdaten eingetragen.

Was ich einfach nicht finde is dieses error.log ... Wo soll sich das file denn befinden?

**Comment by MyIgel** [comment]
Wo du es aktivieren kannst müsstest du in der 1&1 Hilfe finden, das kann ich dir nicht sagen.
Alternativ kannst du auch kurz in der `src/Exceptions/Handlers/Legacy.php` ind er Methode `render` ein `var_dump($e);` rein packen (& es nach dem Seitenaufruf wieder raus nehmen) ;)

**Comment by TDansa** [comment]
Also das log gibt aus das die Verbindung zur Datenbank nicht klappt - Erstelle ich wie in den Hinweisen angegeben eine config.php und lege ich das ganze im Ordner config ab, passiert gar nix, außer der bekannte Fehler :(

Passe ich die Daten in der config.default.php an, funktioniert es und die Seite wird aufgerufen aber nach dem Login kann ich überall hinklicken und kriege immer den Fehler:

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> 
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Ich weiss nicht ob das damit zusammenhängt: wenn ich die update.sql importiere bekomme ich diesen Fehler:

> Fehler
> 
> SQL-Befehl:
> 
> ALTER TABLE `AngelTypes` DROP FOREIGN KEY angeltypes_ibfk_1
> 
> MySQL meldet: Dokumentation
> #1025 - Fehler beim Umbenennen von './db749902536/AngelTypes' in './db749902536/#sql2-59d-105bed4' (Fehler: 152)

Mache ich beim SQL Import nen Fehler - oder liegt es an der Config.php ? Hab aber nirgens so eine richtige Erklärung dazu gefunden.

**Comment by MyIgel** [comment]
Zwischen der `2.0.0` und dem aktuellen Master hat sich das format der `config.php` leicht geändert, hattest du eventuell vorher den master installiert? Am sinnvollsten ist  es hier eventuell wenn du die `config.php` noch mal löschst und die einzelnen Werte der `config.default.php` übernimmst.

Zum SQL error: Hast du die Datei doppelt importiert? Tritt er auch auf wenn du alle Tabellen aus der Datenbank löschst und dann die install & update importierst? Welche Version hat dein MariaDB/MySQL Server?

**Comment by TDansa** [comment]
Das hab ich bereits probiert, also config.php löschen und neu kopieren - die config.php wird in den config ordner kopiert und die config.default.php wird gelöscht - korrekt?
Somit hat die config.php eigtl den gleichen Inhalt wie die default, nur halt angepasst mit meinen Daten.

Hier mal der Abschnitt meiner config mit der DB vielleicht trag ich was falsch ein? (natürlich mit angepassten daten :) )

> return [
>     // MySQL-Connection Settings
>     'database'                => [
>         'host' => env('MYSQL_HOST', (env('CI', false) ? 'mariadb' : ' **Hier der Hostname meiner DB in dem Format: dbblabla.db.1and1.com**')),
>         'user' => env('MYSQL_USER', '**Hier mein DB User**'),
>         'pw'   => env('MYSQL_PASSWORD', '**Hier das PW meines DB Users**'),
>         'db'   => env('MYSQL_DATABASE', '**Hier mein DBName**'),
>     ],

Zur SQL Datenbank: ist eine MySQL 5.5
Ja der Fehler tritt auch auf, wenn ich die Tabellen nochmal alle komplett raus haue via drop befehl - und dann install und update neu importiere.

Sorry für die ganzen Probleme :D

**Comment by MyIgel** [comment]
In der 2.0.0 muss die config.default.php noch vorhanden sein, das könnte die Fehler erklären ;)

Generell kannst du in deiner eigenen Config den env() teil raus lassen, der ist in dem Falle nicht relevant, also

```php
'database' => [
    'host' => ' dbblabla.db.1and1.com',
    'user' => 'DB User',
    'pw' => 'PW DB Users',
    'db' => 'DBName',
],
```

**Comment by TDansa** [comment]
Muss in die config.php nur das rein, was ich auch individuell angepasst habe? 
Oder der gesamte Inhalt der config.default.php ?

**Comment by MyIgel** [comment]
Die `config.php` überschreibt die Inhalte der `config.default.php`, reine Listen (also arrays ohne keys) werden gemerged

**Comment by TDansa** [comment]
hmm.. also egal wie, ich bekomme gerade immer diesen Fehler:

An unexpected error occurred, a team of untrained monkeys has been dispatched to deal with it.object(ParseError)#17 (7) { ["message":protected]=> string(43) "syntax error, unexpected ')', expecting ']'" ["string":"Error":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(69) "/homepages/24/d351164237/htdocs/Engelsystem/config/config.default.php" ["line":protected]=> int(10) ["trace":"Error":private]=> array(4) { [0]=> array(6) { ["file"]=> string(63) "/homepages/24/d351164237/htdocs/Engelsystem/src/Application.php" ["line"]=> int(62) ["function"]=> string(8) "register" ["class"]=> string(40) "Engelsystem\Config\ConfigServiceProvider" ["type"]=> string(2) "->" ["args"]=> array(0) { } } [1]=> array(6) { ["file"]=> string(63) "/homepages/24/d351164237/htdocs/Engelsystem/src/Application.php" ["line"]=> int(84) ["function"]=> string(8) "register" ["class"]=> string(23) "Engelsystem\Application" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(Engelsystem\Config\ConfigServiceProvider)#18 (1) { ["app":protected]=> object(Engelsystem\Application)#3 (19) { ["appPath":protected]=> string(43) "/homepages/24/d351164237/htdocs/Engelsystem" ["isBootstrapped":protected]=> bool(false) ["serviceProviders":protected]=> array(3) { [0]=> object(Engelsystem\Logger\LoggerServiceProvider)#8 (1) { ["app":protected]=> *RECURSION* } [1]=> object(Engelsystem\Exceptions\ExceptionsServiceProvider)#12 (1) { ["app":protected]=> *RECURSION* } [2]=> *RECURSION* } ["resolved":protected]=> array(8) { ["Engelsystem\Config\Config"]=> bool(true) ["Engelsystem\Logger\LoggerServiceProvider"]=> bool(true) ["Engelsystem\Logger\EngelsystemLogger"]=> bool(true) ["Engelsystem\Exceptions\ExceptionsServiceProvider"]=> bool(true) ["Engelsystem\Exceptions\Handler"]=> bool(true) ["Engelsystem\Exceptions\Handlers\Legacy"]=> bool(true) ["Engelsystem\Exceptions\Handlers\LegacyDevelopment"]=> bool(true) ["Engelsystem\Config\ConfigServiceProvider"]=> bool(true) } ["bindings":protected]=> array(5) { ["Psr\Container\ContainerInterface"]=> array(2) { ["concrete"]=> object(Closure)#2 (3) { ["static"]=> array(2) { ["abstract"]=> string(32) "Psr\Container\ContainerInterface" ["concrete"]=> string(23) "Engelsystem\Application" } ["this"]=> *RECURSION* ["parameter"]=> array(2) { ["$container"]=> string(10) "" ["$parameters"]=> string(10) "" } } ["shared"]=> bool(false) } ["Psr\Log\LoggerInterface"]=> array(2) { ["concrete"]=> object(Closure)#7 (3) { ["static"]=> array(2) { ["abstract"]=> string(23) "Psr\Log\LoggerInterface" ["concrete"]=> string(6) "logger" } ["this"]=> *RECURSION* ["parameter"]=> array(2) { ["$container"]=> string(10) "" ["$parameters"]=> string(10) "" } } ["shared"]=> bool(false) } ["Engelsystem\Logger\EngelsystemLogger"]=> array(2) { ["concrete"]=> object(Closure)#4 (3) { ["static"]=> array(2) { ["abstract"]=> string(36) "Engelsystem\Logger\EngelsystemLogger" ["concrete"]=> string(6) "logger" } ["this"]=> *RECURSION* ["parameter"]=> array(2) { ["$container"]=> string(10) "" ["$parameters"]=> string(10) "" } } ["shared"]=> bool(false) } ["Engelsystem\Exceptions\Handlers\HandlerInterface"]=> array(2) { ["concrete"]=> object(Closure)#9 (3) { ["static"]=> array(2) { ["abstract"]=> string(48) "Engelsystem\Exceptions\Handlers\HandlerInterface" ["concrete"]=> string(24) "error.handler.production" } ["this"]=> *RECURSION* ["parameter"]=> array(2) { ["$container"]=> string(10) "" ["$parameters"]=> string(10) "" } } ["shared"]=> bool(false) } ["Engelsystem\Exceptions\Handler"]=> array(2) { ["concrete"]=> object(Closure)#11 (3) { ["static"]=> array(2) { ["abstract"]=> string(30) "Engelsystem\Exceptions\Handler" ["concrete"]=> string(13) "error.handler" } ["this"]=> *RECURSION* ["parameter"]=> array(2) { ["$container"]=> string(10) "" ["$parameters"]=> string(10) "" } } ["shared"]=> bool(false) } } ["methodBindings":protected]=> array(0) { } ["instances":protected]=> array(12) { ["path"]=> string(43) "/homepages/24/d351164237/htdocs/Engelsystem" ["path.config"]=> string(50) "/homepages/24/d351164237/htdocs/Engelsystem/config" ["path.lang"]=> string(50) "/homepages/24/d351164237/htdocs/Engelsystem/locale" ["app"]=> *RECURSION* ["container"]=> *RECURSION* ["Engelsystem\Container\Container"]=> *RECURSION* ["Engelsystem\Application"]=> *RECURSION* ["logger"]=> object(Engelsystem\Logger\EngelsystemLogger)#6 (1) { ["allowedLevels":protected]=> array(8) { [0]=> string(5) "alert" [1]=> string(8) "critical" [2]=> string(5) "debug" [3]=> string(9) "emergency" [4]=> string(5) "error" [5]=> string(4) "info" [6]=> string(6) "notice" [7]=> string(7) "warning" } } ["error.handler.production"]=> object(Engelsystem\Exceptions\Handlers\Legacy)#10 (0) { } ["error.handler.development"]=> object(Engelsystem\Exceptions\Handlers\LegacyDevelopment)#14 (0) { } ["error.handler"]=> object(Engelsystem\Exceptions\Handler)#13 (3) { ["environment":protected]=> string(4) "prod" ["handler":protected]=> array(2) { ["prod"]=> object(Engelsystem\Exceptions\Handlers\Legacy)#10 (0) { } ["dev"]=> object(Engelsystem\Exceptions\Handlers\LegacyDevelopment)#14 (0) { } } ["request":protected]=> object(Engelsystem\Http\Request)#15 (23) { ["attributes"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#21 (1) { ["parameters":protected]=> array(0) { } } ["request"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#19 (1) { ["parameters":protected]=> array(0) { } } ["query"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#20 (1) { ["parameters":protected]=> array(0) { } } ["server"]=> object(Symfony\Component\HttpFoundation\ServerBag)#24 (1) { ["parameters":protected]=> array(0) { } } ["files"]=> object(Symfony\Component\HttpFoundation\FileBag)#23 (1) { ["parameters":protected]=> array(0) { } } ["cookies"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#22 (1) { ["parameters":protected]=> array(0) { } } ["headers"]=> object(Symfony\Component\HttpFoundation\HeaderBag)#25 (2) { ["headers":protected]=> array(0) { } ["cacheControl":protected]=> array(0) { } } ["content":protected]=> NULL ["languages":protected]=> NULL ["charsets":protected]=> NULL ["encodings":protected]=> NULL ["acceptableContentTypes":protected]=> NULL ["pathInfo":protected]=> NULL ["requestUri":protected]=> NULL ["baseUrl":protected]=> NULL ["basePath":protected]=> NULL ["method":protected]=> NULL ["format":protected]=> NULL ["session":protected]=> NULL ["locale":protected]=> NULL ["defaultLocale":protected]=> string(2) "en" ["isHostValid":"Symfony\Component\HttpFoundation\Request":private]=> bool(true) ["isForwardedValid":"Symfony\Component\HttpFoundation\Request":private]=> bool(true) } } ["config"]=> object(Engelsystem\Config\Config)#16 (1) { ["data":protected]=> array(0) { } } } ["aliases":protected]=> array(0) { } ["abstractAliases":protected]=> array(0) { } ["extenders":protected]=> array(0) { } ["tags":protected]=> array(0) { } ["buildStack":protected]=> array(0) { } ["with":protected]=> array(0) { } ["contextual"]=> array(0) { } ["reboundCallbacks":protected]=> array(0) { } ["globalResolvingCallbacks":protected]=> array(0) { } ["globalAfterResolvingCallbacks":protected]=> array(0) { } ["resolvingCallbacks":protected]=> array(0) { } ["afterResolvingCallbacks":protected]=> array(0) { } } } } } [2]=> array(6) { ["file"]=> string(68) "/homepages/24/d351164237/htdocs/Engelsystem/includes/engelsystem.php" ["line"]=> int(26) ["function"]=> string(9) "bootstrap" ["class"]=> string(23) "Engelsystem\Application" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(Engelsystem\Config\Config)#5 (1) { ["data":protected]=> array(1) { ["providers"]=> array(8) { [0]=> string(40) "Engelsystem\Logger\LoggerServiceProvider" [1]=> string(48) "Engelsystem\Exceptions\ExceptionsServiceProvider" [2]=> string(40) "Engelsystem\Config\ConfigServiceProvider" [3]=> string(42) "Engelsystem\Routing\RoutingServiceProvider" [4]=> string(44) "Engelsystem\Renderer\RendererServiceProvider" [5]=> string(44) "Engelsystem\Database\DatabaseServiceProvider" [6]=> string(39) "Engelsystem\Http\RequestServiceProvider" [7]=> string(39) "Engelsystem\Http\SessionServiceProvider" } } } } } [3]=> array(4) { ["file"]=> string(60) "/homepages/24/d351164237/htdocs/Engelsystem/public/index.php" ["line"]=> int(5) ["args"]=> array(1) { [0]=> string(68) "/homepages/24/d351164237/htdocs/Engelsystem/includes/engelsystem.php" } ["function"]=> string(12) "require_once" } } ["previous":"Error":private]=> NULL }

**Comment by MyIgel** [comment]
Du hast einen syntax error in der `config.default.php` in Zeile `10` (oder eine davor) ;)

**Comment by MyIgel** [comment]
Äh du solltest eventuell noch ein `exit;` hinter das `var_dump($e);` in der `src/Exceptions/Handlers/Legacy.php` setzen ;)

**Comment by TDansa** [comment]
Das ist es leider nicht, problem ist trotzdem noch drin - hab den part jetzt wieder raus genommen da ich ihn ja eigentlich nicht mehr brauch.

Das Phänomen ist, ich komme auf die Haupturl, aber sobald ich etwas anklick und in der url z.B. ./register steht - kommt dieser Fehler
Ist da doch noch was mit der SQL Datenbank?

**Comment by MyIgel** [comment]
Hm...
Kannst du mich mal auf anderem Wege kontaktieren damit ich mir das mal mit dir anschauen kann? Message pingpong führt hier glaube ich zu nichts, ein mumble oä ist wahrscheinlich sinnvoller ;)

**Comment by TDansa** [comment]
Hab dir ne Mail geschickt ;)

**Comment by R4U5CH1337** [comment]
Hallo.
Ich würde das Thema auch gerne noch mal ausgraben.

Ich versuche ebenfalls das Engelsystem auf einem simplen Webspace (mit php, mysql, ftp, ..) zu installieren. Allerdings habe ich nur eine leere Seite, wenn ich auf die /public navigiere.

DB ist angelegt und auch in der config.php hinterlegt, sowie die sql Dateien importiert.
Was mache ich falsch? Was habe ich vergessen?

Danke euch.
