### ISSUE TITLE
MYSQL Import Error bei update.sql

### ISSUE THREAD

**Issue by TDansa** [engelsystem/engelsystem#495]
Hi,

habe festgestellt das beim Import der update.sql Datei der import bei Zeile 36 abbricht.

Folgender SQL Fehler:
```
Fehler

SQL-Befehl:

ALTER TABLE `AngelTypes` DROP FOREIGN KEY angeltypes_ibfk_1

MySQL meldet: Dokumentation
#1025 - Fehler beim Umbenennen von './db749902536/AngelTypes' in './db749902536/#sql2-59d-108e89c' (Fehler: 152)
```

Alles was danach kommt, wird somit auch nicht ausgeführt und der Import wird quasi abgebrochen.
Grundsätzlich habe ich nur eine neue DB erstellt, und diese mit install.sql und update.sql bespielt.

Ich habe nun alles was danach kommt, manuell eingespielt, das hat auch funktioniert und scheint auch keine Einschränkungen zu geben (im Moment)

Kann mir aber jemand sagen ob ich diese beiden Abfragen ausführen muss? Wofür sind sie gut?

```
ALTER TABLE `AngelTypes` DROP FOREIGN KEY angeltypes_ibfk_1;
ALTER TABLE `AngelTypes` DROP `contact_user_id`;
```

Thx :-)

**Comment by MyIgel** [comment]
Bei mir funktioniert der Import problemlos, was für eine Datenbankversion benutzt du?

Der Teil des Queries löscht den foreign key (`angeltypes_ibfk_1`) der Spalte `contact_user_id` in der `AngelTypes` Tabelle um diese Spalte anschließend zu löschen

**Comment by TDansa** [comment]
MySQL 5.5
Manuell kann man das auch machen, aber der Befehl funktioniert irgendwie nicht.

**Comment by TDansa** [comment]
Okay das löst das Problem ;) Danke dir!
