### ISSUE TITLE
Double Signup for shifts - inconsistency

### ISSUE THREAD

**Issue by NilsKet** [engelsystem/engelsystem#496]
I have signed up for two shifts that are at the same time (should this even be possible? - maybe). On the user-shifts page this is displayed correctly:

![image](https://user-images.githubusercontent.com/33804036/48405583-d0aa4180-e732-11e8-8efd-e26d052b6f73.png)

But when looking at my user profile only one of those two shifts is shown:

![image](https://user-images.githubusercontent.com/33804036/48405647-f3d4f100-e732-11e8-8b48-29e4d5d2e739.png)

**Comment by der-michik** [comment]
https://github.com/engelsystem/engelsystem/blob/412be8e1884eab7d543c26fafcc93fca3eca8cd1/includes/view/User_view.php#L437

Pretty obvious that this only yields one table row when both shifts start at the same time.

BTW: Bumping yourself into multiple shifts running simultaneously is and should be absolutely possible if you are a shift coordinator like in this case...

**Comment by MyIgel** [comment]
This problem got solved at the camp
