### ISSUE TITLE
Router bug after release  944c29b96429ec95ac1371cb33cc43704a60c7b1

### ISSUE THREAD

**Issue by AnsgarSchmidt** [engelsystem/engelsystem#505]
HI
the current master has a bug which was introduced after the commit 944c29b96429ec95ac1371cb33cc43704a60c7b1 (this one works)

engelsystem_1  | 172.27.0.3 -  27/Nov/2018:23:10:22 +0000 "GET /index.php" 500
engelsystem_1  | [27-Nov-2018 23:10:22] WARNING: [pool www] child 8 said into stderr: "NOTICE: PHP message: Exception: Code: 0, Message: file_put_contents(/var/www/storage/cache/routes.cache.php): failed to open stream: No such file or directory, File: vendor/nikic/fast-route/src/functions.php:68, Trace: [{"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"file_put_contents(\/var\/www\/storage\/cache\/routes.cache.php): failed to open stream: No such file or directory","\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php",68,{"routeDefinitionCallback":{},"options":{"cacheFile":"\/var\/www\/storage\/cache\/routes.cache.php","routeParser":"FastRoute\\RouteParser\\Std","dataGenerator":"FastRoute\\DataGenerator\\GroupCountBased","dispatcher":"FastRoute\\Dispatcher\\GroupCountBased","routeCollector":"FastRoute\\RouteCollector","cacheDisabled":false},"dispatchData":[{"GET":{"\/credits":"CreditsController@index"}},[]],"routeCollector":{}}]},{"file":"\/var\/www\/vendor\/nikic\/fast-r...
engelsystem_1  | [27-Nov-2018 23:10:22] WARNING: [pool www] child 8 said into stderr: ""
nginx_1        | 2018/11/27 23:10:22 [error] 8#8: *1 FastCGI sent in stderr: "PHP message: Exception: Code: 0, Message: file_put_contents(/var/www/storage/cache/routes.cache.php): failed to open stream: No such file or directory, File: vendor/nikic/fast-route/src/functions.php:68, Trace: [{"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"file_put_contents(\/var\/www\/storage\/cache\/routes.cache.php): failed to open stream: No such file or directory","\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php",68,{"routeDefinitionCallback":{},"options":{"cacheFile":"\/var\/www\/storage\/cache\/routes.cache.php","routeParser":"FastRoute\\RouteParser\\Std","dataGenerator":"FastRoute\\DataGenerator\\GroupCountBased","dispatcher":"FastRoute\\Dispatcher\\GroupCountBased","routeCollector":"FastRoute\\RouteCollector","cacheDisabled":false},"dispatchData":[{"GET":{"\/credits":"CreditsController@index"}},[]],"routeCollector":{}}]},{"file":"\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php","line":68,"function":"file_put_contents","args":["\/" while reading response header from upstream, client: ::ffff:172.27.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.27.0.2:9000", host: "localhost:5000"
engelsystem_1  | [27-Nov-2018 23:10:23] WARNING: [pool www] child 9 said into stderr: "NOTICE: PHP message: Exception: Code: 0, Message: file_put_contents(/var/www/storage/cache/routes.cache.php): failed to open stream: No such file or directory, File: vendor/nikic/fast-route/src/functions.php:68, Trace: [{"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"file_put_contents(\/var\/www\/storage\/cache\/routes.cache.php): failed to open stream: No such file or directory","\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php",68,{"routeDefinitionCallback":{},"options":{"cacheFile":"\/var\/www\/storage\/cache\/routes.cache.php","routeParser":"FastRoute\\RouteParser\\Std","dataGenerator":"FastRoute\\DataGenerator\\GroupCountBased","dispatcher":"FastRoute\\Dispatcher\\GroupCountBased","routeCollector":"FastRoute\\RouteCollector","cacheDisabled":false},"dispatchData":[{"GET":{"\/credits":"CreditsController@index"}},[]],"routeCollector":{}}]},{"file":"\/var\/www\/vendor\/nikic\/fast-r...
engelsystem_1  | 172.27.0.3 -  27/Nov/2018:23:10:23 +0000 "GET /index.php" 500
engelsystem_1  | [27-Nov-2018 23:10:23] WARNING: [pool www] child 9 said into stderr: ""
nginx_1        | 2018/11/27 23:10:23 [error] 8#8: *1 FastCGI sent in stderr: "PHP message: Exception: Code: 0, Message: file_put_contents(/var/www/storage/cache/routes.cache.php): failed to open stream: No such file or directory, File: vendor/nikic/fast-route/src/functions.php:68, Trace: [{"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"file_put_contents(\/var\/www\/storage\/cache\/routes.cache.php): failed to open stream: No such file or directory","\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php",68,{"routeDefinitionCallback":{},"options":{"cacheFile":"\/var\/www\/storage\/cache\/routes.cache.php","routeParser":"FastRoute\\RouteParser\\Std","dataGenerator":"FastRoute\\DataGenerator\\GroupCountBased","dispatcher":"FastRoute\\Dispatcher\\GroupCountBased","routeCollector":"FastRoute\\RouteCollector","cacheDisabled":false},"dispatchData":[{"GET":{"\/credits":"CreditsController@index"}},[]],"routeCollector":{}}]},{"file":"\/var\/www\/vendor\/nikic\/fast-route\/src\/functions.php","line":68,"function":"file_put_contents","args":["\/" while reading response header from upstream, client: ::ffff:172.27.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.27.0.2:9000", host: "localhost:5000", referrer: "http://localhost:5000/"
contrib_nginx_1 exited with code 0
contrib_nginx_1 exited with code 0

Sorry, can't help further, just noticed.

Greetings
Ansi

**Comment by MyIgel** [comment]
Did you fully deployed the latest engelsystem Version? It seems that the `storage/cache` directory is missing. If it is there: Has the PHP process write permissions to it as stated in the readme?

**Comment by AnsgarSchmidt** [comment]
Hi,
yes, I used docker for it.
$ git rev-parse HEAD        
e0de2c2c656e708f13bd69a0c98bacb7fdb4104c

here is what I did:

git pull https://github.com/engelsystem/engelsystem.git
cd engelsystem/contrib
docker-compose build nginx (have to do this step by hand before the complete build, otherwise the engelsystem can not reverence it)
docker-compose build
docker-compose up

in a new terminal:
docker exec -it contrib_engelsystem_1 bin/migrate

open a browser on localhost:5000 -> "An unexpected error occurred, a team of untrained monkeys has been dispatched to deal with it." (Damned cool error message btw)

Greetings
Ansgar

**Comment by MyIgel** [comment]
Äh, that's rights, maybe i missed to add this to the `Dockerfile` *dumdidum*
Fixing in progress, PR incoming
