### ISSUE TITLE
iCal/JSON export only works when logged in

### ISSUE THREAD

**Issue by s3lph** [engelsystem/engelsystem#519]
The iCal or JSON export at engelsystem.de/35c3 currently only works when a user is logged in and has a session cookie; the API key in the URL does not seem to have any effect and only seems to be checked for the required length.

When requesting the JSON export without a session cookie, but with a valid API key, the output is
```
No privilege for shifts_json_export.
```

However, the same request works when a valid session cookie is present.

**Comment by MyIgel** [comment]
That us really a bug :(
The user gets first validated with his api key and then (as some kind of fallback) by his cookie.

-> I fixed it in #520 which should be merged soon
