### ISSUE TITLE
Login does not work ->Invalid range in character class

### ISSUE THREAD

**Issue by AnsgarSchmidt** [engelsystem/engelsystem#523]
Hi,

I try to use the docker version.

docker system prune -af --volumes
docker-compose build nginx
docker-compose build
docker-compose up -d
docker exec engelsystem_engelsystem_1 bin/migrate
http://localhost:5000 

login with admin/asdfasdf

result:

[12-Dec-2018 21:12:37] NOTICE: ready to handle connections
172.21.0.3 -  12/Dec/2018:21:13:06 +0000 "GET /index.php" 200
172.21.0.3 -  12/Dec/2018:21:13:07 +0000 "GET /index.php" 404
NOTICE: PHP message: Exception: Code: 0, Message: preg_replace(): Compilation failed: invalid range in character class at offset 13, File: includes/model/User_model.php:119, Trace: [{"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"preg_replace(): Compilation failed: invalid range in character class at offset 13","\/var\/www\/includes\/model\/User_model.php",119,{"nick":"admin"}]},{"file":"\/var\/www\/includes\/model\/User_model.php","line":119,"function":"preg_replace","args":["\/([^\\p{L}\\p{N}-_. ]+)\/ui","","admin"]},{"file":"\/var\/www\/includes\/pages\/guest_login.php","line":391,"function":"User_validate_Nick","args":["admin"]},{"file":"\/var\/www\/src\/Middleware\/LegacyMiddleware.php","line":193,"function":"guest_login","args":[]},{"file":"\/var\/www\/src\/Middleware\/LegacyMiddleware.php","line":83,"function":"loadPage","class":"Engelsystem\\Middleware\\LegacyMiddleware","type":"->","args":["login"]},{"file":"\/var\/www\/src\/Middleware\/RouteDispatcher...
172.21.0.3 -  12/Dec/2018:21:13:13 +0000 "POST /index.php" 500
172.21.0.3 -  12/Dec/2018:21:13:14 +0000 "GET /index.php" 404

Greetings
Ansi

**Comment by MyIgel** [comment]
The "problem" is that PHP 7.3 (Which is used in the docker container) [uses PCRE2](http://php.net/manual/en/migration73.other-changes.php#migration73.other-changes.pcre) which validates regexes [more strictly](https://ayesh.me/Upgrade-PHP-7.3#pcre2). That means that in a `-` in a character set `[...]` needs to be escaped.
In that case the `'/([^\p{L}\p{N}-_. ]+)/ui'` needs to be replaced with `'/([^\p{L}\p{N}\-_. ]+)/ui'`, I'm working on a PR
