### ISSUE TITLE
multiple worklogs on same day not displayed in users shift list (but counted in sum)

### ISSUE THREAD

**Issue by clemensmach** [engelsystem/engelsystem#531]
adding more than one workload for a user on the same day
_(happens accidently when you enter it 0:05h)_
result: only first one displayed in shifts list, all entries in sum 
expected result: list all entries, not one per day

nice to have: show ID of added entry in log

![sameday](https://user-images.githubusercontent.com/19281519/50314084-cc99de00-04ad-11e9-8a1e-ace792f52bc5.png)

**Comment by clemensmach** [comment]
völlig ungetestet:

[user_view.zip](https://github.com/engelsystem/engelsystem/files/2700876/user_view.zip)

**Comment by MyIgel** [comment]
Thank you for your contribution! I committed it for you :)
