### ISSUE TITLE
Schichten werden gebucht, bevor Engel 'arrived' ist

### ISSUE THREAD

**Issue by Blue-Box** [engelsystem/engelsystem#539]
Beobachtet aktuell zum 35C3
z.B. bei diesen Schichten:
https://engelsystem.de/35c3/shifts?action=view&shift_id=409 (die ersten drei Engel)
https://engelsystem.de/35c3/shifts?action=view&shift_id=446 (alle vier Engel)
Im Logfile geprüft, die Engel haben sich selber auf die Schicht gebucht, aber sind und waren nicht 'arrived'.

**Comment by der-michik** [comment]
Signup requires arrival war zeitweise aus, daran wird das liegen. Die haben halt Glück gehabt und waren zur richtigen Zeit am richtigen Ort.
