### ISSUE TITLE
T-Shirt score does not count when the shift is just passing the time maark for double hours

### ISSUE THREAD

**Issue by einfachtorben** [engelsystem/engelsystem#561]
We've heard, that the T-Shirt Score does not increase when the shift is just passing the set time mark for double the hours.
for example when when the shift is from 00:00 to 02:40 these 40 minutes should theoretically count twice. but it doesnt.

**Comment by cbeneke** [comment]
duplicates https://github.com/engelsystem/engelsystem/issues/406
