### ISSUE TITLE
Additional custom information in user profiles for shift coordinators

### ISSUE THREAD

**Issue by MichiK** [engelsystem/engelsystem#564]
With over 4000 angels it becomes very hard to remember and coordinate special arrangements with individual angels that may be relevant when that angel comes to or calls Heaven and talks to a random shift coordinator.

This year, we had a permanent task in our Kanboard to share such information but that was not seen by people when it would have been useful and caused issues. I think it would be easier to have this as a comment field in a user's profile that is only visible for shift coordinators (like the freeload comment).

**Comment by MyIgel** [comment]
* and should be only visible after clicking an icon

**Comment by MyIgel** [comment]
Implemented by #1260
