### ISSUE TITLE
Better voucher count calculation

### ISSUE THREAD

**Issue by MichiK** [engelsystem/engelsystem#566]
Currently, the number of vouchers which an angel should receive is only determined by the count of shifts worked. This works well in cases where all shifts are of the same length and each and every shift counts equally. Meanwhile, the food voucher situation on congress became more complex:

* Shifts are of different lengths (talk-related shifts are usually shorter than 2 hours, some coordinator shifts are up to 4 hours long)
* Only shifts starting no earlier than a specific date/time count for vouchers (buildup shifts to not count during congress as food is free during buildup)
* Angels can get a maximum of 3 vouchers a day (starting with the day they were marked as arrived, they worked for the first time or the earliest voucher-eligible date - whichever comes latest)
* We now have not only shifts but also work log entries (I haven't checked if these count for vouchers or not)

This makes voucher calculation complex for shift coordinators and angels might be confused because it is not very easy for them to figure out if they may get vouchers or not, and if yes, how many.

Configuration should include:

* hours per voucher
* earliest voucher time
* max. vouchers per day

**Comment by Wiiilmaa** [comment]
It should also be possible to configure Workload Entries as eligible for Vouchers.

**Comment by Blue-Box** [comment]
@MyIgel I believe this issue has been resolved during the 36C3 with an update?

**Comment by MyIgel** [comment]
Except the point that there is a hard limit (for example 3 vouchers/day) but thats imho optional (but can be discussed further)
