### ISSUE TITLE
Installation webspace

### ISSUE THREAD

**Issue by R4U5CH1337** [engelsystem/engelsystem#570]
Hi,
auch auf die Gefahr hin ein Doppelpost ([hier](https://github.com/engelsystem/engelsystem/issues/492), [hier](https://github.com/engelsystem/engelsystem/issues/255), [hier](https://github.com/engelsystem/engelsystem/issues/265)) zu erstellen, würde ich mich über Tipps zur Installation auf einem simplen Webspace (PHP, mySQL, FTP, Subdomain, kein Composer, kein SSH, etc. = da uns leider ein v bzw root Server zu teuer ist) für unseren gemeinnützigen unkommerziellen Verein freuen.
Gerne auch per PM.

Was ich bisher versucht habe: subdomain auf /public gerichtet, Version 3.0 runtergeladen, Datenbank erstellt, DB (install & update) via phpMyAdmin importiert, zip hochgeladen, zip entpackt, config bearbeitet und die subdomain url im browser eingegeben, doch da hört es auf. Die Seite bleibt leider weiß.
Habe ich etwas vergessen oder falsch gemacht?
"Der Webserver muss auf public als http-root zeigen" - ist das schon mein Problem? Oder wie kann ich diese Anleitung verstehen?

Vielen lieben Dank!

**Comment by msquare** [comment]
Hi,

klingt erstmal gut. Leider ist das Projekt für deinen Hosting-Fall nicht so gut vorbereitet. Leere bitte die Datenbank nochmal und importiere die SQL-Datei, die direkt im Github Release liegt. Ich hoffe, dass es damit funktioniert.

**Comment by legeiger** [comment]
Erstelle als erstes die SQL Datenbank und importiere das sql File mittels myphp Admin.
Danach musst die Datei im Ordner config/config.example.php an deinen Hoster anpassen und als config.php speichern..
Bsp wie es bei mir beim kostenlosen Hoster bplaced.net aussieht:
` // MySQL-Connection Settings
    'database'                => [
        'host'     => env('MYSQL_HOST', 'localhost'),
        'database' => env('MYSQL_DATABASE', 'engelsystem'),
        'username' => env('MYSQL_USER', 'fak2'),
        'password' => env('MYSQL_PASSWORD', '************'),
    ],`

**Comment by MyIgel** [comment]
Moin, konntest du das Engelsystem installieren oder benötigst du weitere Hilfe? Wenn ja schreibe hier einfach drunter :)

Prinzipiell gilt:
Wenn kein Composer vorhanden ist können die Abhängigkeiten auch mit einem anderen System installiert werden und anschließend alle Dateien hochgeladen werden.
 Im Release `.zip` (zuletzt `3.0.0`) sind schon alle Dateien dabei, dieses muss nur entpackt und hochgeladen (und natürlich konfiguriert) werden.
Nach dem Importieren der Release `.sql` Datei sollte das Engelsystem auch auf einem shared webspace benutzbar sein.
