### ISSUE TITLE
Use the system for other purposes than C3/hacker events

### ISSUE THREAD

**Issue by ghost** [engelsystem/engelsystem#574]
I'm looking for an open-source web application to manage volunteers for different kind of events and tasks within the area of charity/non-profit organizations and associations.

I was wondering how flexible the engelsystem is to fit such a purpose or how difficult it would be to make it more generic, so it would not only serve for C3 and hacker congresses, but also for other events.

I think the project would greatly benefit from making it available to a broader audience.
What do you think?

**Comment by MyIgel** [comment]
As it's OSS anyone can use it, so I see no problems with that. While it's developed for chaos events, it could also be used for other shift plannings. Do you have any points where it's not flexible enough?

Our current goal is to make it more generic to use (and decouple more chaos specific functionality in the future), but imho its be already usable for all kinds of events.
