### ISSUE TITLE
Gitlab CI broken due to failing test job

### ISSUE THREAD

**Issue by k127** [engelsystem/engelsystem#582]
Hi there, after forking this nice project and trying to build it on my own Gitlab space, sadly the `test` job is failing for a **deprecation reason** [1], and the very same problem happens also on Gitlab `engelsystem/engelsystem` CI [2]:
> An <del>un</del>expected error occurred, a team of untrained monkeys has been dispatched to deal with it.Exception: Code: 0, Message: The "Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory" class is deprecated since symfony/psr-http-message-bridge 1.2, use PsrHttpFactory instead., File: vendor/symfony/psr-http-message-bridge/Factory/DiactorosFactory.php:14, Trace: …

Since the respective committed code changes [3] do not explicitly hint to a connection with the problem, I'd consider this a package incompatibility issue due to an unversioned `composer.lock` file.

EDIT:
This problem came up with a version change from `v1.1.1` to `v1.2.0` of package `symfony/psr-http-message-bridge` [4] that sneaked into this project within the last 7 days.

---
[1] <https://chaos.expert/engelsystem/engelsystem/-/jobs/24541>
[2] <https://chaos.expert/engelsystem/engelsystem/pipelines/21641>
[3] <https://chaos.expert/engelsystem/engelsystem/commit/69ac1b2d2115a41afe2bd4527abadda70063019a>
[4] <https://github.com/symfony/psr-http-message-bridge/compare/v1.1.1...v1.2.0#diff-7e5b3956b6ae2a5924719b9d4eecb8cdR14>

**Comment by MyIgel** [comment]
Jup, i know this (Got an email from my ci some days ago for this and another one). The "problem" is indeed the added warning in twig >=2.7 and could be fixed (have a half pr for that but this requires some [upstream changes](https://github.com/twigphp/Twig-extensions/issues/239)) with the version pinning.

The reason for not versioning the composer.lock is that it needs to be updated and working on the newest bugfix releases of software is normally a good thing while developing (and the master is normally the "should be kinda stable" branch). The release packages have a working composer.lock ;)

**Comment by k127** [comment]
Ok, looks like a good strategy since version pinning (of those two packages) provides the fix :)
