### ISSUE TITLE
On Shiftchange: Fatal Error when unable to send mail

### ISSUE THREAD

**Issue by jwacalex** [engelsystem/engelsystem#590]
Step to reproduce
1. Have one angel with active mail notifications
2. Sign up the angles for a shift
3. Change the time of the shift

Expected behavior:
The shift is changed, the user gets informed by mail.

Current behavior:
The shift is not changed, the execution stops with a fatal error

**Comment by MyIgel** [comment]
Seems to work fine if sending the email works as expected.
Do you have an error log?

**Comment by MacLemon** [comment]
I was asked to add requirements to send email on our system:

Submission:
Port 587 with `STARTTLS` before `AUTH` (recommended)
Port 465 with implicit TLS and `AUTH`

`auth_mechanisms = cram-md5 login plain`

**Comment by jwacalex** [comment]
@MyIgel the error itself is triggeres by the SMTP Mailing Library

"file":"\/usr\/local\/www\/engelsystem\/config\/config.php","line":48,"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[2,"Use of undefined constant tls - assumed 'tls' (this will throw an Error in a future version of PHP)","\/usr\/local\/www\/engelsystem\/config\/config.php",48,{"config":{"database":{"host":"localhost","database":"engelsystem","username":"root","password":""},"api_key":"","maintenance":false,"app_name":"Engelsystem","environment":"production","footer_items":{"FAQ":"https:\/\/events.ccc.de\/congress\/2013\/wiki\/Static:Volunteers","Contact":"mailto:ticket@c3heaven.de"},"email":{"driver":"mail","from":{"address":"noreply@engelsystem.de","name":"Engelsystem"},"host":"localhost","port":587,"encryption":null,"username":null,"password":null,"sendmail":"\/usr\/sbin\/sendmail -bs"" while reading response header from upstream, client: , server:  , request: "GET / HTTP/2.0", upstream: "", host: ""

**Comment by jwacalex** [comment]
@MyIgel The log is generated by the SMTP Transport Class, that cannot connect towards the Server that has been described by @MacLemon.

**Comment by MyIgel** [comment]
Did you tried setting `encryption` to `tls`? That should work imho.

Maybe we should mumble to debug this ;)

**Comment by jwacalex** [comment]
TLS resulted in an error. @MacLemon can provide the log

**Comment by MyIgel** [comment]
Thats right, `tls` should enable `STARTTLS` (port 587) and `ssl` would mean using an ssl encrypted connection (port 465), both work at least with my mail server so it would be helpful if @MacLemon could contanct me somehow.

**Comment by MacLemon** [comment]
That's pretty much exactly how I'd have interpreted the `ssl` and `tls` settings. (Sinsce almost nobody uses proper terms anyway. :-) )

Installed PHP modules as listed by `php -m` just in case.
```
[PHP Modules]
Core
date
filter
gettext
hash
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Reflection
session
SimpleXML
SPL
standard
```

**Comment by MyIgel** [comment]
I'm closing this issue as the original problem has been solved (Using port 465/ssl). Hardening the Engelsystem against this kind of config problems can be discussed in #591 (Show an error if email notification failed)

**Comment by MacLemon** [comment]
Thanks for the support.
I can confirm that switching Submission to port `465/tcp` with implicit `TLS`, did work fine.
It seems that `STARTTLS` on port `587/tcp` wasn't even attempted, but of course, was mandatory on our mailserver (as most would).
