### ISSUE TITLE
Integrate/document gettext export for .twig files

### ISSUE THREAD

**Issue by MyIgel** [engelsystem/engelsystem#594]
See https://github.com/engelsystem/engelsystem/commit/60ad343b22ab3cff886e8a8c0f57d40bbff8dcfc#commitcomment-33229728

**Comment by msquare** [comment]
Fixed with commit 9829e6da390c8a62f322e085cbf5b48a586446a0.

**Comment by MyIgel** [comment]
But how do you also exported translation strings from `.twig` files?

**Comment by msquare** [comment]
Using the following configuration:
https://gist.github.com/jlambe/a868d9b63d70902a12254ce47069d0e6

**Comment by MyIgel** [comment]
Hm, maybe we should provide all config options in the readme, an external gist could be deleted ;)
