### ISSUE TITLE
Issue in reverse proxy setup

### ISSUE THREAD

**Issue by cyb3rwr3ck** [engelsystem/engelsystem#620]
Hi there, 
I am facing an issue in a reverse proxy configuration where the front-end is offloading ssl, and the back-end is serving the engelsystem (both are on apache 2.4).
The backend generates all links with http instead of https, which obviously wont work. 
"RequestHeader set X-Forwarded-Proto https" is set on the front-end.

The engelsystem is working correctly if its contacted via its http port directly (its reachable via a debugging access which bypasses the offloader).

The relevant config parts of the front-end:

```
<VirtualHost *:80>
        ServerName <hostname>
        Redirect permanent / https://<hostname>/

        ErrorLog<SNIP>
        LogLevel warn
        CustomLog <SNIP>
</VirtualHost>

<VirtualHost *:443>
        ServerAdmin <SNIP>
        ServerName <hostname>

        Header always set X-Frame-Options SAMEORIGIN
        RequestHeader set X-Forwarded-Proto https

        ProxyPass "/"  "http://<internal_ip>:81/"
        ProxyPassReverse "/"  "http://<internal_ip>:81/"

        ProxyPreserveHost On

        ErrorLog <SNIP>
        LogLevel info
        CustomLog<SNIP>

        <IfModule mod_ssl.c>
<SNIP>
        </IfModule>
</VirtualHost>
```

And the config of the back-end:

```
<VirtualHost *:81>
        DocumentRoot <SNIP>/public
        ServerAdmin <SNIP>
        ServerName <hostname>

        <Directory <SNIP>/public>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        ErrorLog<SNIP>
        LogLevel warn
        CustomLog <SNIP>
</VirtualHost>

```

Any idea how to force the backend to generate https links? 
Thanks in advance!

**Comment by MyIgel** [comment]
Is the IP of the reverse proxy set in `trusted_proxies` in the config file?

If yes the Engelsystem should accept a X-Forwarded-Proto header from your reverse proxy.

**Comment by cyb3rwr3ck** [comment]
Oh sh**, I missed that one. Thank you!

**Comment by MyIgel** [comment]
No problem, I'm happy that it works!
