### ISSUE TITLE
Datepickers for planned arrival/departure date starts with sunday

### ISSUE THREAD

**Issue by 0xErnie** [engelsystem/engelsystem#630]
Calendar for planned arrival/depature date starts with Sunday when browser language is English.

This might lead to problems because angels from Germany assume that Monday is the first day of the week, when they do not check their calendar or the description.

**Comment by weeman1337** [comment]
Should we just implement [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) then (first day of week = Monday) or make this an user specific option? I would go for ISO.

**Comment by MyIgel** [comment]
The datepicker uses eonasdan-bootstrap-datetimepicker and changing the start of the week is somehow possible but looks somehow hacky: http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/#how-do-i-change-the-start-of-the-week
