### ISSUE TITLE
angels cannot sign up for restricted shifts even though they are accepted as the angeltype

### ISSUE THREAD

**Issue by loewenflausch** [engelsystem/engelsystem#632]
when we started using the engelsystem, we did not have any problems with signing up for restricted shifts. But we have added some more new angels in the past few days, and added (and accepted them also to be) to restricted Angel types. If they now want to sign up for restricted shifts, they can see them, but cannot sign up. The sign up - button is only displayed for the non-restricted angel types (for the very same shift where different types of angels are needed). We could solve the problem for a first instance by increase the angels rights from 2- Angel to 3- Shift Manager.

**Comment by msquare** [comment]
Is the angeltype setting "Self Sign Up Allowed" active?
This prevents angels to sign up for shifts by themselves.

**Comment by loewenflausch** [comment]
> Is the angeltype setting "Self Sign Up Allowed" active?
> This prevents angels to sign up for shifts by themselves.

yes, it seems as it worked! thanks a lot.
