### ISSUE TITLE
Shift overview - Possible timezone issue

### ISSUE THREAD

**Issue by pjdeltour** [engelsystem/engelsystem#633]
The shift filter shows the possible dates in a dropdown list. These dates are generated by the database which can possibly have a different timezone than the timezone chosen in the config. This can generate some issues where a created shift can't be displayed by the filter because the right date is unpickable.

For example:
Use Engelsystem in timezone Europe/Berlin, but the Mysql timezone is UTC.
When creating a shift which starts at 12/08/2019 at 00:00(CET), this generates unix timestamp 1565560800. When generating the dates for the dropdown list, the mysql date picker uses UTC time, which is 11/08/2019 at 22PM. Because of this, the date drop down list is not correctly shown.

I would recommend to pull the unix timestamp directly from the database and do the date conversion using the chosen timezone in the config file in the PHP code instead of using the `DATE(FROM_UNIXTIME(...))` in the mysql query which uses the Mysql timezone.

Or alternatively change the SQL query to `DATE(CONVERT_TZ(FROM_UNIXTIME(...), from_tz, to_tz)` in order to be completely sure the right date is chosen.

**Comment by herzmut** [comment]
As 2019-08-12 00:00:00 CET is supposed to create unix timestamp 1565571600, there's something wrong in taking the timezone into account properly when creating the unix timestamp. The timestamp you gave represents 2019-08-12 00:00:00 UTC .
