### ISSUE TITLE
Calculation of T-Shirt score is wrong

### ISSUE THREAD

**Issue by nmxcgeo** [engelsystem/engelsystem#644]
The calculation of T-Shirt scores doesn't match the worked houres in special cases.

Longer story: I had a shift where I was signed up as a runner. When I showed up ad heaven (the correct meeting point) noone was able to tell me where to go and it was decided to delete the shift and to assign me to bottle sorting, which I did. Later that evening I had a negative T-Shirt score of -2:00h for no apparent reason. Now the number of worked shifts (see attached screenshots) is supposed to add up to 10h (2 night shifts being in the future at point of writing) but T-Shirt score is 6:00h.
Username at Camp2019: Nitimax

![Screenshot from 2019-08-22 19-54-46](https://user-images.githubusercontent.com/25130823/63538024-57d4e300-c517-11e9-862b-93945d97de3c.png)

**Comment by msquare** [comment]
Actually the calculation of the T-Shirt score is correct, but your shifts table lies. Fix is incoming.
Please go to heaven to resolve your (the bug hides it) freeloader shift.

**Comment by msquare** [comment]
Thank you for reporting. The fix is deployed.
