### ISSUE TITLE
Notify on shift deletion

### ISSUE THREAD

**Issue by extmind** [engelsystem/engelsystem#645]
If a user enabled email notification for shift changes, they should also receive a notification on shift deletion. It seems to me that the deletion of a shift is a significant shift change.

I would consider from a user's perspective that the deletion of a complete shift and the deletion of the user from a particular shift are relevant here.

**Comment by msquare** [comment]
This should happen already. If not we need to find the reason..

**Comment by msquare** [comment]
What is the nick of the user, that didn't get the email?

**Comment by MyIgel** [comment]
This could be related to #640 (Don't delete work when deleting shifts)?

**Comment by MyIgel** [comment]
And the other question is: Was `The Engelsystem is allowed to send me an email` activated in the users settings?

**Comment by msquare** [comment]
I tested this - shift deletion email notifictation works fine.
This issue can only be misconfiguration/spam detection/generic admin problem - or the missing permission, as mentioned by @MyIgel.
