### ISSUE TITLE
Shifts after tshirt collection

### ISSUE THREAD

**Issue by sargon** [engelsystem/engelsystem#646]
Shifts after collection of the angel shirt are not shown in the personal shifts overview.

Expected Behavior: The shift overview shows all registered shifts.
Actual Behavior: After the T-Shirt collection no further shifts are shown.

**Comment by msquare** [comment]
Can you please add a screenshot?

**Comment by sargon** [comment]
Looks like I can't reproduce the bug now. I vote for caching problems ;)
