### ISSUE TITLE
Allow shift coordinators to add users to angeltypes

### ISSUE THREAD

**Issue by ofeldt** [engelsystem/engelsystem#648]
Currently only those with supporter rights and bureaucrats can add angels to shifts. Shift coordinators need to relay those information to those busy supporter rights holder, which is time consuming.

Allowing shift coordinators to at least add user to angeltypes would simplify this process.

**Comment by Mimoja** [comment]
Agree. This would be pretty nice

**Comment by msquare** [comment]
This is a configurable role/permission thing. It should now be possible.
We disabled this once, because the teams won't the heaven to confirm angels into angeltypes without introduction.
