### ISSUE TITLE
Frab import changes to support Translation shifts

### ISSUE THREAD

**Issue by korfuri** [engelsystem/engelsystem#649]
Hi, I had a discussion at Camp with @MyIgel about what the Translation angels would need in order to manage our shifts in the Engelsystem. On the technical side, the only blocker is related to the Frab import. Per our discussion, here's a list of what we would need:

* The Frab import currently can only be run by one group: it creates 1 shift for each event in the Fahrplan, with a count of angels configured per-room, and a before/after time buffer common to all. Translation team needs to reflect prep time in our shift, which differs from the 15/15 used today for room operation shifts. Ideally we'd like to run the import just to create Translation shifts, independently from the VOC who runs the import on their side to create the "room operation" shifts as they do today.

  I think a clean way to do this would be to configure each shifttype to be linked to N angeltypes, and create only shifts for these angeltypes during the Frab import. This way we would have a "Translation" shift type, enabling shifts for Translation angels, and VOC would keep the "Room Operation" shift type, enabling shifts for Camera, Signal, Crowd Control, etc. angels. (Note that shifttypes are already linked to 1 and only 1 angeltype but I have not found where that is used: it does not impact the Frab import).

* Our prep time is generally speaking a function of the talk length. Most of that prep doesn't necessarily happen during the shift, but we want to reflect it in the shift duration anyway. The cleanest way I can think of this would be:
  * Create our shifts with a lead time of 15min (because that's when we want folks in the cabin)
  * Add a buffer of `talk length * ratio - 15min` at the end, where `ratio` would be configurable

  If this is too complicated, we're open to suggestions on how to best approximate this.

I'm happy to bring clarifications on any of this. Thanks for all your help!

**Comment by korfuri** [comment]
Hi! I just wanted to know if I could provide any more info or context from the translate side. I'm happy to help in any way I can. Thanks!

**Comment by MyIgel** [comment]
Atm im working on the basics, if i am at the point of importing multiple types i'll ask ;)

**Comment by MyIgel** [comment]
A small update: My current version implements the know featureset of the old import, 'will do a PR for that soon.

**Comment by MyIgel** [comment]
The PR #1285  allows us to import multiple schedules and define the needed angels based on the selected shift type.
That means we will be able to add parallel shifts that start / end on different times before / after. (but without a ratio as that would make it currently more complicated). Would that work for you @korfuri? (would mean just having a predefined "after" time here)

**Comment by korfuri** [comment]
Yes, thank you! That should cover all our needs.
