### ISSUE TITLE
Docker dev setup

### ISSUE THREAD

**Issue by weeman1337** [engelsystem/engelsystem#660]
Jep I know - with https://github.com/engelsystem/engelsystem/commit/91eae7d067be09d0aa6af3dd617a7aff4a66a9bb something found it's way into the README. There is room for improvements. For example including xdebug with some helpers to get it working with IDEs. 

I would send a PR with my setup but I'm wondering where to put the docker dev setup. The current docker setup is placed in `/contrib`. Should the dev stuff then go to `/contrib/dev`?

**Comment by MyIgel** [comment]
Hmm, I think it would be an option to put a dev container to to `contrib/dev` (and maybe also rename contrib to docker or something?). This container should
* Extend the normal `contrib/Dockerfile` container (via a variable `FROM`) 
* can be also used in testing with gitlab (see `.gitlab-ci.yml`)
  * and can be deleted after a ci run?
* thus contain xdebug and composer + whatever could be needed

**Comment by msquare** [comment]
I put my docker dev into /contrib-dev, but thats detail.
Nice idea, definitively something I would use.
