### ISSUE TITLE
Make e-mail options more clear on registration

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#669]
> dieses Jahr hatten wir relativ viele Engel mit genug Stunden für nen
> Voucher, zu denen aber keine Mailadresse vorliegt (vmtl zu großen
> Teilen, weil sie nicht den Optin-Haken gesetzt haben?).
> 
> Ich erinner mich zwar so, als stünde beim signup ziemlich deutlichd
> abei, wofür der Haken ist, aber anscheinend hams ja viele verpasst:
> Falls du eh noch mal drüber guckst, kannst du noch mal gucken, ob man
> das noch deutlicher machen kann.

**Comment by MyIgel** [comment]
But what should we show instead of `Humans are allowed to send me an email (e.g. for ticket vouchers)`?
We could eventually change the position at which these are shown but i personally don't know what to do else :(

**Comment by msquare** [comment]
Since we will get more options for notifications/e-mails in future, these may be moved to a second page/step in the registration process to focus the user on theses options.
