### ISSUE TITLE
Number of shifts differs in web interface and API response

### ISSUE THREAD

**Issue by johnjohndoe** [engelsystem/engelsystem#674]
I created and assigned me for a couple shifts in the staging environment.
When I take a look in the web interface at `users?action=view` it renders **seven** shifts for me.
When I take a look at the JSON response at `shifts-json-export?key=apikey` then the API outputs **eight** shifts. One shift appears twice - only the `id` differs.

Is this a bug or am I missing something here?

**Comment by MyIgel** [comment]
Can you post the IDs of the JSON  export? That makes debugging easier ;)

**Comment by johnjohndoe** [comment]
The `SID` of both shifts is `579`, the `id` is `36` resp. `37`. Meanwhile they also differ by the `Comment`. The webinterface still shows one less then the API output.

**Comment by MyIgel** [comment]
Aaaand there is the "problem": You have signed up twice for the shift, see shifts?action=view&shift_id=579 ;)

**Comment by johnjohndoe** [comment]
Ah! The user interface now shows my username twice when I signed up twice. Thank you for the fix.
