### ISSUE TITLE
Prevent transferring unchanged content via the shifts-json-export API

### ISSUE THREAD

**Issue by johnjohndoe** [engelsystem/engelsystem#677]
It would be great if you could implement a mechanism which allows clients of the `shifts-json-export` API to **avoid loading** data which has **not changed**. This would save bandwidth and facilitate avoidance of redundant processing at the client side.

# Proposal
- I recommend using [HTTP ETag](https://en.wikipedia.org/wiki/HTTP_ETag) to accomplish the above behavior.

**Comment by MyIgel** [comment]
This would basically mean hashing the response (to use it as an etag) and implementing a check for the `If-None-Match` header, potentially responding with a `304 not modified`

**Comment by johnjohndoe** [comment]
Here is a curl command to try out if the ETag header works:

``` shell
curl -v -s -H "ETag: " -H "If-None-Match: " https://some.engelsystem.de/shifts-json-export\?key\=12345 > /dev/null
```

**Comment by MyIgel** [comment]
@johnjohndoe das staging engelsystem wurde auch gerade aktualisiert, du solltest also dort ETags verwenden können

**Comment by johnjohndoe** [comment]
:heavy_check_mark: Now available in the [EventFahrplan app](https://github.com/EventFahrplan/EventFahrplan/pull/575). Thank you!
