### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by weeman1337** [engelsystem/engelsystem#683]
I had a chat with @MyIgel about upgrading to Bootstrap 4. I did some investigation and here are some issues I found that we should think about:

- The current engelsystem is implemented using Less. A proper migration should then also cover switching from Less to Sass.
- Date datepicker doesn't seem to receive any updates. So I guess this has to be changed as well.
- This is a quite huge change. I would start that after the Congress

Any opinions about these points?

**Comment by msquare** [comment]
These points are the reason for me not starting this thing at all. I even considered a move to semantic ui or so. Do you really want to do this?

**Comment by weeman1337** [comment]
> Do you really want to do this?

Nope ;) I thought about improving some views. Then @MyIgel came along and had the idea to upgrade Bootstrap. Anyway I have no strong opinion on that.

**Comment by MyIgel** [comment]
Hm, afaik there where some tools to switch/convert from Less to Sass back then? Replacing the datepicker shouldn't be the biggest problem here i guess ^^
Imho its not the best idea to completely switch to another user interface as this would definitely require changing everything that has some output or living with two different frontends which i definitely want to avoid.

**Comment by digitaldonkey** [comment]
I fixed dome mobile issues in https://github.com/engelsystem/engelsystem/pull/713. 
But yes. Bootstrap 3 is a pain. Semantic or BS 4 Anything can be better :)

**Comment by rugk** [comment]
> Replacing the datepicker shouldn't be the biggest problem here i guess ^^

Considering modern browsers do have a good implemented default picker for "input type=date" (and time) that should really be easy.

**Comment by msquare** [comment]
Do you consider to include the bootstrap-icons package? This seems to be simple.
Or can I begin with that task, replacing the icons? @weeman1337

**Comment by weeman1337** [comment]
@msquare wait this weekend please. I already started the migration. I can include the icons package ✓.

**Comment by weeman1337** [comment]
Some intermediate report: It compiles the sources. Still requires migration of the structure.

But at least it's saying hello with BS5:

![image](https://user-images.githubusercontent.com/6216686/115077345-2d127c00-9efe-11eb-99c6-17dd46e181c7.png)

**Comment by weeman1337** [comment]
@msquare as the bootstrap icons are supported by bs5 and I need a replacement for Glyphicons I am adding the bootstrap icons during the migration.

**Comment by digitaldonkey** [comment]
Looks good in screenshot.
But some colors definitely don't work for WAI/ARIA minimum contrast
requirements. Please try to fix that at design system level.

I'm a bit afraid that the most work lies ahead when migration content
templates.
Are you planing on design guidelines? Like js on/off compatibility?
Keyboard navigation?

I also recommend to add some html validation to the pipeline as it prevents
errors you often search long for.


Michael Weimann ***@***.***> schrieb am Sa., 17. Apr. 2021,
15:24:

**Comment by weeman1337** [comment]
Hey @digitaldonkey . The screenshot is a work in progress ;) I am not changing fundemental structures. My goal is a 1:1 BS5 version. After that we can apply some fancy design guidelines or whatever.
