### ISSUE TITLE
Usage of the "container" class for some content areas

### ISSUE THREAD

**Issue by weeman1337** [engelsystem/engelsystem#688]
The page looks kind of lost in some places because it's too width. Many content areas simply use *col-md-12* → full width. I want to change the some pages to the bootstrap built in *container* class.

For example have a look at the news page:

before: [width_before](https://user-images.githubusercontent.com/6216686/69916347-4aa28b00-145a-11ea-97e8-fa299cb2979d.png)
container: [width_container](https://user-images.githubusercontent.com/6216686/69916346-4aa28b00-145a-11ea-8b44-2b13d5fd3e94.png)

What do you think about that?

**Comment by MyIgel** [comment]
If you want to change that: feel free as it improves the overall readability :)
