### ISSUE TITLE
Provide time zone offset via the shifts-json-export API

### ISSUE THREAD

**Issue by johnjohndoe** [engelsystem/engelsystem#689]
A typical API response contains a bunch of time stamps as shown in the following example:

``` json
[
  {
    "Comment": "Lorem ipsum dolor sit amet.",
    "Name": "Baikonur",
    "PSID": null,
    "RID": 14,
    "SID": 580,
    "TID": 10,
    "UID": 23,
    "URL": null,
    "created_at_timestamp": 1565979718,
    "created_by_user_id": 23,
    "description": "",
    "edited_at_timestamp": 1567362938,
    "edited_by_user_id": 23,
    "end": 1566423000,
    "freeloaded": 0,
    "from_frab": 1,
    "id": 42,
    "map_url": "",
    "name": "Collect stickers",
    "shifttype_id": 6,
    "start": 1566421200,
    "title": ""
  }
]
```

It would be useful for client applications which parse and process the time stamps to know which time zone is associated with the time stamps. Without the information apps need to guess and hardcode the time zone themselves.
Therefore, I would love to see a time zone information being provided as part of the response.

**Comment by johnjohndoe** [comment]
@MyIgel Thank you for this :zap: fast response. 
:shipit: Can you please post here once the new field is deployed on the staging and on the #36c3 instance?

**Comment by msquare** [comment]
We deployed it already :)

**Comment by johnjohndoe** [comment]
Nice. On both instances?

**Comment by msquare** [comment]
Only staging/test, since we found another bug to resolve first.

**Comment by msquare** [comment]
Its live on 36c3 now as well.

**Comment by johnjohndoe** [comment]
One more thing ..

I created a couple of test shifts in the staging system both for the Camp 2019 time range (08/2019) and the 36C3 (12/2019). Here are two examples - first a Camp shift at 22.08.2019:

``` json
{
    "Comment": "",
    "Name": "Baikonur",
    "RID": 14,
    "SID": 585,
    "TID": 10,
    "UID": 32,
    "URL": null,
    "created_at_timestamp": 1565979719,
    "created_by_user_id": 32,
    "description": "Baikonur (kasachisc...",
    "edited_at_timestamp": 1567367727,
    "edited_by_user_id": 32,
    "end": 1566435600,
    "freeloaded": 0,
    "id": 42,
    "map_url": "https://openstreetmap.org",
    "name": "Sticker sammeln",
    "shifttype_id": 6,
    "start": 1566434700,
    "timezone": "+01:00",
    "title": "Tag 2: Notebook bekleben bis 03:00"
}
```

Then one for 36C3 at 27.12.2019:

``` json
{
    "Comment": "",
    "Name": "Kourou",
    "RID": 13,
    "SID": 627,
    "TID": 6,
    "UID": 32,
    "URL": null,
    "created_at_timestamp": 1575838846,
    "created_by_user_id": 32,
    "description": null,
    "edited_at_timestamp": 1575838846,
    "edited_by_user_id": null,
    "end": 1577440800,
    "freeloaded": 0,
    "id": 54,
    "map_url": null,
    "name": "Sticker sammeln",
    "shifttype_id": 6,
    "start": 1577437200,
    "timezone": "+01:00",
    "title": "36C3 Sticker sammeln 10-11"
}
```

I noticed that for both shifts the `timezone` is set to `+01:00`. The Camp however was before 27.10.2019 when [Germany changed to winter time](https://www.timechange.info/germany-2019/). It became apparent because I am currently testing with the Camp 2019 schedule and shifts in the same time range.
To my understand each event needs to "deliver" its original time zone offset aka. the time zone offset which was valid when the event took place. I suppose the `+01:00` is returned for Camp shifts because that is the current time zone offset on the server as of today.
Can you please change this?
