### ISSUE TITLE
Unpopular Opinion: Rebuild from scratch instead of slow and painful migration.

### ISSUE THREAD

**Issue by cbluoss** [engelsystem/engelsystem#691]
## Disclaimer
This isn't meant to be offensive in any way and we're all happy that the engelsystem supports our events for such a long time.
Sometimes the perspective of a bystander is helpful.

## My impression about the current state of the project
The project isn't overly complicated by itself, but migrating 10y old legacy code to Symfony/Laravel/$framework is extremely labor intensive and slow. Often results in (slightly less) legacy code (e.g. migrations from 2018) while slowing down development of new features and improvements.

And I actually don't see the point of doing so. Engelsystems are usually fresh installations for single events and rarely long time installations where backwards compatibility really matters.

It feels like slowly converting a trabbi to a tesla and by the time you finally got a tesla it will be old already.

There are probably good reasons for doing so which I just don't realize, but I want to start this discussion anyway.

**Comment by msquare** [comment]
Well, we start this discussion every year for 10 years now. You may find about 10 failed rewrite attempts (even in different languages) on github. If you have the time, feel free. I will never try this again.

**Comment by MyIgel** [comment]
Definitely what @msquare wrote: Various ppl tried it and failed, plz don't be the next one :'(

It's not a "big" project but it has many smaller features/workflows that others expect/will miss if they don't get integrated. And that means that a rewrite has to cover all of them (not only the basic functionality) to be accepted and that's definitely a much bigger project.

Rebuilding only small parts (in the best case in a way that they get decoupled from another) is the more efficient method as it will allow us to replace some components in the future (maybe also in other languages/as Microservices or whatever will be the best option).

**Comment by cbluoss** [comment]
I've absolutly no intention nor time to start a copy by myself (and probably alone) and we all know the related xkcd about new standards.
But then all the small hidden features need to be reimplemented any ways.

**Comment by msquare** [comment]
Closing, due to unpopular opinions. ;)
