### ISSUE TITLE
Default view for shifts

### ISSUE THREAD

**Issue by spel-oe** [engelsystem/engelsystem#693]
is there any possibility to view all shifts by default when entering the shifts page?
At the moment the default date and the roomes preselected don't show me anything,
makes it a bit diffcult for new angles...

edit:
only occurs if arrival or depature date are set odd

**Comment by chriskbach** [comment]
@spel-oe 
what exactly do you mean with arrival/departure date are set odd?

I am facing the same problem. We are using the system for a single day event, and I was not planning to use the arrive or depart feature. so I have set the autoarrive option and disabled the planned arrival option. Now the user has an arrive date equal to sign-up date and is arrived. When I go to the shifts view, I see nothing by default.

How could I change that?

**Comment by msquare** [comment]
The selected default day is now the first day with existing shifts when you open the shifts view before the first shifts started.

**Comment by spel-oe** [comment]
@msquare big thanks!
