### ISSUE TITLE
Provide event specific time zone via the shifts-json-export API

### ISSUE THREAD

**Issue by johnjohndoe** [engelsystem/engelsystem#695]
Not sure if you noticed my comment initially posted on #689. I now move it here so you can handle it as a separate issue.

---

This is a follow-up of adding the `timezone` field to the response of the shifts-json-export API in b540ac93856065ce6e145930b6611e0a0946d646.

I created a couple of test shifts in the staging system both for the Camp 2019 time range (08/2019) and the 36C3 (12/2019). Here are two examples - first a Camp shift at 22.08.2019:

``` json
{
    "Comment": "",
    "Name": "Baikonur",
    "RID": 14,
    "SID": 585,
    "TID": 10,
    "UID": 32,
    "URL": null,
    "created_at_timestamp": 1565979719,
    "created_by_user_id": 32,
    "description": "Baikonur (kasachisc...",
    "edited_at_timestamp": 1567367727,
    "edited_by_user_id": 32,
    "end": 1566435600,
    "freeloaded": 0,
    "id": 42,
    "map_url": "https://openstreetmap.org",
    "name": "Sticker sammeln",
    "shifttype_id": 6,
    "start": 1566434700,
    "timezone": "+01:00",
    "title": "Tag 2: Notebook bekleben bis 03:00"
}
```

Then one for 36C3 at 27.12.2019:

``` json
{
    "Comment": "",
    "Name": "Kourou",
    "RID": 13,
    "SID": 627,
    "TID": 6,
    "UID": 32,
    "URL": null,
    "created_at_timestamp": 1575838846,
    "created_by_user_id": 32,
    "description": null,
    "edited_at_timestamp": 1575838846,
    "edited_by_user_id": null,
    "end": 1577440800,
    "freeloaded": 0,
    "id": 54,
    "map_url": null,
    "name": "Sticker sammeln",
    "shifttype_id": 6,
    "start": 1577437200,
    "timezone": "+01:00",
    "title": "36C3 Sticker sammeln 10-11"
}
```

I noticed that for both shifts the `timezone` is set to `+01:00`. The Camp however was before 27.10.2019 when [Germany changed to winter time](https://www.timechange.info/germany-2019/), `+02:00`. It became apparent because I am currently testing with the Camp 2019 schedule and shifts in the same time range.
To my understand each event needs to "deliver" its original time zone offset aka. the time zone offset which was valid when the event took place. I suppose the `+01:00` is returned for Camp shifts because that is the current time zone offset on the server as of today.
Can you please change this?

# Related

- [Issue #689: Provide time zone offset via the shifts-json-export API](https://github.com/engelsystem/engelsystem/issues/689)
- [Commit: Add timezone to shifts JSON](https://github.com/engelsystem/engelsystem/commit/b540ac93856065ce6e145930b6611e0a0946d646)

**Comment by MyIgel** [comment]
The time zone is the one configured for the engelsystem's config file and thus used on the database session/connection.

For what do you want to use the field? I can also export the "real" timezone string as it is configured in the engelsystem like `Europe/Berlin` (maybe as a header)?

**Comment by johnjohndoe** [comment]
I am using the time zone offset when I parse the timestamps in the response. In the mentioned scenario where I test shifts of the Camp 2019 a typical session has the following time stamp:

``` xml
<date>2019-08-21T11:00:00+02:00</date>
```

This makes sense to me because back in August there was summer time - so the time zone offset was `+02:00`.

The shifts response on the other hand currently specifies `+01:00` for all entries regardless of their timestamps.
Please let me know if this clarifies my concern.

**Comment by MyIgel** [comment]
You are right, that info was :hankey: -> i'll replace it with the more usefull `event_timezone` string (`Europe/Berlin` for example) and include preformatted `start_date` and `end_date`  fields which are formatted as RFC3339 strings of the format (`Y-m-d\TH:i:sP`) so for example 10:00 is `2021-10-30T10:00:00+02:00` and `2021-10-31T10:00:00+01:00`.

The fix will be deployed in the near future for the rC3 ^^

**Comment by johnjohndoe** [comment]
Thank you. Please let me know when the changes are live in the staging installation. I like to test them with [my code](https://github.com/johnjohndoe/engelsystem) to see if I have to adapt something.

**Comment by MyIgel** [comment]
You will have to replace the useless `timeZoneOffset` with an ionterpretation of the `event_timezone` value and can use the `start_date` and `end_date` values.
It will look like:
```json
[
  {
    "id": 13,
    "name": "Schichttyp1",
    "map_url": null,
    "description": "",
    "created_at": "2021-10-04 02:08:32",
    "updated_at": "2021-10-04 02:08:32",
    "Name": "Testraum",
    "shifttype_id": 4,
    "SID": 679,
    "TID": 4,
    "UID": 6,
    "freeloaded": 0,
    "Comment": "",
    "title": "Timezone UTC+2",
    "start": 1635580800,
    "end": 1635588000,
    "RID": 1,
    "URL": null,
    "created_by_user_id": 1,
    "created_at_timestamp": 1639048202,
    "edited_by_user_id": null,
    "edited_at_timestamp": 1639048202,
    "event_timezone": "Europe/Berlin",
    "start_date": "2021-10-30T10:00:00+02:00",
    "end_date": "2021-10-30T12:00:00+02:00"
  },
  {
    "id": 14,
    "name": "Schichttyp1",
    "map_url": null,
    "description": "",
    "created_at": "2021-10-04 02:08:32",
    "updated_at": "2021-10-04 02:08:32",
    "Name": "Testraum",
    "shifttype_id": 4,
    "SID": 680,
    "TID": 4,
    "UID": 6,
    "freeloaded": 0,
    "Comment": "",
    "title": "Timezone UTC+1",
    "start": 1635670800,
    "end": 1635678000,
    "RID": 1,
    "URL": null,
    "created_by_user_id": 1,
    "created_at_timestamp": 1639048244,
    "edited_by_user_id": 1,
    "edited_at_timestamp": 1639048314,
    "event_timezone": "Europe/Berlin",
    "start_date": "2021-10-31T10:00:00+01:00",
    "end_date": "2021-10-31T12:00:00+01:00"
  }
]
```

**Comment by johnjohndoe** [comment]
I appreciate that you are adding the `event_timezone` property. I [currently parse](https://github.com/johnjohndoe/engelsystem/blob/v.5.3.0/engelsystem-base/src/main/kotlin/info/metadude/kotlin/library/engelsystem/models/Shift.kt#L76-L80) the `timezone` property. Therefore, it would be valuable if you could first only **deprecate** the `timezone` property, **without removing** it. Otherwise my parse breaks and app being published using this version of the parser.

**Comment by MyIgel** [comment]
Fair enough, its back again and will be removed eventually sometimes:tm: ^^
```json
[
  {
    "id": 13,
    "name": "Schichttyp1",
    "map_url": null,
    "description": "",
    "created_at": "2021-10-04 02:08:32",
    "updated_at": "2021-10-04 02:08:32",
    "Name": "Testraum",
    "shifttype_id": 4,
    "SID": 679,
    "TID": 4,
    "UID": 6,
    "freeloaded": 0,
    "Comment": "",
    "title": "Timezone UTC+2",
    "start": 1635580800,
    "end": 1635588000,
    "RID": 1,
    "URL": null,
    "created_by_user_id": 1,
    "created_at_timestamp": 1639048202,
    "edited_by_user_id": null,
    "edited_at_timestamp": 1639048202,
    "timezone": "+01:00",
    "event_timezone": "Europe/Berlin",
    "start_date": "2021-10-30T10:00:00+02:00",
    "end_date": "2021-10-30T12:00:00+02:00"
  },
  {
    "id": 14,
    "name": "Schichttyp1",
    "map_url": null,
    "description": "",
    "created_at": "2021-10-04 02:08:32",
    "updated_at": "2021-10-04 02:08:32",
    "Name": "Testraum",
    "shifttype_id": 4,
    "SID": 680,
    "TID": 4,
    "UID": 6,
    "freeloaded": 0,
    "Comment": "",
    "title": "Timezone UTC+1",
    "start": 1635670800,
    "end": 1635678000,
    "RID": 1,
    "URL": null,
    "created_by_user_id": 1,
    "created_at_timestamp": 1639048244,
    "edited_by_user_id": 1,
    "edited_at_timestamp": 1639048314,
    "timezone": "+01:00",
    "event_timezone": "Europe/Berlin",
    "start_date": "2021-10-31T10:00:00+01:00",
    "end_date": "2021-10-31T12:00:00+01:00"
  }
]
```

**Comment by msquare** [comment]
The change is now deployed on staging and also on live.

**Comment by MyIgel** [comment]
So you can also test it at `https://engelsystem.rc3.world/shifts-json-export?key=[yourpersonalapikey]` ^^

**Comment by johnjohndoe** [comment]
LGTM: https://github.com/johnjohndoe/engelsystem/pull/8 :smile:

**Comment by johnjohndoe** [comment]
Thank you.

**Comment by johnjohndoe** [comment]
@msquare, @MyIgel which release does contain this change? Can I see from the login page which version an instance uses?

**Comment by MyIgel** [comment]
Hi @johnjohndoe, it should be part of [v3.3.0](https://github.com/engelsystem/engelsystem/releases/tag/v3.3.0) :)
The Engelsystem shows its version on the `/credits` page when a release is used.

Btw, the Engelsystem is almost ready for some kind of useable API -> i would love to have some input what would be useful for you to have in there (which endpoints with what data) :)

**Comment by johnjohndoe** [comment]
@MyIgel thanks. I checked https://staging.engelsystem.de/credits but it seems not to be deployed/activated.

Where would you like to receive input for API endpoints?

**Comment by MyIgel** [comment]
@johnjohndoe the staging system is deployed at `/test` and indeed uses git and thus i can't easily get some version information ^^

If you want you can create an issue for the requirements and eventually with suggestions what would fit how and eventually why :)

**Comment by johnjohndoe** [comment]
You could display the hash of the Git commit as a reference there.

**Comment by MyIgel** [comment]
The problem there is that there is not one file that says "this is the latest commit" -> i have to parse `.git/logs/HEAD` so that i don't have to run git commands which i am avoiding till now :D

**Comment by johnjohndoe** [comment]
Yes. I do this when I build the Android app via Gradle: https://github.com/EventFahrplan/EventFahrplan/blob/master/app/build.gradle#L241

**Comment by MyIgel** [comment]
Thats during build time (same as the engelsystem does it for the /credits version) -> the staging system is drectly using a git checkout and thus has no build pipeline before it

**Comment by MyIgel** [comment]
I added HEAD parsing in #1103 ^^
