### ISSUE TITLE
The ability to add the  General Angel Meeting as well to "my shifts"

### ISSUE THREAD

**Issue by dervitti** [engelsystem/engelsystem#703]
How about adding the General Angel Meeting to "my Shifts" so 
- heaven can plan the rush
- angels can meet in the "shift"
- my General Angel meeting would be present in ICAL or JSON ?

**Comment by MyIgel** [comment]
Thats an issue for the heaven and can't be solved in the angelsystem in general so it would be better to ask that in heaven or write them an email at the event ;)
