### ISSUE TITLE
Arrived Angels List should be a list of arrived angels

### ISSUE THREAD

**Issue by Wiiilmaa** [engelsystem/engelsystem#704]
The Arrived Angels List should list arrived angels. It currently shows a list of angels including a lot of angels not having arrived yet. I was told, that there is a purpose of this list it fulfills perfectly, it's only its name that is missleading.
So the perfect fix would be to create an Arrived Angels List for the many uses where only arrived angels are of interest (for example giving out vouchers) AND rename the current list to a name describing what it is for.

**Comment by MichiK** [comment]
The purpose of the admin_arrive view is to show a list of all angels and allow the user to mark them as arrived/not arrived with one click. The access to this view can be controlled individually via group rights and that is what allows us to have Welcome Angels who can only mark angels as arrived but not e.g. edit their profile information or do other administrative stuff like signing up other angels for shifts or create shifts.

**Comment by MyIgel** [comment]
Fixed with #780 (translation: less misleading admin_arrive translation)
