### ISSUE TITLE
Allow emoji as private message text

### ISSUE THREAD

**Issue by eliasgruenewald** [engelsystem/engelsystem#706]
When sending a 🍕emoji as part of a private message, there will be the following error:
```
Transmitting was terminated with an Error.
```

https://engelsystem.de/36c3/user-messages

**Comment by MyIgel** [comment]
Thats because MySQL implementation of UTF-8 is broken, the tables char set need to be changed to `utf8mb4`...

I fixed that, PR will be available soon

**Comment by eliasgruenewald** [comment]
Thanks!
