### ISSUE TITLE
New User-Rights-Group: Food-Voucher-Angel

### ISSUE THREAD

**Issue by 0xErnie** [engelsystem/engelsystem#708]
To spare the angels the long way to the heaven before dinner, lunch or breakfast, we created a _Food Voucher Distribution Point_ at the Heaven Kitchen.

Because only Shift Coordinators can edit vouchers, we assign a Shift Coordinator and a Trainee for this.

It would be nice if we could give this task to angels who are not Shift Coordinators.

**Comment by xuwhite** [comment]
I think that is a very good idea. MyIgel should implement this before the next inperson event!
