### ISSUE TITLE
Needs favicon

### ISSUE THREAD

**Issue by rugk** [engelsystem/engelsystem#714]
The website has no favicon… :cry: 

Maybe you can just use the same icon you always use for angels?
Or you just use some variant/image of the :angel: emoji.

I could pick this up, if you tell me which favicon/image to choose. (preferably SVG)

**Comment by MyIgel** [comment]
The angel icon is available as `resources/assets/icons/angel.svg`, feel free to use that :)

**Comment by MyIgel** [comment]
Implemented in b842466b3a842652662a0b354752bf5973c2b0cc
