### ISSUE TITLE
Sum of hours does not include nightshifts

### ISSUE THREAD

**Issue by rugk** [engelsystem/engelsystem#715]
It shows you only your planned hours ("sum of hours") without double-counting nightshifts…

Whereas the "T-Shirt Score™" hours do count nightshifts correctly.

IMHO this is bad and it should always count your nightshifts in all scores (only maybe explicitly listing X hours + Y hours nightshift).

**Comment by MrGamy** [comment]
Nightshifts are only ever double-counted for the T-Shirt Score™, for all other Counters (e.g. vouchers) they're treated as normal hours - which is by design.

**Comment by rugk** [comment]
Okay, for vouchers this may make sense, however, when you are planning to get a T-Shirt and want to estimate the hours you need, you have no indicator to do so.
You can only calculate it manually, which is rather awkward and inconvenient, as it would be an easy job for such an application.

So this is more a usability/UX error here then.

**Comment by rugk** [comment]
Also for me it is now not clear whether the hours are double-counted also for getting a voucher next year? I.e. did "e.g. vouchers" only mean meal vouchers in Engelküche or also next year vouchers?

**Comment by MyIgel** [comment]
Yeah, thats indeed a wording problem -> Improvements are welcome ;)

**Comment by gnomus** [comment]
Maybe one could add a
T-Shirt Score™ and a Voucher Score™ in Addition to the Hours Worked Score™

**Comment by rugk** [comment]
Yeah, that would possibly also solve https://github.com/engelsystem/engelsystem/issues/718 if done properly. :smiley:
