### ISSUE TITLE
Installation problems on uberspace

### ISSUE THREAD

**Issue by chriskbach** [engelsystem/engelsystem#722]
Hi everyone,

I am trying to install the engelsystem on my [uberspace 7](https://uberspace.de), it seems to work kind of, but there seems to be no theme, at least the website looks very ugly, see [this screenshot](https://imgur.com/a/Pv2CdCt).

It did a git clone to my server, 
ran composer install in $htmlroot$/engelsystem/,
created a mysql database for the engelsystem,
copied the config and entered the credentials for the database,
logged in as admin and changed the password.

Neither step produced any errors, also the logs show no errors.

unfortunately there is very little documentation available, so I am hoping we can sort out the issue here. 
thanks

chriskbach

**Comment by msquare** [comment]
Hi,
when you clone the repo you also need to build the static assets, see README.
You could also download the zip from the releases, which contains everything prebuild.

Hope this works for you.

**Comment by chriskbach** [comment]
thanks that worked!
