### ISSUE TITLE
Inconsistent date formatting with german language settings

### ISSUE THREAD

**Issue by chriskbach** [engelsystem/engelsystem#723]
Language settings unfortunately do not affect the format of dates in all views.

Event dates are shown as  DD.MM.YYYY in the footer and on the login page. The dates of news, or in the shift view are all shown as YYYY-MM-DD. For "normal" people this can be confusing.

I found no settings in the config.php or in the language file. Is this something that could be changed easily somewhere in PHP just for the view?

I see dates being handled in many places in the scripts. Unfortunately my PHP knowledge is very limited and without an overview of the project, I got lost immediately. It would be highly appreciated, if someone with enough overview could tell me if this is possible with a small change in the code or if this requires change too many functions in the code.

chriskbach

**Comment by msquare** [comment]
Fixing the news page is easy. Fixing the shifts filter is a bit more complicated.

**Comment by MyIgel** [comment]
This should be "just" searching for the `'Y-m-d'` (and similar) formatting options through the code base and wrapping them in `__([...])` to get translated (in in the best case verifying that a translation exists)

**Comment by msquare** [comment]
Nope, this will break the datepickers.

**Comment by MyIgel** [comment]
Thats right and needs to be configured in the js lib but the other occurrences could be fixed that way

**Comment by chriskbach** [comment]
Translating the ticks in the shifts view table required me to remove the linebreak, see here:
chriskbach/engelsystem@bdca96c3ae9b94254ff3971e11b05a2feefc926d

for me this works, somehow the linebreak is still present in the view. If you have any hints for me how to do this properly, I can try and then create a pull-request here.

**Comment by msquare** [comment]
I guess the divs are to small to display d-m H:I in one row, so the browser breaks the line.
What about  __('d-m') . '<br>' . __('H:i')?

**Comment by chriskbach** [comment]
thank you, I made the changes and created a pull request, works as proposed by you, except a space was needed for the line break to work

**Comment by MyIgel** [comment]
I guess this issue can be closed now?

**Comment by johnjohndoe** [comment]
:thinking: Just to double check: Is it correct that the date format in the JSON export stays the same?

**Comment by msquare** [comment]
Yes.
