### ISSUE TITLE
Mysql Socket

### ISSUE THREAD

**Issue by Kloenk** [engelsystem/engelsystem#724]
I'm trying to make a nixos module for engelsystem, but unfortionally im unable to find out how to use a unix socket for database connection, wich is needed for provisioning. Is there a way to use a unix socket witch trust auth for the engelsystem?

The open pr on nixos in [#82753](https://github.com/NixOS/nixpkgs/pull/82753)

**Comment by MyIgel** [comment]
NixOS looks interesting :D

As far as I know it should be enough to add a `unix_socket` key with a path to the socket as the value to the database config entry but I haven't tested that ^^

**Comment by Kloenk** [comment]
seems to work if I also set password to ""
Thanks
