### ISSUE TITLE
Can't edit or add any types or shifts.

### ISSUE THREAD

**Issue by HansF** [engelsystem/engelsystem#732]
Dear, 
I've installed from release everything seems to work, but when I try to edit or create rooms , angel types or shifttypes, nothing seems to happen.

There's nothing in the console log, nor errors from nginx.  Rewrite rules work, but I've disabled it in the troubleshooting. Could somebody advise me please?

Thanks!

![image](https://user-images.githubusercontent.com/1503/79642236-a1f09000-819c-11ea-8048-10491920270f.png)

![image](https://user-images.githubusercontent.com/1503/79642248-b7fe5080-819c-11ea-9fe0-a9850b9573cc.png)

![image](https://user-images.githubusercontent.com/1503/79642300-090e4480-819d-11ea-87d8-c70c42225317.png)

**Comment by MyIgel** [comment]
Disabling rewrite rules is not recommended as the current angelsystem does not 100% supports that (had some bugs and broke unnoticed during a merge...).

Could you post the nginx and php log for a request that should create a resource?
Does the browser log shows any messages in its console? (usually can be accessed by pressing `F12` and then in the `Console` tab)?

**Comment by HansF** [comment]
Hey @MyIgel Thanks for your reply. I've re-enabled rewite.

Access Log: 
`141.101.105.120 - - [19/Apr/2020:23:01:07 +0000] "GET /admin-rooms?show=edit HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"`

Error log of nginx and php-fpm are **empty**, to test , I've put the logging level on info.

Console gives:
`DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map` But this seems to be something generic on every page, and not related to this issue.

**Comment by MyIgel** [comment]
The above request is a `GET` (showing the page) request and not a `POST` (send the form) -> can share that one too?

**Comment by HansF** [comment]
Thanks @MyIgel , 

There is `    'rewrite_urls'            => true,` in the config, yet is keeps putting get paratmeters in the url, don't know is this is as it should?

Anyway, there's no post since if I click on any of the buttons, I don't seem to post a form but get a url with parameters: 
![image](https://user-images.githubusercontent.com/1503/79702685-00a23080-82a7-11ea-9156-4ffe0751f139.png)

Here's the log:

172.69.54.103 - - [19/Apr/2020:23:30:18 +0000] "GET /admin-rooms?show=edit&id=1 HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:26 +0000] "GET /admin-rooms?show=delete&id=1 HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms?show=edit&id=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:30 +0000] "GET /rooms?action=view&room_id=1 HTTP/1.1" 302 5 "https://angels.roguerope.be/admin-rooms?show=delete&id=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:30 +0000] "GET /admin-rooms HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms?show=delete&id=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:41 +0000] "GET /rooms?action=view&room_id=1 HTTP/1.1" 302 5 "https://angels.roguerope.be/admin-rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:41 +0000] "GET /admin-rooms HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:30:49 +0000] "GET /admin-rooms?show=edit HTTP/1.1" 200 2057 "https://angels.roguerope.be/admin-rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:31:07 +0000] "GET /user-settings HTTP/1.1" 200 3030 "https://angels.roguerope.be/admin-rooms?show=edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
172.69.54.103 - - [19/Apr/2020:23:31:19 +0000] "POST /user-settings HTTP/1.1" 302 5 "https://angels.roguerope.be/user-settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

The last request is a post, when editing some of my user preferences, because I wanted to to show that that works.

**Comment by MyIgel** [comment]
Well, there should be some POST requests then... Maybe something infront of the engelsystem is blocking/caching stuff?

After having a closer look at your application I can see that you are using cloudflare and thus probably request caching, could you disable that and some other optimizations first and check if that works (what I would suspect)?

**Comment by HansF** [comment]
I moved it away from cloudflare and disabled https, if you connect now you have direct connection to the nginx. 
Nothing changes though.

**Comment by MyIgel** [comment]
So in that case it should be something about the angelsystem being unable to interpret the url parameters..

Can you share (parts of) the nginx config?
And does it contain somthing like `try_files $uri $uri/ /index.php?$args;` (esp. the `$args` part is the important one here)?

**Comment by HansF** [comment]
Hey, I posted [my nginx rewrite](https://github.com/engelsystem/engelsystem/issues/732#issuecomment-616241315) a few days ago. 

Thanks for your support, your line worked perfectly! 
Have a nice dat.
