### ISSUE TITLE
Public Dashboard Filters

### ISSUE THREAD

**Issue by cyriax0** [engelsystem/engelsystem#759]
### What ###
A button "use Filters for Public Dasboard" on the Shifts Page.
The button generates a link similar to the /user_shifts parameters for the dashboard (omitting time).
The Dashboard shows open shifts and statistics only for the selected rooms and/or angeltypes.

### Why ###
Teams might use the dashboard filtering only their vacancies. This can be locally (like a display in Hall 1 showing all open Hall 1 Shifts or the local Hackspace at rC3), by angeltype/team (e.g. CERT Medical, CERT Technical, CERT Dispatcher), or even by shifttype (show all open Access Control shifts).

**Comment by MyIgel** [comment]
Shift types are not filtered by the normal shift display page so i would omit it for the dashboard
