### ISSUE TITLE
Add optional description to shift

### ISSUE THREAD

**Issue by maulwuff** [engelsystem/engelsystem#769]
For our purpose on a school event it would be beneficial to have an extra field with description text, when adding a new shift.
Currently a description is only possible on the shift type. This makes it hard to describe what to do in a shift, on not so repetitive tasks. It doesn't make sense for us to add various shift types with corresponding descriptions to only use them once afterwards. :-)

**Comment by msquare** [comment]
- [ ] add new markdown textarea "description" to shift creation and editing pages
- [ ] add hint, that this description is for single shifts and that otherwise the description in shift type should be used
- [ ] append the description to the description from the shift type on the shift view

**Comment by xuwhite** [comment]
I'll try to implement it
