### ISSUE TITLE
Buttons "Registrieren" and "Team-/Aufgabenbeschreibung" without function

### ISSUE THREAD

**Issue by probonopd** [engelsystem/engelsystem#785]
Buttons "Registrieren" and "Team-/Aufgabenbeschreibung" are without function on https://engelsystem.de/rc3/login

![image](https://user-images.githubusercontent.com/2480569/103154751-e1df2c80-4799-11eb-84fa-e24d007b030f.png)

Chromium Version 84.0

**Comment by MyIgel** [comment]
Interesting as they are "just" normal links (which "work for me"), do you have some interesting script blockers installed that could interfere here?

**Comment by probonopd** [comment]
uBlock Origin. Now that you are saying it. Sorry for the noise!
