### ISSUE TITLE
Engelsystem Docker Base table or view not found

### ISSUE THREAD

**Issue by PaulGoldschmidt** [engelsystem/engelsystem#802]
Hey,

I'm setting up an instance of the Engelsystem for a local event I'm currently organizing, unfortuanly I can't get the docker version of the Engelsystem to run; If I try to access the page, I only get an error (An -un-expected error occurred. A team of untrained monkeys has been dispatched to fix it.).
In the logs of the docker containers I find a lot of errors that seem to indicate a missing database:
`[error] 9#9: *1 FastCGI sent in stderr: "PHP message: Exception: Code: 42S02, Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'engelsystem.sessions' doesn't exist (SQL: select * from sessions where id = 177aba76c771965e15b7788604997b83 limit 1)`
Can anybody of you help me with this problem? I would greatly appreciate it! 

Kind regards,
Paul from Heidelberg

**Comment by msquare** [comment]
Hi,
please try to run the migrate script which sets the database up.
Something like `docker-compose exec es_php_fpm bin/migrate`.

**Comment by PaulGoldschmidt** [comment]
That seems to do the trick, perfect! I can now access the Engelsystem directly via the IP, when I try to access the site forwarded by the nginx reverse-proxy, I'm redirected to the internal IP of the service (127.0.0.1:5000) and thus the connection fails. Is there a recommended reverse proxy config for the Engelsystem?

Thank you so much with your fast help and great week,
Paul

**Comment by PaulGoldschmidt** [comment]
Nevermind, I figured out the correct configuration (somehow, I put the proxy pass config in the wrong section.
Thanks again for your work, I will happily report after the event how everything went.

Greetings,
Paul
