### ISSUE TITLE
Manually install with nginx, rooting without .htaccess?

### ISSUE THREAD

**Issue by peetCreative** [engelsystem/engelsystem#819]
Hey,
I want to setup a engelsystem on my server which already runs nginx webserver.
So cloned the git to my `/var/www/engelsystem` and made sure webserver has access rights.
I setup following config for nginx:

```
server {
 	root /var/www/engelsystem/public;
 	index index.php;
     server_name engel.myserver.de; # managed by Certbot
 	location / {
		try_files $uri $uri/ /index.php?$args;
 	}
 
 	location ~ \.php$ {
 		include snippets/fastcgi-php.conf;
 		fastcgi_pass unix:/run/php/php7.3-fpm.sock;
 	}
      listen [::]:443 ssl; 
      listen 443 ssl;
#more ssl stuff
...
 }
```

I know that the problem is, that engelsystem is designed to do routing using the .htaccess file, which is not possible with nginx. However the Requirements says that it is possible to run engelsystem with nginx. Sadly I'm not too much into webdevelopment and deployment, are there any suggestions how to solve this? Is it maybe a good workaround solution to run nginx and apache in parallel, ontop or so?
Thank you!

**Comment by msquare** [comment]
Hi,

just take a look on the nginx config file we use for our docker setup:
https://github.com/engelsystem/engelsystem/blob/main/docker/nginx/nginx.conf

**Comment by msquare** [comment]
Hey @peetCreative could you resolve the problem?

**Comment by peetCreative** [comment]
I was not able setup my instance, but I don't have the need anymore. So I would close the issue for now.
