### ISSUE TITLE
Password recovery not working

### ISSUE THREAD

**Issue by neumantm** [engelsystem/engelsystem#820]
On current master, when trying to reset my password, i get a 500 error.
There is also a PHP exception in the stderr of the php runtime (see [error.log](https://github.com/engelsystem/engelsystem/files/6794194/error.log)).
I think this bug was introduced here: https://github.com/engelsystem/engelsystem/commit/149155fbda6242f13dd8880126801a2c85551eea#diff-5ddf40f8e6d38dc891e2004e3aaa4b0256a0aae6c2b9fbdc99b685a238be0938R64

**Comment by MyIgel** [comment]
Thx for your detailed bug report!
That was definitely a fuckup that should be caught using some kind of regression/integration tests that we still need to implement :(

4ff44d141c6430ea200da10a521dcf14aebfd454 should fix that problem as it makes the translator more robust.
