### ISSUE TITLE
Applying config in Engelsystem / Docker

### ISSUE THREAD

**Issue by PaulGoldschmidt** [engelsystem/engelsystem#825]
Hey,

I'm currently working with an instance on Engelsystem in Docker and trying to apply settings from the config.php.
Is there an example config-file or shoud I rename the config.default.php to config.php and change the value in there?
Do I have to recreate the docker-images so that the changes are being applied?

Kind regards and thanks a lot,
Paul

**Comment by MyIgel** [comment]
Hi, as stated in the readme, the config file can be copied. The recommended way is to just overwrite the values that you want to change so you don't need to update settings as often.

If you are using docker you can also have a look if you can overwrite the settings that you want to change via environment variables.
The env var changes are the more flexible as they are read at the container start.

If you want to have a config file its recommended to mount one inside the container so you don't have to rebuild it on every change.

**Comment by MyIgel** [comment]
I how that explanation helped you. If not or if you have some questions feel free to reopen the Issue :)
