### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by menkey2k** [engelsystem/engelsystem#830]
Hello everyone, I have now been able to install the system after endless back and forth. Now I'm a bit irritated, because it probably doesn't quite work out that way. The pages are displayed to me a bit strangely.
![image](https://user-images.githubusercontent.com/89402232/130466660-709dbb41-2ce2-453e-99ad-92e5e59ae436.png)

**Comment by MyIgel** [comment]
Hi, sorry for the late reply. That looks like you have not build the frontend resources (yarn build)
How do you installed the Engelsystem and which version?

**Comment by MyIgel** [comment]
Hi, if you still have the problem, feel free to reopen the issue! :)
