### ISSUE TITLE
No countdown, when in shift

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#832]
In the top right used to be a countdown to my next shift and for my actual running shift. On a docker deploy version 3.2 that was missing.

**Comment by MyIgel** [comment]
The current master has the counter, under which conditions do you encountered that problem?

Next shift:
![image](https://user-images.githubusercontent.com/1448057/135777921-70c34859-f5ed-4d11-9d1a-97b9393316d2.png)

Running Shift:
![image](https://user-images.githubusercontent.com/1448057/135777906-abcda0eb-11a1-40b7-8f6b-9f3af34b4349.png)
