### ISSUE TITLE
Error while docker-compose deployment

### ISSUE THREAD

**Issue by Lukas2112** [engelsystem/engelsystem#841]
![engelsystem-2](https://user-images.githubusercontent.com/47597136/136676114-2967a567-83d9-41ec-9d28-cb9ec2c8c415.png)
![engelsystem-1](https://user-images.githubusercontent.com/47597136/136676115-705eb99d-0d2f-4912-bebc-b455cfcac343.png)

**Comment by Lukas2112** [comment]
Nevermind. I'm sorry for the impropriety.

**Comment by MyIgel** [comment]
No problem (and for anyone wondering: The migrations where not run and thus the sessions table is missing) :+1:
