### ISSUE TITLE
Include explanation of T-shirt types when signing up

### ISSUE THREAD

**Issue by jbethune** [engelsystem/engelsystem#859]
New angels have to pick a T-shirt type. I suggest to include a help link to this page:
https://geekfeminism.fandom.com/wiki/T-shirts

Because not everyone knows what straight-cut and fitted-cut are.

**Comment by MyIgel** [comment]
Thats definitely a great Idea end easy to implement! Do you know any other pages (esp. eventually also german ones) that also summarize it? As this one is especially more US centric as it uses Inches which are imho not that depictive?

To implement it (esp. as it might hold by itself a bit more information / links) I would recommend eventually using some kind of popup?

**Comment by jbethune** [comment]
I don't know of any other pages that explain it that well. I also tried searching for an explanation and this was the first one that actually made sense in this context. I am not aware of any german websites on the topic.

For context: The URL of this page is https://engelsystem.rc3.world/register

![register_angel](https://user-images.githubusercontent.com/3159699/146429818-7eb12c20-71c9-4de6-aa78-b1abe2cad6f3.png)

This is where the dropdown with the T-Shirt sizes is. Maybe there could be a blue questionmark right next to the blue warning sign that links to the the explanation? But the help symbol could also be on the right site of the dropdown menu.

**Comment by xuwhite** [comment]
Text suggestion:
A straight-cut shirt has wide shoulders and a body which is almost square. The side seams, descending from the armpit to the hem, are absolutely straight and perpendicular to the hem. The sleeves are usually cut loose, and are quite long when measured from the shoulder seam to the cuff.

A fitted-cut t-shirt has a curved side seam which comes in at the waist and goes out at the upper and lower ends, to make room for curvy hips and bust/chest areas. The shoulders are also cut narrower, and the sleeves are shorter and more fitted relative to a straight-cut shirt. The neckline may be slightly scooped in front.

Fitted t-shirts are generally made in a narrower range of sizes than straight-cut shirts. 

Normally a fitted-cut shirts are smaller then same size straight-cut shirts, and sizes differ between brands.

**Comment by xuwhite** [comment]
a shorter version could be: 
A straight-cut shirt has wide shoulders and a body which is almost square. 
A fitted-cut t-shirt has a curved side seam which comes in at the waist and goes out at the upper and lower ends. 
Normally a fitted-cut shirts are smaller then same size straight-cut shirts, and sizes differ between brands.

**Comment by jbethune** [comment]
@xuwhite I think it is fine to add this information, but I think showing/linking to actual pictures would help a lot more.

**Comment by MyIgel** [comment]
@xuwhite I like the general idea to have an info text that explains the general case of shirts (please check the sizes etc).
But in addition it would be great to have a small text under the select which gets displayed when a "shirt size info" link is set in the config
