### ISSUE TITLE
[Expansion of interoperability with other FLOSS projects] Connection to FLOSS financial systems for billing 

### ISSUE THREAD

**Issue by Lukas2112** [engelsystem/engelsystem#861]
The idea came to me in the context of Issue #849 .

In this way, the association or organisation that uses engelsystem could also directly handle the remuneration for the helpers (e.g. polling clerk).

**Comment by MyIgel** [comment]
That integration could be done via an external application (and after an API is implemented) but is not really in the scope of this project.
