### ISSUE TITLE
Imports should be disabled/deleted

### ISSUE THREAD

**Issue by jwacalex** [engelsystem/engelsystem#867]
Currently, there is no possibility to remove an import (e.g. if the fahrplan is merged). There should be an option to deactivate or remove those imports.

**Comment by MyIgel** [comment]
The question here: should the connected shifts also be deleted? Or just detached?

**Comment by Lukas2112** [comment]
Would say that detached, would be the way to go?

**Comment by MyIgel** [comment]
More like: Detach those who are already worked on and delete newer ones
