### ISSUE TITLE
Extension: Tool can be used to document working time via check-in and check-out? 

### ISSUE THREAD

**Issue by Lukas2112** [engelsystem/engelsystem#875]
Would it be in the spirit of the project that it could be expanded to the extent that it could also be used to document working hours?

A concrete use case could be with municipal city councils, for example, if you use it in the area of "election workers" for the coordination of these.

Another use case could be in child and youth work. In Germany, there is a youth leader card (JuLeiCa) and for this you have to indicate how long this measure(s) lasted, for example, if you do internal further training in a youth association.

Could then be combined / completed with the extension to HR systems, maybe.

**Comment by Lukas2112** [comment]
Admitted: My thought sounds abstract and perhaps very far-fetched but could perhaps help many and facilitate the workflow. 

I could imagine OpenPetra or SuiteCRM as HR systems.

**Comment by MyIgel** [comment]
In theory it could, but it would be better to do this via an external page and just sync the data to the engelsystem (by for exampel saving the check in time and on check out create a shift for the user in the background and assigning them)
