### ISSUE TITLE
Session-Table not in install.sql?

### ISSUE THREAD

**Issue by lawnmower425** [engelsystem/engelsystem#884]
Hi,

just wanted to make engelsystem run as a test on a xampp-environment.

1. There is no session-table in the install.sql - i created it by guessing that just the id-column is needed - why isn't it in the install?
2. Right after logging in first time as admin I get "The provided CSRF token is invalid or has expired" and have no chance to fix this - any hints for this?

Thank you!

René

**Comment by lawnmower425** [comment]
Hello?

We want to use it for the organization of our Ukraine-Refugees-Support in my town.

I would appreciate some information on this :)

**Comment by msquare** [comment]
Hi, where did you get your install files? If you use the latest release: https://github.com/engelsystem/engelsystem/releases/tag/v3.2.0
There is a download link for the install-v3.2.0.sql file. The session table is included there, starting at line 730.
Can you please check?

**Comment by sirexeclp** [comment]
Migrating the Database (as noted in the README) fixed it for me
After starting the docker containers run:

    cd docker
    docker-compose exec es_php_fpm bin/migrate

**Comment by msquare** [comment]
No problem, I'm glad it worked.
