### ISSUE TITLE
Unable to set "Planned date of departure"

### ISSUE THREAD

**Issue by Volker-Weissmann** [engelsystem/engelsystem#886]
Hello,

If I go to https://troll.gulas.ch/user-settings and select a date for "Planned date of departure", it shows the selected date in the textfield.
But once I hit "Save", It shows "Settings saved" and resets the "Planned date of departure" to 2022-05-18. Changing the fields "DECT", "Mobile", "E-Mail" works fine. 

Firefox 98.0.1

**Comment by MyIgel** [comment]
Afaik it sets it correctly but the cal select js does some magic which then resets it -> would need some debugging ans poking around

**Comment by MyIgel** [comment]
I'v heard that @marudor wants to have a look at it and eventually remove the calendar js completely which would be a great idea esp. as it has some interesting development progress :upside_down_face:
