### ISSUE TITLE
Undocumented / not working frontend feature?

### ISSUE THREAD

**Issue by lawnmower425** [engelsystem/engelsystem#892]
Hi,

thanks for your support last time. We set up our Engelsystem for our region, now we have a dancing warning indicator next to our nicknames on the top right of the page. (In red)

It links to an unnamed anchor on the current page (e.g. messages#) and does nothing when clicking it. Also, we do not know how to remove it.

What are the indications for that notification? 

Thank you in advance!

René

**Comment by MyIgel** [comment]
Hmm, interesting -> does it have some content? Can you add a screenshot?

**Comment by lawnmower425** [comment]
Hi,

no content, no action is performed when clicking it.

We found out that different preconditions have to be fulfilled like having a t-shirt-size, dect-number etc. Plus: it may have something todo with blocking external sources - as js is broken, too...

As it's not happening any more, I don't have a screenshot.

We can consider it fixed. Thx!

**Comment by MyIgel** [comment]
Ok, that point with not working JS explains it :D
As we are not using external resources that normally means that the JS resources are not working for some reason (not build / server config etc.). Normally a klick in the button opens a message and as its red it means that either the user was freeloaded, has not arrvied, has configured an invalid tshirt size or arrived and no dect configured.

So eventually you fixed the resources loading and it worked ^^
If not: You can use you browsers development tools and their network/console tab to find out why they are being blocked.

**Comment by xuwhite** [comment]
Hat die Erklärung dein Problem gelöst?

**Comment by MyIgel** [comment]
Hi, if you have any further questions feel free to reopen the issue :)
