### ISSUE TITLE
bekomme bei der Installation error 500

### ISSUE THREAD

**Issue by akihelper** [engelsystem/engelsystem#905]
Hallo zusammen
Ich habe das system auf meinem Webspace hochgteladen und die Config angepasst
nachdem ich die Seite aufrufen wollte, bekomme ich immer den Fehler 500 
In der Errorlog steht:
`AH01071: Got error 'PHP message: PHP Fatal error:  Trait 'Illuminate\\Support\\Traits\\ForwardsCalls' not found in /home/users/demo/www/helferanmeldung/release/vendor/illuminate/database/Eloquent/Model.php on line 23'`

**Comment by MyIgel** [comment]
Hi, wie hast du das Engelsstem installiert? Also Aus dem letzten release zip file oder hast du nur das repo herunter geladen -> dann musst du die resourcen noch mit composer install nach installieren.

**Comment by akihelper** [comment]
ich habe das release zip genommen und auf meinem Webspace hochgeladen. die Datenbank angelegt und die install und update sql importiert. auf dem Webspace läuft php 8.0

**Comment by MyIgel** [comment]
Aaah, neben dem zip file liegt beim release auch noch eine install sql datei, diese muss beim Installieren importiert werden. die install und update sql dateien beinhalten nur teile des datenbank setups.

Wenn du die release install importierst sollte es klappen. Alternativ kannst du auch die migrations ausführen, die tun dann genau das selbe.

**Comment by xuwhite** [comment]
Hat es geklappt?

**Comment by akihelper** [comment]
Habe es nicht leider hinbekommen, ich habe die vermutung, das auf dem Webspace was fehlt

**Comment by MyIgel** [comment]
Hi, versuch mal die .zip des releases https://github.com/engelsystem/engelsystem/releases/tag/v3.2.0 zu verwenden, die sollte klappen

**Comment by Caeppi** [comment]
Hallo, ich hatte das gleiche Problem, es lag an der php Version.
Wenn ich zu 7.4 gehe läuft das System, gehe ich zur 8er kommt Error 500

**Comment by MyIgel** [comment]
Mittlerweile gibt es noch aktuellere Engelsystem Versionen, diese sollten auf aktuellen systemen funktionieren
