### ISSUE TITLE
Question: What is the purpose of shifttypes?

### ISSUE THREAD

**Issue by joshuabach** [engelsystem/engelsystem#907]
I'm setting up Engelsystem for our (non-chaos) event. While it is a great piece of software, I do not understand what "Shifttypes" are for:

When creating a new shift, one has to select a room and a shifttype. The information on what angeltypes (and how many) are required for the shift is either entered manually or taken from the room. Each shifttype also has an angeltype associated with it but this setting does not seem to be relevent for the shift at all.

So: What is the purpose / usecase for shifttypes and where / how, if at all, is the angeltype associated with the shifttype used?

If I missed some documentation that explains this, please point me to it.

Thanks!

**Comment by MyIgel** [comment]
The Shift Type is used to provide a description for the shifts (what to do in them) and what to do there (for example ho to operate equipment, where to be at shift start and so on).
The connection to the Angeltype is more or less irrelevant as it afaik was once supposed to be used but then not implemented so it should be removed at some point ^^

**Comment by joshuabach** [comment]
This makes sense and answers my question, thank you.

If it were possible to add multiple angeltypes (and an amount for each) to the shift types (like with rooms) it might also be useful to have the option to take the required angels for a shift from the shift type instead of the room. This would be useful when I have different types of shifts with different amounts of angels required in the same room, e.g. when less angels are required at night.
