### ISSUE TITLE
Error trying to parse /metrics

### ISSUE THREAD

**Issue by sebastius** [engelsystem/engelsystem#909]
Metrics output is missing a CR/LF at the end:

2022-05-10T20:12:41Z E! [inputs.http] Error in plugin: [url=http://angel.mch2022.org/metrics]: reading text format failed: text format parsing error in line 166: unexpected end of input stream

According to Xesxen it's this:

https://github.com/engelsystem/engelsystem/blob/main/src/Controllers/Metrics/MetricsEngine.php#L60 missing a \n or PHP_EOL at the end.

**Comment by MyIgel** [comment]
Hmm, interesting -> is there some spec about that? And which Parser are you using? Anyhow, it should not break anything so i'll add it :D

**Comment by xesxen** [comment]
```
The last line must end with a line feed character.
```
From https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details ;)
