### ISSUE TITLE
You have to be logged in to read the news.

### ISSUE THREAD

**Issue by Volker-Weissmann** [engelsystem/engelsystem#912]
If you are not logged in and go to https://troll.gulas.ch/news , it just shows
```
You are not allowed to access this page

Please log in.
```
This is kind of unnecessary. You should be able to see the news, even if you are not logged in.

**Comment by msquare** [comment]
If this default behavior is "kind of unnecessary" for your event, then just add the "news" privilege to the guest group in the admin menu for group rights.
