### ISSUE TITLE
php8 compatibilty

### ISSUE THREAD

**Issue by poelzi** [engelsystem/engelsystem#929]
There are a lot of warnings that cause the nixos tests to fail. It seems that many vendor libraries use deprecated APIs.
php74 was the only version I had sucess with, which is no removed in nixos.

With php8.1:

```
engelsystem # curl: (22) The request[   37.122254] nginx[956]: Stack trace:
engelsystem # ed URL returned [   37.126059] nginx[956]: #0 /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/composer/ClassLoader.php(444): include()
engelsystem # error: 500
engelsystem # [   37.131757] nginx[956]: #1 /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
engelsystem # [   37.139284] nginx[956]: #2 /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/vlucas/phpdotenv/src/Repository/AdapterRepository.php(5): Composer\Autoload\ClassLoader->loadClass()
engelsystem # [   37.147486] nginx[956]: #3 /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/composer/ClassLoader.php(444): include('...')
engelsystem # [   37.154319] nginx[956]: #4 /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/co
engelsystem # [   38.302655] nginx[956]: 2022/06/16 18:28:04 [error] 956#956: *15 FastCGI sent in stderr: "PHP message: Exception: Code: 0, Message: Return type of Dotenv\Repository\AbstractRepository::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice, File: vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php:147, Previous: None, Trace: [{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php","line":8,"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->"},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/ClassLoader.php","line":444,"args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php"],"function":"include"},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58k...PHP message: PHP Warning:  Uncaught Error: Object of class UnwindExit could not be converted to string in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php:8
```

More errors with 8.0

```
engelsystem # [   27.924844] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/container/Container.php on line 1271
engelsystem # [   27.937043] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/container/Container.php on line 1282
engelsystem # [   27.945755] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/container/Container.php on line 1294
engelsystem # [   27.954828] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/container/Container.php on line 1307
engelsystem # [   27.971513] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Support\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/support/Fluent.php on line 95
engelsystem # [   27.979489] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Support\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/support/Fluent.php on line 106
engelsystem # [   27.986824] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Support\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/support/Fluent.php on line 118
engelsystem # [   27.996317] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Support\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/support/Fluent.php on line 129
engelsystem # [   28.005996] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Support\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/support/Fluent.php on line 73
engelsystem # [   28.129910] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/database/Eloquent/Model.php on line 1658
engelsystem # [   28.138492] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/database/Eloquent/Model.php on line 1669
engelsystem # [   28.147458] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/database/Eloquent/Model.php on line 1681
engelsystem # [   28.157298] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/database/Eloquent/Model.php on line 1692
engelsystem # [   28.168127] engelsystem-migrate-start[1047]: Deprecated: Return type of Illuminate\Database\Eloquent\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/illuminate/database/Eloquent/Model.php on line 1203
engelsystem # [   28.266366] engelsystem-migrate-start[1047]: Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/symfony/http-foundation/ParameterBag.php on line 205
engelsystem # [   28.278017] engelsystem-migrate-start[1047]: Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/symfony/http-foundation/ParameterBag.php on line 215
engelsystem # [   28.317492] engelsystem-migrate-start[1047]: Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/symfony/http-foundation/HeaderBag.php on line 255
engelsystem # [   28.327852] engelsystem-migrate-start[1047]: Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /nix/store/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0/share/engelsystem/vendor/symfony/http-foundation/HeaderBag.php on line 265
engelsystem # [   28.358524] engelsystem-migrate-start[1047]: Exception: Code: 0, Message: Return type of Dotenv\Repository\AbstractRepository::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice, File: vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php:147, Previous: None, Trace: [{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php","line":8,"function":"errorHandler","class":"Engelsystem\\Exceptions\\Handler","type":"->","args":[8192,"Return type of Dotenv\\Repository\\AbstractRepository::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice","\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php",147]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/ClassLoader.php","line":444,"args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php"],"function":"include"},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/ClassLoader.php","line":322,"function":"Composer\\Autoload\\includeFile","args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/..\/vlucas\/phpdotenv\/src\/Repository\/AbstractRepository.php"]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AdapterRepository.php","line":5,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["Dotenv\\Repository\\AbstractRepository"]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/ClassLoader.php","line":444,"args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/AdapterRepository.php"],"function":"include"},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/ClassLoader.php","line":322,"function":"Composer\\Autoload\\includeFile","args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/composer\/..\/vlucas\/phpdotenv\/src\/Repository\/AdapterRepository.php"]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/vlucas\/phpdotenv\/src\/Repository\/RepositoryBuilder.php","line":109,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["Dotenv\\Repository\\AdapterRepository"]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/illuminate\/support\/Env.php","line":66,"function":"make","class":"Dotenv\\Repository\\RepositoryBuilder","type":"->","args":[]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/illuminate\/support\/Env.php","line":81,"function":"getRepository","class":"Illuminate\\Support\\Env","type":"::","args":[]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/vendor\/illuminate\/support\/helpers.php","line":276,"function":"get","class":"Illuminate\\Support\\Env","type":"::","args":["CI",false]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/config\/config.default.php","line":8,"function":"env","args":["CI",false]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/src\/Config\/ConfigServiceProvider.php","line":45,"args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/config\/config.default.php"],"function":"require"},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/src\/Application.php","line":68,"function":"register","class":"Engelsystem\\Config\\ConfigServiceProvider","type":"->","args":[]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/src\/Application.php","line":90,"function":"register","class":"Engelsystem\\Application","type":"->","args":[{}]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/includes\/application.php","line":17,"function":"bootstrap","class":"Engelsystem\\Application","type":"->","args":[{"providers":["Engelsystem\\Logger\\LoggerServiceProvider","Engelsystem\\Exceptions\\ExceptionsServiceProvider","Engelsystem\\Config\\ConfigServiceProvider","Engelsystem\\Helpers\\ConfigureEnvironmentServiceProvider","Engelsystem\\Http\\UrlGeneratorServiceProvider","Engelsystem\\Renderer\\RendererServiceProvider","Engelsystem\\Database\\DatabaseServiceProvider","Engelsystem\\Http\\RequestServiceProvider","Engelsystem\\Http\\SessionServiceProvider","Engelsystem\\Helpers\\Translation\\TranslationServiceProvider","Engelsystem\\Http\\ResponseServiceProvider","Engelsystem\\Http\\Psr7ServiceProvider","Engelsystem\\Helpers\\AuthenticatorServiceProvider","Engelsystem\\Renderer\\TwigServiceProvider","Engelsystem\\Middleware\\RouteDispatcherServiceProvider","Engelsystem\\Middleware\\RequestHandlerServiceProvider","Engelsystem\\Middleware\\SessionHandlerServiceProvider","Engelsystem\\Http\\Validation\\ValidationServiceProvider","Engelsystem\\Http\\RedirectServiceProvider","Engelsystem\\Helpers\\VersionServiceProvider","Engelsystem\\Mail\\MailerServiceProvider","Engelsystem\\Http\\HttpClientServiceProvider"],"middleware":["Engelsystem\\Middleware\\SendResponseHandler","Engelsystem\\Middleware\\ExceptionHandler","Engelsystem\\Middleware\\SetLocale","Engelsystem\\Middleware\\AddHeaders","Engelsystem\\Middleware\\ErrorHandler","Engelsystem\\Middleware\\VerifyCsrfToken","Engelsystem\\Middleware\\RouteDispatcher","Engelsystem\\Middleware\\SessionHandler","Engelsystem\\Middleware\\RequestHandler"]}]},{"file":"\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/bin\/migrate","line":11,"args":["\/nix\/store\/qj1qdvbhix099ljpk58km549c0sbw97x-engelsystem-3.2.0\/share\/engelsystem\/includes\/application.php"],"function":"require_once"}]

```

**Comment by MyIgel** [comment]
Which engelsystem version are you trying to use here?

**Comment by Caeppi** [comment]
Same problem, I tried to install actual Version on a shred webspace at oneblu.de
With php8.1 it came "same monkeys are on the way"
Changed php to 7.4 - working!

**Comment by MyIgel** [comment]
Hi @Caeppi, thats interesting -> which engelsystem version where you using / how did you installed it? Can you provide the corresponding error logs?

**Comment by astro** [comment]
PHP 7.4 is unsupported in NixOS 22.11 (https://github.com/NixOS/nixpkgs/pull/174555). That means the engelsystem module in NixOS is broken.

Cc: @kloenk

**Comment by Caeppi** [comment]
> Hi @Caeppi, thats interesting -> which engelsystem version where you using / how did you installed it? Can you provide the corresponding error logs?

Hello,
I have to correct my Information.
My "engelsystem" at 1blu.de (shared hosting) is working finde with php7.4 and php8.0.
When changing to php8.1, I get the error I wrote.

Because of shared webspace there is no error-log.
I can only share access.log:
79.210.175.0 - - [25/Nov/2022:16:44:12 +0100] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"
79.210.175.0 - - [25/Nov/2022:16:44:12 +0100] "GET /login HTTP/1.1" 200 1988 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"
79.210.175.0 - - [25/Nov/2022:16:44:12 +0100] "GET /assets/theme1.css HTTP/1.1" 200 25516 "http://helfer.mmc-berlin.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"
79.210.175.0 - - [25/Nov/2022:16:44:12 +0100] "GET /assets/908638513c7d287121b116464bba79d0.svg HTTP/1.1" 200 714 "http://helfer.mmc-berlin.com/assets/theme1.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"
79.210.175.0 - - [25/Nov/2022:16:44:12 +0100] "GET /assets/be810be3a3e14c682a257d6eff341fe4.woff2 HTTP/1.1" 200 18028 "http://helfer.mmc-berlin.com/assets/theme1.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"
79.210.175.0 - - [25/Nov/2022:16:44:13 +0100] "GET /favicon.ico HTTP/1.1" 200 4754 "http://helfer.mmc-berlin.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56"

**Comment by Caeppi** [comment]
> Hi @Caeppi, thats interesting -> which engelsystem version where you using / how did you installed it? Can you provide the corresponding error logs?

OK, I get a way to activate logfiles, here is the error:
Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php on line 1271

Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php on line 1282

Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php on line 1294

Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php on line 1307

Deprecated: Return type of Illuminate\Support\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Fluent.php on line 95

Deprecated: Return type of Illuminate\Support\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Fluent.php on line 106

Deprecated: Return type of Illuminate\Support\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Fluent.php on line 118

Deprecated: Return type of Illuminate\Support\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Fluent.php on line 129

Deprecated: Return type of Illuminate\Support\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Fluent.php on line 73

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/database/Eloquent/Model.php on line 1658

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/database/Eloquent/Model.php on line 1669

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/database/Eloquent/Model.php on line 1681

Deprecated: Return type of Illuminate\Database\Eloquent\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/database/Eloquent/Model.php on line 1692

Deprecated: Return type of Illuminate\Database\Eloquent\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/database/Eloquent/Model.php on line 1203

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/symfony/http-foundation/ParameterBag.php on line 205

Deprecated: Return type of Symfony\Component\HttpFoundation\ParameterBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/symfony/http-foundation/ParameterBag.php on line 215

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/symfony/http-foundation/HeaderBag.php on line 255

Deprecated: Return type of Symfony\Component\HttpFoundation\HeaderBag::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /hp/cm/ac/kf/www/mmc/helfer/vendor/symfony/http-foundation/HeaderBag.php on line 265
An unexpected error occurred. A team of untrained monkeys has been dispatched to fix it.
Warning: Uncaught Error: Object of class UnwindExit could not be converted to string in /hp/cm/ac/kf/www/mmc/helfer/vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php:8 Stack trace: #0 /hp/cm/ac/kf/www/mmc/helfer/vendor/composer/ClassLoader.php(444): include() #1 /hp/cm/ac/kf/www/mmc/helfer/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/hp/cm/ac/kf/ww...') #2 /hp/cm/ac/kf/www/mmc/helfer/vendor/vlucas/phpdotenv/src/Repository/AdapterRepository.php(5): Composer\Autoload\ClassLoader->loadClass('Dotenv\\Reposito...') #3 /hp/cm/ac/kf/www/mmc/helfer/vendor/composer/ClassLoader.php(444): include('/hp/cm/ac/kf/ww...') #4 /hp/cm/ac/kf/www/mmc/helfer/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/hp/cm/ac/kf/ww...') #5 /hp/cm/ac/kf/www/mmc/helfer/vendor/vlucas/phpdotenv/src/Repository/RepositoryBuilder.php(109): Composer\Autoload\ClassLoader->loadClass('Dotenv\\Reposito...') #6 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Env.php(66): Dotenv\Repository\RepositoryBuilder->make() #7 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/Env.php(81): Illuminate\Support\Env::getRepository() #8 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/support/helpers.php(276): Illuminate\Support\Env::get('CI', false) #9 /hp/cm/ac/kf/www/mmc/helfer/config/config.php(8): env('CI', false) #10 /hp/cm/ac/kf/www/mmc/helfer/src/Config/ConfigServiceProvider.php(45): require('/hp/cm/ac/kf/ww...') #11 /hp/cm/ac/kf/www/mmc/helfer/src/Application.php(68): Engelsystem\Config\ConfigServiceProvider->register() #12 /hp/cm/ac/kf/www/mmc/helfer/src/Application.php(90): Engelsystem\Application->register(Object(Engelsystem\Config\ConfigServiceProvider)) #13 /hp/cm/ac/kf/www/mmc/helfer/includes/application.php(17): Engelsystem\Application->bootstrap(Object(Engelsystem\Config\Config)) #14 /hp/cm/ac/kf/www/mmc/helfer/includes/engelsystem.php(6): require('/hp/cm/ac/kf/ww...') #15 /hp/cm/ac/kf/www/mmc/helfer/public/index.php(7): require_once('/hp/cm/ac/kf/ww...') #16 {main} thrown in /hp/cm/ac/kf/www/mmc/helfer/vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php on line 8

Fatal error: During inheritance of ArrayAccess: Uncaught in /hp/cm/ac/kf/www/mmc/helfer/vendor/vlucas/phpdotenv/src/Repository/AbstractRepository.php on line 8

**Comment by MyIgel** [comment]
SO the remaining question: What engelsystem version are you using? The release or the (currently recommended) main branch version?

**Comment by astro** [comment]
I tried both 3.1.0 (in nixpkgs) and 3.2.0 (last release) to no avail.

**Comment by ximex** [comment]
by the way: PHP 7.4 is deprecated now:
https://www.php.net/supported-versions.php

**Comment by MyIgel** [comment]
And we have a "new old release" which should eventually fix some issues: https://github.com/engelsystem/engelsystem/releases/tag/v3.3.0

**Comment by MyIgel** [comment]
The newest release should hopefully work, if you have further problems you can re-open this issue :)
