### ISSUE TITLE
Error on database install

### ISSUE THREAD

**Issue by matbad** [engelsystem/engelsystem#930]
Hello.
I tried to setup the Engelsystem on my webspace, but unfortunately I am failing on setting up the database.

* When importing the install-v3.2.0.sql from the 3.2.0 release to mariadb, I see the following error:
`ERROR 1100 (HY000) at line 221: Table 'schedules' was not locked with LOCK TABLES`

* I also tried to use the /db/install.sql for setting up the database. While doing this, I get a different error:
`ERROR 1451 (23000) at line 23: Cannot delete or update a parent row: a foreign key constraint fails`

* When using the bin/migrate script to setup the database, I get the information to run composer.phar install first, so I downloaded the composer to the same directory the composer.lock and composer.json are located and ran php composer.phar install. After doing so I get the following error on executing bin/migrate:
```
Exception: Code: 42S01, Message: SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`database`.`migrations`' already exists (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'), File: vendor/illuminate/database/Connection.php:703, Previous: SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`database`.`migrations`' already exists, Trace: [
```

What is the proper way to install the database, since there seem to be different ways, but none of them works for me.

I am sorry if I am missing something obvious. Any help is appreciated, thank you.
Cheers

**Comment by matbad** [comment]
forgot to mention, that I am using version 10.5.15 of MariaDB

**Comment by MyIgel** [comment]
Hi @matbad, that should work (but eventually you want to try the newest releas or directly the main) ^^
The release install .sql ist meant to setup a working engelsystem by its own so no other imports are required. The alternative way (and recommended if you have shell access to the server) is to run the `bin/migrate up` command which creates all tables for you.
To verify and retest it i would suggest using the latest release and (before setting up the database) deleting the old tables.

**Comment by MyIgel** [comment]
I'll close this issue for now, feel free to re-open it when the problem still persists with the newest version :)
