### ISSUE TITLE
Deploy with docker-compose and nginx

### ISSUE THREAD

**Issue by Troumble** [engelsystem/engelsystem#936]
# Deploy with docker-compose and nginx

Hi guys, 
the new IT guy from the Sommerschein-Team here, nice reaching out to you. 
So i got kind of a roadblock whilst deploying the Engelsystem with the supplied docker-compose.yml.

### tl;dr
I tried deploying the Engelsystem with Docker and Nginx, but kind of failed. I think i´m missing some key information that is not well, or at all, Documented yet. I would like to fix the Deploy flow with Docker, and contribute to the Documentation.

### The Idea
Theres a Domain and a Server.
The Domain points to the server via DNS entry.
The Engelsystem is running on the server deployed with Docker. Port 5000.
Nginx then reversy proxys incoming traffic to the Engelsystem

### Whats working?
- [x] Domain DNS entry
- [x] Engelsystem running on port 5000
- [x] Nginx reversy Proxy
- [x] SSL/TLS Https certificate

#### So Whats the Problem?
**If i enable ssl/tls for https everything works fine except that there is no static content displayed.**
<img width="1728" alt="Bildschirmfoto 2022-06-25 um 19 09 37" src="https://user-images.githubusercontent.com/36246867/175783840-6c22db82-5b79-4886-9f0f-d89fefed4eac.png">

**If i disable changes made by certbot and load the page via http it is working**
<img width="1728" alt="Bildschirmfoto 2022-06-25 um 17 15 23" src="https://user-images.githubusercontent.com/36246867/175783893-140c6eeb-dc7f-4b62-bfd2-23a28ac8c8b7.png">

I saw that you guys supplied a nginx.conf file. I tried using that one but nginx just straight stopped working. What am i missing?

### The Code
Heres the `/etc/nginx/site-available/default` file i modified:

```
server {
        server_name engel.sommerschein.de;
        root /var/www/html/;
        index index.html index.htm index.nginx-debian.html;
        location / {
                proxy_pass http://localhost:5000/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/engel.sommerschein.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/engel.sommerschein.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = engel.sommerschein.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name engel.sommerschein.de;
    listen 80;
    return 404; # managed by Certbot
}
```
I´m using the default nginx.conf because the supplied one was not working.

### The Question
What should i do with the supplied nginx.conf?
Why is nginx serving the application without static content after certificate implementation?
What am i overlooking?

Greetings from Germany and the Sommerschein team, wich is using the Engelsystem for the last 3 years. 

Feel free adding labels and doing stuff. Im new here and dont have the overview yet 😅 

> the old one burned up for everyone wondering 👍

**Comment by Troumble** [comment]
# Hooray found a fix

`/etc/nginx/sites-available/default` now looks like this:

```
server {
    listen        80;
    server_name engel.sommerschein.de;
    location / {
        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/engel.sommerschein.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/engel.sommerschein.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = engel.sommerschein.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name engel.sommerschein.de;
    listen 80;
    return 404; # managed by Certbot


}
```

**Comment by manzari** [comment]
I am experiencing the same issue.

I am running the provided container with unchanged nginx.conf behind a traefik container that does nothing but add ssl via letsencrypt. This seems to break CSP.

`Content Security Policy: The page’s settings blocked the loading of a resource at http://orgneedsangels.com/assets/theme1-3e1f6ce61cb8585d9628.css (“default-src”).`

Can you give us any hint @MyIgel  how to resolve this issue?

**Comment by MyIgel** [comment]
@manzari even as this seems to be a potentially slightly unrelated issue, the easiest option would be to set the application `url` with https (so `'url' => 'https://orgneedsangels.com',`).

**Comment by MyIgel** [comment]
I'll close this issue for now, if you still have the problem feel free to re-open it :)
