### ISSUE TITLE
No Mail after registration

### ISSUE THREAD

**Issue by stirlingzero** [engelsystem/engelsystem#937]
After login in, in to the engelsystem of angel.mch2022.org, i got no email for my registration.
I used a password the is longer than 20 characters, used big and small letters, as same as numbers and special characters.
I couldn't login, until i reseted my password via email.
Might be my own stupidity, but could also be a bug.
Greetings : )

**Comment by MyIgel** [comment]
Hi, I tested it with a 42 characters random pw and it worked -> without further testing data i would say u'r eventually just a slightly bit lost ;)
