### ISSUE TITLE
Driving license option is not shown in profile without admin_user

### ISSUE THREAD

**Issue by SolidTux** [engelsystem/engelsystem#988]
When a user doesn't have the `admin_user` permission, they can edit their driver license state via `https://example.com/user-driver-licenses`, but the option doesn't show up in the profile.

**Comment by MyIgel** [comment]
Hi @SolidTux, the link for the user is shown on the angeltype that requires the driving license (with a hint that it needs to be added if the user has not entered it).
-> I would prefer not to show it for all users to prevent eventual confusion but could show it when the user is in an angeltype that requires a license.

**Comment by SolidTux** [comment]
That's a good solution. Thank you so much for super fast implementation!
